codelab-app/platform

.circleci/config.yml, .github/PULL_REQUEST_TEMPLATE.md, libs/components/ui/src/components/form/Form.types.ts, libs/components/ui/src/components/form/data/Form-4--node.data.ts, libs/components/ui/src/components/select/Select.spec.tsx, libs/components/ui/src/components/select/Select.types.ts
story(libs-components-ui): add example for form select helper
Fixes #
=> story(libs-components-ui): add example for form select helper

.gitignore
=> chore: add lsp logs to .gitignore

.circleci/config.yml, package.json
=> revert: revert node to 14

libs/core/graph/src/graph/graph.tsx, libs/core/renderer/src/ElementFactory.tsx, libs/core/renderer/src/TreeDom.tsx, libs/core/traversal/src/traversal-iteratee.tsx, libs/core/traversal/src/traversal.ts, libs/core/tree/src/tree-factory.tsx, libs/factory/src/tree/strategy/Tree-strategy--graph.tsx, libs/factory/src/tree/strategy/Tree-strategy--tree.tsx, libs/shared/interface/graph/src/graph.ts, libs/shared/interface/graph/src/traversal.ts, libs/shared/interface/node/src/node.ts, libs/shared/interface/tree/src/tree.ts
=> Props typing

.vscode/settings.json, apps/docs/src/components/layout.tsx, apps/web/pages/node.tsx, apps/web/src/node/utils/convertNodeTreeToAntTreeNode.spec.ts, libs/core/node/src/index.ts, libs/core/node/src/node-entity.tsx, libs/core/node/src/node-factory.spec.ts, libs/core/node/src/node-factory.ts, libs/core/renderer/src/TreeDom.tsx, libs/core/renderer/src/component.interface.tsx, libs/core/traversal/src/traversal-iteratee.tsx, libs/core/traversal/src/traversal-strategy.ts, libs/core/traversal/src/traversal.ts, libs/core/tree/src/node.spec.ts, libs/core/tree/src/tree-entity.tsx, libs/core/tree/src/tree-factory.tsx, libs/factory/src/tree/strategy/Tree-strategy--graph.tsx, libs/factory/src/tree/strategy/Tree-strategy--react.tsx, libs/factory/src/tree/strategy/Tree-strategy--tree.tsx, libs/shared/interface/node/src/assertions/node-assertions.ts, libs/shared/interface/node/src/index.ts, libs/shared/interface/node/src/node.ts, libs/shared/interface/tree/src/index.ts, libs/shared/interface/tree/src/tree.ts, package.json, yarn.lock
=> Node factory specs

libs/core/node/src/node-factory.spec.ts, libs/core/node/src/node-factory.ts, libs/core/node/src/node-mapper.ts, libs/core/node/src/node-repository.spec.ts, libs/core/node/src/node-repository.ts, libs/core/node/src/node-service.ts, libs/core/node/src/validator.ts
=> Repository pattern

libs/core/node/src/node-repository.spec.ts
=> test(libs-core-node): remove node repo test

.circleci/config.yml, .huskyrc.js
=> Ci docker executor

apps/web/pages/_app.tsx, apps/web/pages/tree.tsx, apps/web/src/node/NodeTree.tsx, apps/web/src/tree/ButtonGroup.tsx, libs/core/node/src/node-entity.tsx, libs/shared/interface/node/src/node.ts, package.json, yarn.lock
=> 71 duplicate node tree builder

apps/web-e2e/src/integration/pages-node.ts, apps/web-e2e/src/support/commands.ts, apps/web-e2e/src/support/index.d.ts
=> test(apps-web-e2e): create node form

apps/api/gateway/src/app/app.service.ts, apps/api/gateway/src/federation/federation.module.ts, apps/api/gateway/src/main.ts, apps/api/services/graph/src/main.ts, apps/api/services/props/src/main.ts, apps/api/services/user/src/main.ts, libs/api/config/src/config.ts, libs/api/drivers/mongoose/src/drivers/mongoose-drivers.module.ts, libs/api/drivers/neo4j/src/drivers/neo4j-drivers.provider.ts, libs/api/schema/node/src/lib/node.input.ts, libs/api/schema/node/src/lib/node.model.ts, libs/api/schema/node/src/lib/node.resolvers.ts, package.json, yarn.lock
=> Fix enum graphql

libs/core/renderer/src/libs/renderer-components.tsx, libs/ui/antd/src/components/button/Button.data.ts, libs/ui/antd/src/components/button/Button.stories.tsx, libs/ui/antd/src/props/Props-renderProps.spec.tsx
@webberwang  please have a look 
ISSUES CLOSED: #190
Fixes #
=> feat(libs-core-props): #190 override internal props with external ones

docker-compose.yml
@webber I've quickly set up docker-compose for databases for local development. Maybe it will be useful for you.
Fixes #
=> chore(apps): docker-compose with mongo and neo4j for local dev

documentation/ci-cd/circleci.md
=> docs: add docs for circleci

.docker/Dockerfile, .docker/run.sh
=> change cmd overidding

.circleci/config.yml, .kubernetes/base/ambassador-demo.yaml, .kubernetes/base/ambassador.yaml, .kubernetes/base/deployment.yaml, .kubernetes/base/kustomization.yaml, .kubernetes/base/mapping.yaml, .kubernetes/base/service.yaml, .kubernetes/overlays/staging/deployment.yaml, .kubernetes/overlays/staging/kustomization.yaml, .kubernetes/setup.sh, .kubernetes/setup/ambassador.sh, .storybook/main.js, package.json, yarn.lock
=> Storybook addon code

.circleci/config.yml
=> ci: install nvm

libs/ui/antd/src/components/form/json-schema/Form-edge.tsx, libs/ui/antd/src/components/form/json-schema/Form-graph.tsx, libs/ui/antd/src/components/form/json-schema/Form-vertex.tsx
=> feat(libs-ui-antd): #277 create form stories for vertex, edge, graph

.docker/docker-compose.yaml, apps/api/graph/src/models/user/user.entity.ts, apps/api/graph/tsconfig.app.json, documentation/getting-started/4-getting-started.md, documentation/issues/dotenv.md, documentation/issues/typeorm.md, libs/api/providers/config/src/hasura/config-graphql-hasura.service.ts, libs/shared/utils/src/config.ts, makefile
=> refactor(apps-api-graph): use optional chain

libs/api/providers/config/src/config.module.ts, libs/api/providers/config/src/config.ts
=> ci: remove un-used config

.circleci/config.yml, .docker/Dockerfile, .docker/docker-compose.build.yaml, .docker/docker-compose.yaml, scripts/docker/build.sh
=> ci: create separate docker compose for building

libs/shared/factory/.eslintrc.js, libs/shared/factory/src/cytoscape.js/Cytoscape.stories.tsx, libs/shared/factory/src/cytoscape.js/demo-data.ts, libs/shared/factory/src/cytoscape.js/factory.spec.ts, libs/shared/factory/src/cytoscape.js/mapper.ts, libs/shared/interface/graph-v2/src/vertex.ts, package.json, workspace.json, yarn.lock
=> 0 cytoscape bfs

documentation/getting-started/4-getting-started.md
=> docs: fix command in codegen section (#333)

.docker/docker-compose.build.yaml, scripts/docker/build.sh, scripts/docker/push.sh
=> ci: fix build and deploy docker

.docker/docker-compose.yaml, package.json, yarn.lock
=> ci: fix pm2-runtime

scripts/lint/git.sh
=> 0 e2e tests

libs/api/providers/config/src/config.module.ts, libs/api/providers/config/src/hasura/config-graphql-hasura.service.ts
=> fix(apps-api-graph): make joi to number

libs/api/providers/config/src/checkDotEnvExistence.ts, libs/api/providers/config/src/config.module.ts
=> build(libs-api-providers): #354 throw error if .env exists

apps/api/graph/.hasura/metadata/tables.yaml, apps/api/graph/src/models/app/codelab-app.entity.ts, apps/api/graph/src/models/page/page.entity.ts, apps/api/graph/src/models/user/user.entity.ts
=> fix: fix hasura schema

.docker/docker-compose.yaml
=> ci: add pg admin docker

workspace.json
=> fix: apollo state import

.kubernetes/kustomize/overlays/prod/ingress.yaml, .kubernetes/kustomize/overlays/prod/kustomization.yaml, .kubernetes/kustomize/overlays/prod/patches/api_graph.yaml, .kubernetes/kustomize/overlays/prod/patches/hasura.yaml, documentation/kubernetes/prod-vault-k8s-auth.md
Production app was not integrated with Vault
Integrated Vault to Prod apps 
https://github.com/codelab-ai/codelab.ai/issues/314
Fixes #
=> Vault prod

libs/modules/users/src/core/application/handlers/CreateUserCommandHandler.ts, libs/modules/users/src/core/application/services/CreateUserService.ts, libs/modules/users/src/core/application/useCases/createUser/CreateUserResponse.ts, libs/modules/users/src/infrastructure/persistence/TypeOrmUserRepositoryAdapter.ts, libs/modules/users/src/presentation/controllers/UserCommandQueryAdapter.ts
=> 0 type layers

.storybook/grid.scss, apps/web/pages/_app.tsx, apps/web/pages/apps.tsx, libs/modules/app-stories/src/model/store/machine-app.tsx, libs/modules/grid-stories/src/Grid.stories.tsx, libs/modules/grid-stories/src/index.ts, libs/modules/grid-stories/src/store/index.ts, libs/modules/grid-stories/src/store/machine-grid.ts, libs/modules/grid-stories/src/store/useGrid.ts, libs/modules/grid-stories/src/useCases/dragGrid/DragGridState.tsx, libs/modules/grid-stories/src/useCases/index.ts, libs/modules/layout-stories/src/AppLayout.tsx, libs/modules/modal-stories/src/ModalContainer.tsx, libs/tools/plugins/codelab/src/migrations/update-10-3-2/update-10-3-2.ts, package.json, yarn.lock
=> feat: add grid xstate

libs/modules/app/src/lib/modules-app.module.ts, libs/modules/header-stories/src/HeaderMenu.tsx, libs/modules/layout-stories/src/AppLayout.tsx, libs/modules/layout-stories/src/AppLayoutContainer.tsx, libs/modules/modal-stories/src/ModalContainer.tsx, libs/modules/user-stories/src/index.ts, libs/modules/user-stories/src/store/machine-user.ts, libs/modules/user-stories/src/useCases/userLogin/UserLoginForm.tsx, libs/modules/user-stories/src/useCases/userLogin/UserLoginState.ts, libs/modules/user-stories/src/useCases/userLogin/userLoginServices.ts, libs/modules/user-stories/src/useCases/userSignout/UserSignOutButton.tsx, libs/modules/user-stories/src/useCases/userSignout/UserSignOutButtonContainer.tsx, libs/modules/user-stories/src/useCases/userSignout/UserSignOutServices.ts, libs/modules/user-stories/src/useCases/userSignout/UserSignOutState.ts, libs/modules/user-stories/src/useCases/userSignout/index.ts, libs/modules/user-stories/src/useCases/userSignup/UserSignupForm.tsx, libs/modules/user-stories/src/useCases/userSignup/UserSignupServices.ts, libs/modules/user-stories/src/useCases/userSignup/UserSignupState.ts, libs/modules/user-stories/src/useCases/userSignup/index.ts, libs/modules/user/src/core/application/useCases/registerUser/RegisterUserUseCase.i.spec.ts, makefile
=> 414 front end auth refactor

libs/modules/app/src/core/application/useCases/createApp/CreateApp.generated.ts, libs/modules/app/src/core/application/useCases/createApp/CreateApp.graphql, libs/modules/app/src/core/application/useCases/createApp/CreateAppUseCase.i.spec.ts, libs/modules/app/src/core/application/useCases/deleteApp/DeleteApp.generated.ts, libs/modules/app/src/core/application/useCases/deleteApp/DeleteApp.graphql, libs/modules/user-stories/src/useCases/registerUser/RegisterUserInput.generated.ts, libs/modules/user-stories/src/useCases/registerUser/RegisterUserInput.graphql, libs/modules/user/src/core/adapters/UserRepositoryPort.ts, libs/modules/user/src/core/application/useCases/loginUser/LoginUserUseCase.i.spec.ts, libs/modules/user/src/core/application/useCases/registerUser/RegisterUser.generated.ts, libs/modules/user/src/core/application/useCases/registerUser/RegisterUser.graphql, libs/modules/user/src/core/application/useCases/registerUser/RegisterUserUseCase.i.spec.ts, libs/modules/user/src/core/application/useCases/updateUser/UpdateUserInput.ts, libs/modules/user/src/core/application/useCases/updateUser/UpdateUserRequest.ts, libs/modules/user/src/core/application/useCases/updateUser/UpdateUserResponse.ts, libs/modules/user/src/core/application/useCases/updateUser/UpdateUserService.ts, libs/modules/user/src/core/application/useCases/updateUser/UpdateUserUseCase.i.spec.ts, libs/modules/user/src/infrastructure/persistence/TypeOrmUserRepositoryAdapter.ts, libs/modules/user/src/presentation/UserDto.ts
=> refactor: use generated graphql for e2e

apps/web/pages/apps/index.tsx, libs/modules/app-stories/src/model/index.ts, libs/modules/app-stories/src/model/store/machine-app.tsx, libs/modules/app-stories/src/useCases/createApp/CreateAppForm.tsx, libs/modules/app-stories/src/useCases/createApp/CreateAppModal.tsx, libs/modules/app-stories/src/useCases/createApp/CreateAppService.ts, libs/modules/app-stories/src/useCases/createApp/CreateAppState.ts, libs/modules/app-stories/src/useCases/deleteApp/DeleteAppInput.generated.ts, libs/modules/app-stories/src/useCases/deleteApp/DeleteAppInput.graphql, libs/modules/app-stories/src/useCases/deleteApp/DeleteAppService.ts, libs/modules/app-stories/src/useCases/deleteApp/DeleteAppState.ts, libs/modules/app-stories/src/useCases/deleteApp/index.ts, libs/modules/app-stories/src/useCases/deleteApp/useDeleteApp.tsx, libs/modules/app-stories/src/useCases/getApps/GetAppsItem.tsx, libs/modules/app-stories/src/useCases/getApps/GetAppsList.tsx, libs/modules/app-stories/src/useCases/getApps/GetAppsService.ts, libs/modules/app-stories/src/useCases/getApps/GetAppsState.ts, libs/modules/user-stories/src/useCases/registerUser/RegisterUserForm.tsx, libs/modules/user-stories/src/useCases/registerUser/RegisterUserModal.tsx, libs/modules/user-stories/src/useCases/userLogin/UserLoginModal.tsx
=> 448 create and delete app

apps/api/codelab/src/app/heroes/commands/handlers/drop-ancient-item.handler.ts, apps/api/codelab/src/app/heroes/commands/handlers/kill-dragon.handler.ts, apps/api/codelab/src/app/heroes/events/handlers/dragon-revived.handler.ts, apps/api/codelab/src/app/heroes/events/handlers/hero-found-item.handler.ts, apps/api/codelab/src/app/heroes/events/handlers/hero-killed-dragon.handler.ts, apps/api/codelab/src/app/heroes/events/handlers/index.ts, apps/api/codelab/src/app/heroes/events/impl/dragon-revived.event.ts, apps/api/codelab/src/app/heroes/models/hero.model.ts, apps/api/codelab/src/app/heroes/queries/handlers/get-heroes.handler.ts, apps/api/codelab/src/app/heroes/sagas/heroes.sagas.ts, package.json
=> feat: example for saga multiple events

libs/modules/app-stories/src/useCases/createApp/CreateAppInput.generated.ts, libs/modules/app-stories/src/useCases/createApp/CreateAppInput.graphql, libs/modules/app-stories/src/useCases/editApp/EditAppForm.tsx, libs/modules/app-stories/src/useCases/editApp/EditAppInput.generated.ts, libs/modules/app-stories/src/useCases/editApp/EditAppInput.graphql, libs/modules/app-stories/src/useCases/editApp/EditAppService.ts, libs/modules/app-stories/src/useCases/editApp/EditAppState.ts, libs/modules/app-stories/src/useCases/getApps/GetAppsItem.tsx, libs/modules/app/src/core/adapters/AppRepositoryPort.ts, libs/modules/app/src/core/application/commands/UpdateAppCommand.ts, libs/modules/app/src/core/application/handlers/UpdateAppCommandHandler.ts, libs/modules/app/src/core/application/useCases/updateApp/UpdateApp.generated.ts, libs/modules/app/src/core/application/useCases/updateApp/UpdateApp.graphql, libs/modules/app/src/core/application/useCases/updateApp/UpdateAppErrors.ts, libs/modules/app/src/core/application/useCases/updateApp/UpdateAppInput.generated.ts, libs/modules/app/src/core/application/useCases/updateApp/UpdateAppInput.ts, libs/modules/app/src/core/application/useCases/updateApp/UpdateAppRequest.ts, libs/modules/app/src/core/application/useCases/updateApp/UpdateAppResponse.ts, libs/modules/app/src/core/application/useCases/updateApp/UpdateAppService.ts, libs/modules/app/src/core/application/useCases/updateApp/UpdateAppUseCase.spec.ts, libs/modules/app/src/core/application/useCases/updateApp/UpdateAppUseCase.ts, libs/modules/app/src/core/application/useCases/updateApp/index.ts, libs/modules/app/src/framework/AppDITokens.ts, libs/modules/app/src/framework/nestjs/AppModule.ts, libs/modules/app/src/index.ts, libs/modules/app/src/infrastructure/persistence/TypeOrmAppRepositoryAdapter.ts, libs/modules/app/src/presentation/controllers/AppCommandQueryAdapter.ts, schema.graphql
=> 483 connect edit app service to backend

libs/backend/src/infrastructure/persistence/typeorm/entity/TypeOrmEdge.ts, libs/backend/src/infrastructure/persistence/typeorm/entity/TypeOrmGraph.ts, libs/backend/src/infrastructure/persistence/typeorm/entity/TypeOrmVertex.ts, libs/modules/app/src/infrastructure/persistence/TypeOrmAppRepositoryAdapter.ts, libs/modules/graph/src/infrastructure/persistence/TypeOrmGraphRepositoryAdapter.ts, libs/modules/page/src/core/application/commands/DeletePageCommand.ts, libs/modules/page/src/core/application/handlers/DeletePageCommandHandler.ts, libs/modules/page/src/core/application/useCases/deletePage/DeletePageErrors.ts, libs/modules/page/src/core/application/useCases/deletePage/DeletePageInput.ts, libs/modules/page/src/core/application/useCases/deletePage/DeletePageRequest.ts, libs/modules/page/src/core/application/useCases/deletePage/DeletePageResponse.ts, libs/modules/page/src/core/application/useCases/deletePage/DeletePageService.ts, libs/modules/page/src/core/application/useCases/deletePage/DeletePageUseCase.i.spec.ts, libs/modules/page/src/core/application/useCases/deletePage/DeletePageUseCase.ts, libs/modules/page/src/framework/PageDITokens.ts, libs/modules/page/src/framework/nestjs/PageModule.ts, libs/modules/page/src/infrastructure/persistence/TypeOrmPageRepositoryAdapter.ts, libs/modules/page/src/presentation/controllers/PageCommandQueryAdapter.ts, libs/tools/plugins/codelab/src/schematics/library/use-case/helpers/modify-files.ts
Fixes #490 #441 #495
Please note, in order for DeletePageUseCase to work, you need to reset the database by setting synchronize and dropSchema to true in DatabaseModule
=> feat(apps-api-codelab): inject base repository

.circleci/config.yml
=> ci: add docker image build

.circleci/config.yml
=> ci: workflow back to tagging condition

.circleci/config.yml, apps/web/pages/_app.tsx, libs/generated/src/json-schema.generated.ts, package.json, scripts/postinstall.sh
=> ci: app-staging only work on tags

apps/web/pages/demo/groupedForm/index.tsx, apps/web/src/demoGroupedForm/GroupedTemplates.tsx, apps/web/src/demoGroupedForm/RJSFCustomGroupedTemplate.tsx
=> feat(apps-web): #552 rjsf grouped template demo

libs/generated/src/jsonSchema.generated.ts, libs/modules/graph/src/core/application/useCases/updateVertex/UpdateVertexInput.ts
=> fix: schema generation

libs/alpha/ui/component/src/form/Form.stories.tsx, libs/alpha/ui/component/src/form/examples/Form-new-grid.tsx, libs/alpha/ui/component/src/form/rjsf-templates/ObjectGridTemplate.tsx, package.json, yarn.lock
=> feat(apps-api-codelab): grid widget with order

.env.example
=> feat: update env example

apps/web/src/useCases/component/paneMain/Pane-config--props.tsx, apps/web/src/useCases/lambda/paneMain/Pane-main--lambda.tsx, apps/web/src/useCases/pages/getPage/GetPageLayout.tsx, documentation/getting-started/9-codegen.md, libs/alpha/ui/antd/src/components/rgl/RGL.tsx, libs/frontend/src/renderer/Renderer-children.tsx, libs/frontend/src/renderer/Renderer-components.tsx, libs/frontend/src/renderer/elementTypeMap.tsx, libs/modules/app/src/core/domain/App.ts, libs/tools/plugins/codelab/src/generators/library/domain-module/schema.json, libs/tools/plugins/codelab/src/generators/library/use-case/schema.json, prisma/schema.prisma
=> feat: fix renderer

apps/web/src/pages/builder/Editor.tsx, apps/web/src/templates/Layout.tsx, apps/web/src/useCases/pages/getPage/GetPageLayout.tsx, libs/alpha/ui/antd/src/components/grid/Grid.tsx, libs/frontend/src/cytoscape/CytoscapeService.tsx, libs/frontend/src/renderer/Renderer-components.tsx, libs/frontend/src/renderer/craftjsResolver.tsx, libs/frontend/src/renderer/index.ts
=> 609 integration craftjs

documentation/getting-started/12-rjsf.md, jest.config.js, libs/tools/rjsf/.babelrc, libs/tools/rjsf/.eslintrc.js, libs/tools/rjsf/README.md, libs/tools/rjsf/babel-jest.config.json, libs/tools/rjsf/jest.config.js, libs/tools/rjsf/src/decorators/Rjsf.ts, libs/tools/rjsf/src/decorators/RjsfProperty.ts, libs/tools/rjsf/src/examples/Simple.ts, libs/tools/rjsf/tsconfig.eslint.json, libs/tools/rjsf/tsconfig.json, libs/tools/rjsf/tsconfig.lib.json, libs/tools/rjsf/tsconfig.spec.json, nx.json, package.json, tsconfig.base.json, workspace.json, yarn.lock
feat: add example for rjsf
feat: add example for rjsf
Fixes #
=> feat: add example for rjsf

.circleci/config.yml, .vault/agent.hcl
=> ci: migrate vault to vault-cloud hashicorp

apps/web/.gitignore, package.json, yarn.lock
=> chore: update gitignore

workspace.json
=> build(apps-web): fix nx serve web

libs/backend/src/framework/nestjs/infrastructure.module.ts, libs/backend/src/framework/nestjs/test-infrastructure.module.ts, libs/backend/src/infrastructure/persistence/aws/AwsLambdaService.ts, libs/backend/src/infrastructure/persistence/aws/AwsS3Service.ts
=> fix: api compile errors

documentation/getting-started/4-getting-started.md, libs/backend/src/framework/nestjs/infrastructure.module.ts, libs/backend/src/framework/nestjs/test-infrastructure.module.ts, makefile, scripts/test/e2e.sh, workspace.json
=> fix: remove graphql

.github/config.yml, hasura/config.yaml, makefile
=> feat: enable github todo plugin

.env.example, README.md, documentation/README.admin.md, documentation/getting-started/1-installation.md, documentation/getting-started/2-tech-stack.md, documentation/getting-started/3-project-structure.md, documentation/getting-started/4-getting-started.md
=> docs: update docs

apps/web/src/useCases/apps/AppProvider.tsx, apps/web/src/useCases/lambda/getLambdas/GetLambdasTable.tsx, apps/web/src/useCases/pages/getPage/GetPageLayout.tsx, apps/web/src/useCases/styles/assignStyle/AssignStyleForm.tsx, apps/web/src/useCases/styles/paneConfig/Pane-config--style.tsx, libs/frontend/src/cytoscape/CytoscapeService.tsx, libs/generated/src/graphql-client-hasura.generated.ts, relay.config.js, schema.graphql
=> fix: lint errors

.env.example
=> style(apps): fix .env.example code-style

.env.example, apps/web-e2e/src/support/commands.ts, hasura/config.yaml, hasura/metadata/databases/default/tables/public_app.yaml, hasura/metadata/databases/default/tables/public_page.yaml, hasura/metadata/databases/default/tables/public_prop.yaml, hasura/migrations/default/1616898368796_run_sql_migration/down.sql, hasura/migrations/default/1616898368796_run_sql_migration/up.sql, hasura/migrations/default/1616898420021_run_sql_migration/down.sql, hasura/migrations/default/1616898420021_run_sql_migration/up.sql, hasura/migrations/default/1616898458645_run_sql_migration/down.sql, hasura/migrations/default/1616898458645_run_sql_migration/up.sql, makefile, package.json, yarn.lock
=> feat(apps-api-codelab): hasura env vars and migrations update

apps/web/src/pages/LayoutFactory.tsx, libs/frontend/shared/src/state/apollo/apolloClient.ts, libs/generated/src/graphql-client-hasura.generated.ts, libs/hasura/src/graphql-client-hasura.generated.ts, libs/modules/app/src/createApp/CreateAppForm.tsx, libs/modules/app/src/deleteApp/useDeleteAppConfirmation.ts, libs/modules/app/src/editApp/EditAppForm.tsx, libs/modules/app/src/getApps/GetAppsList.tsx, libs/modules/page/src/createPage/CreatePage.graphql, libs/modules/page/src/createPage/CreatePage.hasura.graphql, libs/modules/page/src/createPage/CreatePageForm.tsx, libs/modules/page/src/createPage/createPageSchema.ts, libs/modules/page/src/deletePage/DeletePage.hasura.graphql, libs/modules/page/src/deletePage/DeletePageButton.tsx, libs/modules/page/src/getPage/GetPage.hasura.graphql, libs/modules/page/src/getPages/GetPagesList.hasura.graphql, libs/modules/page/src/getPages/GetPagesList.tsx, libs/modules/page/src/updatePage/UpdatePage.hasura.graphql, libs/modules/page/src/updatePage/UpdatePageForm.tsx, libs/modules/page/src/updatePage/updateFromSchema.ts
=> 658 complete crud for pages

.circleci/config.yml, makefile
=> feat: graphql relay

.circleci/config.yml, .ebextensions/01_options.config, .ebignore, .elasticbeanstalk/config.yml, .gitignore, .platform/hooks/prebuild/yarn.sh, Procfile, apps/api/pm2.json, package.json, workspace.json
There is no beanstalk deployment today.
This will trigger deploying the updates to beanstalk on tag releases.
Fixes #
=> feat(circleci): include beanstalk deploy in cicd (#700)

.circleci/config.yml
=> feat(ci): add app-prod workflow to deploy

apps/web/src/pages/home/Home-menu--header.tsx, libs/generated/.eslintrc.json, libs/generated/README.md, libs/generated/tsconfig.json, libs/generated/tsconfig.lib.json, libs/hasura/README.md, libs/hasura/tsconfig.json, libs/hasura/tsconfig.lib.json, libs/modules/README.md, makefile, nx.json, tsconfig.base.json, workspace.json
=> ci: change ci lint

apps/web/src/pages/pane-main/Pane-main.tsx, libs/frontend/shared/src/components/crudModal/crudModalsState.ts, libs/hasura/src/graphql-client-hasura.generated.ts, libs/modules/library/src/GetLibrary.graphql, libs/modules/library/src/Library.fragments.graphql, libs/modules/library/src/createLibrary/CreateLibrary.graphql, libs/modules/library/src/createLibrary/CreateLibraryButton.tsx, libs/modules/library/src/createLibrary/CreateLibraryForm.tsx, libs/modules/library/src/createLibrary/createLibrarySchema.ts, libs/modules/library/src/createLibrary/index.ts, libs/modules/library/src/deleteLibrary/DeleteLibrary.graphql, libs/modules/library/src/deleteLibrary/DeleteLibraryForm.tsx, libs/modules/library/src/deleteLibrary/deleteLibrarySchema.ts, libs/modules/library/src/deleteLibrary/index.ts, libs/modules/library/src/getLibraries/GetLibrariesList.graphql, libs/modules/library/src/getLibraries/GetLibrariesList.tsx, libs/modules/library/src/getLibraries/index.ts, libs/modules/library/src/index.ts, libs/modules/library/src/paneMain/Pane-library.tsx, libs/modules/library/src/paneMain/index.ts, libs/modules/library/src/updateLibrary/UpdateLibrary.graphql, libs/modules/library/src/updateLibrary/UpdateLibraryForm.tsx, libs/modules/library/src/updateLibrary/index.ts, libs/modules/library/src/updateLibrary/updateLibrarySchema.ts
=> 664 refactor left sidebar

apps/doc/gatsby-node.js, apps/doc/src/pages/index.tsx
=> docs(apps-doc): add documentation for modules

apps/web/pages/api/graphql.ts, libs/hasura/src/graphql-client-hasura.generated.ts, libs/modules/app/src/createApp/CreateAppForm.tsx, libs/modules/prop/src/fragments/Prop.fragments.graphql
=> Fixes CreateApp, proxyTimeout, values_aggregate

apps/web/pages/api/github/events.ts
=> ci: webhook for slack

.env.example, .husky/post-merge
=> chore: update env example

apps/web-e2e/src/integration/atom.spec.ts, apps/web-e2e/src/plugins/index.js, apps/web-e2e/src/support/commands.ts, apps/web/src/pages/pane-main/Pane-main.tsx, libs/frontend/shared/src/components/form/uniforms/Form-uniforms--modal.tsx, libs/frontend/shared/src/components/modal/CrudModal.tsx, libs/hasura/src/graphql-client-hasura.generated.ts, libs/modules/atom/src/createAtom/CreateAtomButton.tsx, libs/modules/atom/src/createAtom/CreateAtomForm.tsx, libs/modules/atom/src/deleteAtom/DeleteAllAtoms.graphql, libs/modules/atom/src/deleteAtom/DeleteAtomForm.tsx, libs/modules/atom/src/getAtoms/GetAtomsList.tsx, libs/modules/atom/src/paneMain/Pane-atom.tsx, libs/modules/atom/src/updateAtom/UpdateAtomForm.tsx
=> test(apps-web-e2e): #751 atom  CRUD Tests

apps/web-e2e/cypress.json, apps/web-e2e/src/integration/apps.spec.ts, apps/web-e2e/src/support/commands.ts, libs/hasura/src/graphql-client-hasura.generated.ts, libs/modules/app/src/updateApp/UpdateApp.graphql, libs/modules/app/src/updateApp/UpdateAppForm.tsx
=> test(apps-web-e2e): #748 apps CRUD

apps/web-e2e/src/integration/apps.spec.ts, apps/web-e2e/src/support/commands.ts
=> 748 specs for app

apps/web-e2e/src/integration/apps.spec.ts, apps/web-e2e/src/integration/pages.spec.ts, apps/web-e2e/src/support/commands.ts, apps/web/src/pages/pane-main/Pane-main.tsx, libs/hasura/src/graphql-client-hasura.generated.ts, libs/modules/app/src/deleteApp/DeleteAppByUser.graphql, libs/modules/page/src/getPages/GetPagesList.tsx
=> 749 cypress spec for pages

apps/web-e2e/src/integration/library.spec.ts, apps/web-e2e/src/integration/pages.spec.ts, apps/web-e2e/src/support/commands.ts, libs/frontend/shared/src/components/button/ListItemDeleteButton.tsx, libs/frontend/shared/src/components/button/ListItemSettingsButton.tsx, libs/frontend/shared/src/components/button/index.ts, libs/hasura/src/graphql-client-hasura.generated.ts, libs/modules/library/src/deleteLibrary/DeleteUserLibraries.graphql, libs/modules/library/src/getLibraries/GetLibrariesList.tsx, libs/modules/page/src/getPages/GetPagesList.tsx
=> 750 cypress spec for library

apps/web/pages/apps/index.tsx, dgraph/schema.graphql, libs/dgraph/src/graphql-client-dgraph.generated.ts, libs/frontend/shared/src/components/form/uniforms/Form-uniforms--types.tsx, libs/frontend/shared/src/components/form/uniforms/Form-uniforms.tsx, libs/modules/app/src/App.d.graphql, libs/modules/app/src/createApp/CreateAppForm.tsx, libs/modules/app/src/createApp/CreateAppMutation.d.graphql, libs/modules/app/src/createApp/CreateAppMutation.graphql, libs/modules/app/src/createApp/createAppSchema.ts, libs/modules/app/src/deleteApp/DeleteApp.d.graphql, libs/modules/app/src/deleteApp/DeleteApp.graphql, libs/modules/app/src/deleteApp/DeleteAppForm.tsx, libs/modules/app/src/deleteApp/useDeleteAppConfirmation.ts, libs/modules/app/src/getApps/GetAppItem.d.graphql, libs/modules/app/src/getApps/GetAppItem.graphql, libs/modules/app/src/getApps/GetAppsItem.tsx, libs/modules/app/src/getApps/GetAppsList.d.graphql, libs/modules/app/src/getApps/GetAppsList.tsx, libs/modules/app/src/state.ts, libs/modules/app/src/updateApp/UpdateApp.d.graphql, libs/modules/app/src/updateApp/UpdateApp.graphql, libs/modules/app/src/updateApp/UpdateAppForm.tsx, libs/modules/atom/src/dGraph/Atom.fragments.d.graphql, libs/modules/user/src/index.ts, libs/modules/user/src/ownerSchema.ts, package.json, schema.dgraph.graphql, scripts/graphql/watch-codegen.js, yarn.lock
=> feat: app dgraph

libs/backend/src/application/auth/auth.module.ts, libs/backend/src/application/auth/jwt.strategy.ts, libs/modules/app-api/src/app.resolver.ts, libs/modules/user-api/src/use-cases/create-user/create-user.service.ts, libs/modules/user-api/src/user.module.ts, libs/modules/user-api/src/user.resolver.ts
=> wip: auth guard working

apps/web-e2e/src/integration/component.spec.ignore.ts, apps/web-e2e/src/integration/componentElement.spec.ignore.ts, apps/web-e2e/src/integration/library.spec.ignore.ts, apps/web-e2e/src/integration/user.spec.ts, apps/web-e2e/src/support/commands.ts, apps/web/src/pages/home/Home-menu--header.tsx, apps/web/src/styles/App.less
=> 855 cypres specs app user

.circleci/config.yml, .terraform/.env.example, .terraform/cloudfront.tf, .terraform/ecs.tf, .terraform/parameterstore.tf, .terraform/route53.tf, .terraform/templates/ecs/cb_app.json.tpl, .terraform/vars.tf
=> feat: update ci to deploy ecs staging

libs/tools/scripts/src/dgraph/codegen.js, libs/tools/scripts/src/dgraph/dropSchema.js, package.json
=> ci: update dgraph scripts

libs/modules/atom-api/src/atom.model.ts, libs/modules/atom-api/src/atom.resolver.ts, libs/modules/atom-api/src/use-cases/create-atom/create-atom.i.spec.ts, libs/modules/atom-api/src/use-cases/delete-atom/delete-atom.i.spec.ts, libs/modules/atom-api/src/use-cases/get-atom/get-atom.i.spec.ts, libs/modules/atom-api/src/use-cases/get-atoms/get-atoms.i.spec.ts, libs/modules/atom-api/src/use-cases/update-atom/update-atom.i.spec.ts, libs/modules/atom-api/src/use-cases/update-atom/update-atom.service.ts
=> test(libs-modules-atom-api): atom crud tests

.circleci/config.yml, apps/gqlgen/src/app/app.service.ts, apps/gqlgen/src/server/server.service.ts, apps/web-e2e/src/plugins/index.js, apps/web-e2e/src/support/commands.ts, makefile
=> fix(ci): make cypress ci

libs/modules/component-element/src/createComponentElement/CreateComponentElementFormBase.tsx, libs/modules/lambda/src/updateLambda/UpdateLambdaModal.tsx, nx.json
=> fix(ci): disable target build for parallel

.terraform/.env.example, .terraform/.terraform.lock.hcl, .terraform/auto_scaling.tf, .terraform/ecs.tf, .terraform/network.tf, .terraform/parameterstore.tf, .terraform/provider.tf, .terraform/templates/ecs/cb_app.json.tpl, .terraform/vars.tf, apps/api/src/main.ts
=> fix(ci): enable ecs breaker 

libs/backend/src/infrastructure/dgraph/config/dgraph.config.ts, libs/backend/src/infrastructure/dgraph/dgraph.provider.ts
=> fix(ci): make integration test pass

libs/modules/prop-api/src/models/prop/prop.model.ts
=> 885 page specs

.circleci/config.yml, apps/web/.babelrc, apps/web/next.config.js, apps/web/src/styles/App.less
=> fix(web): theme with custom values on css compile

.circleci/config.yml
=> fix(ci): mentioning via slack channel

.circleci/config.yml, .env.example, .husky/pre-push, apps/api/src/main.ts, apps/gqlgen/src/app/app.service.ts, apps/gqlgen/src/server/server.service.ts, apps/web-e2e/cypress.json, libs/backend/src/adapters/auth/auth.module.ts, libs/backend/src/infrastructure/apollo-client/apollo-client.module.ts, libs/backend/src/infrastructure/dgraph/dgraph.module.ts, libs/backend/src/infrastructure/graphql-schema/graphql-schema.module.ts, libs/backend/src/infrastructure/graphql-server/graphql-server.module.ts, makefile, package.json, workspace.json
=> ci(apps-gqlgen): add e2e-dev to local

.husky/pre-push, apps/api/src/main.ts, makefile
=> feat(ci): add storybook to husky

.circleci/config.yml, .prettierignore, schema.api.graphql
=> ci: add schema.api.graphql to prettierignore

.circleci/config.yml
=> feat: replace dgraph client access with http endpoint

apps/cli/src/app/app.module.ts, apps/cli/src/dgraph-cli/dgraph-cli.module.ts, apps/cli/src/dgraph-cli/dgraph-cli.service.ts, apps/cli/src/dgraph-cli/index.ts, scripts/cli.ts
=> feat(cli): add dgraph cli

libs/modules/type-api/src/field.resolver.ts, libs/modules/type-api/src/use-cases/field/create-field/helper/create-type-field.ts, libs/modules/type-api/src/use-cases/field/create-field/helper/data.ts, libs/modules/type-api/src/use-cases/field/create-field/test/create-field.i.spec.ts, libs/modules/type-api/src/use-cases/field/delete-field/test/delete-field.i.spec.ts, libs/modules/type-api/src/use-cases/field/get-field/test/get-field.i.spec.ts, libs/modules/type-api/src/use-cases/field/update-field/test/update-field.i.spec.ts, libs/modules/type-api/src/use-cases/type/create-type/test/create-type.data.ts, libs/modules/type-api/src/use-cases/type/create-type/test/create-type.i.spec.ts, libs/modules/type-api/src/use-cases/type/delete-type/test/delete-type.i.spec.ts, libs/modules/type-api/src/use-cases/type/get-type/test/get-type.i.spec.ts, libs/modules/type-api/src/use-cases/type/get-types/test/get-types.i.spec.ts
Closes https://github.com/codelab-ai/codelab.ai/issues/1000
Fixes #
> add mapper in the field resolver
> add field specs
=> 1000 type api specs

.circleci/config.yml
=> feat(apps): use different dgraph in e2e, integration test

libs/frontend/modules/builder/src/renderer/Renderer.tsx, libs/frontend/modules/builder/src/renderer/renderFactory.tsx, libs/frontend/presenter/container/src/providers/RenderContextProvider.tsx, libs/frontend/view/components/mapper/Mapper.tsx, libs/frontend/view/components/propMapper/PropMapper.tsx, libs/frontend/view/components/propMapper/PropMapperBinding.ts
=> Fix menu render issue and PropMapper

libs/backend/modules/element/src/use-cases/component/create-component/tests/create-component.data.ts, libs/backend/modules/element/src/use-cases/component/create-component/tests/create-component.i.spec.ts, libs/backend/modules/element/src/use-cases/component/delete-component/tests/delete-component.i.spec.ts, libs/backend/modules/element/src/use-cases/component/get-component/tests/get-component.api.graphql, libs/backend/modules/element/src/use-cases/component/get-component/tests/get-component.i.spec.ts, libs/backend/modules/element/src/use-cases/component/get-components/tests/get-components.api.graphql, libs/backend/modules/element/src/use-cases/component/get-components/tests/get-components.i.spec.ts, libs/backend/modules/element/src/use-cases/component/update-component/tests/update-component.i.spec.ts
=> 1048 component spec

libs/backend/modules/element/src/use-cases/component/delete-component/tests/delete-component.i.spec.ts
=> test: delete component spec

.circleci/config.yml, libs/shared/abstract/core/src/graph/Vertex.ts~ccf1e7a3 (build: re-add start script for ecs)
=> ci: update to large machine

.circleci/config.yml, libs/shared/abstract/core/src/graph/Vertex.ts~ccf1e7a3 (build: re-add start script for ecs)
=> ci: update to large machine (#1087)

libs/frontend/modules/atom/src/use-cases/export-atoms/ExportAtoms.api.graphql, libs/frontend/modules/atom/src/use-cases/export-atoms/ExportAtoms.api.graphql.gen.ts, libs/frontend/modules/atom/src/use-cases/export-atoms/ExportAtomsButton.tsx, scripts/postinstall.sh
=> fix: atom export

.eslintrc.json, apps/api/src/main.ts, apps/cli/src/main.ts, apps/web-e2e/.eslintrc.json, apps/web-e2e/src/integration/component.spec.ignore.ts, apps/web/.eslintrc.json, libs/backend/modules/admin/src/application/admin.resolver.ts, libs/backend/modules/admin/src/use-cases/reset-data/reset-data.service.ts, libs/backend/modules/atom/src/use-cases/create-atom/create-atom.service.ts, libs/backend/modules/atom/src/use-cases/delete-atom/delete-atom.service.ts, libs/backend/modules/element/src/use-cases/component/delete-component/tests/delete-component.i.spec.ts, libs/backend/modules/type/src/use-cases/field/create-field/tests/create-field.i.spec.ts, libs/backend/modules/type/src/use-cases/field/create-field/tests/create-type-field.ts, libs/backend/modules/type/src/use-cases/field/update-field/tests/update-field.i.spec.ts, libs/backend/modules/user/src/infra/auth0/auth0.controller.ts, libs/backend/shared/generic/src/cytoscape/cytoscape.spec.ts, libs/frontend/modules/builder/src/main-pane/useExpandedNodes.tsx, libs/frontend/modules/builder/src/meta-pane/PropsInspectorTab.tsx, libs/frontend/modules/builder/src/renderer/hooks/handlers/useRecoilStateHook.ts, libs/frontend/modules/lambda/src/use-cases/create-lambda/CreateLambdaForm.tsx, libs/frontend/modules/lambda/src/use-cases/delete-lambda/DeleteLambdaForm.tsx, libs/frontend/modules/lambda/src/use-cases/execute-lambda/ExecuteLambdaButton.tsx, libs/frontend/modules/lambda/src/use-cases/update-lambda/UpdateLambdaForm.tsx, libs/frontend/modules/library/src/librarySelectionState.ts, libs/frontend/presenter/container/src/providers/LibraryProvider.tsx, libs/frontend/view/components/loadingIndicator/loadingIndicatorState.ts, libs/frontend/view/components/state/State.tsx, libs/tools/plugins/codelab/src/migrations/tsconfig-lib/tsconfig-lib.ts, libs/ui/d3/src/cytoscape/CyGraph.tsx, libs/ui/d3/src/cytoscape/Cytoscape.stories.tsx
- added eslint rule to avoid unhandled promises
- fixed various eslint warnings
=> lint: add promise lint rule and fix lint warnings

apps/web-e2e/src/support/graphql/CreateApp.api.graphql, apps/web-e2e/src/support/graphql/CreateApp.api.graphql.gen.ts, apps/web-e2e/src/support/graphql/DeleteApp.api.graphql, apps/web-e2e/src/support/graphql/DeleteApp.api.graphql.gen.ts, libs/backend/modules/app/src/app.module.ts, libs/backend/modules/app/src/application/app.resolver.ts, libs/backend/modules/app/src/use-cases/create-app/create-app.service.ts, libs/backend/modules/app/src/use-cases/create-app/tests/create-app.api.graphql, libs/backend/modules/app/src/use-cases/create-app/tests/create-app.api.graphql.gen.ts, libs/backend/modules/app/src/use-cases/create-app/tests/create-app.i.spec.ts, libs/backend/modules/app/src/use-cases/delete-app/delete-app.service.ts, libs/backend/modules/app/src/use-cases/delete-app/tests/delete-app.api.graphql, libs/backend/modules/app/src/use-cases/delete-app/tests/delete-app.api.graphql.gen.ts, libs/backend/modules/app/src/use-cases/delete-app/tests/delete-app.i.spec.ts, libs/backend/modules/app/src/use-cases/update-app/tests/update-app.api.graphql, libs/backend/modules/app/src/use-cases/update-app/tests/update-app.api.graphql.gen.ts, libs/backend/modules/app/src/use-cases/update-app/tests/update-app.i.spec.ts, libs/backend/modules/app/src/use-cases/update-app/update-app.service.ts, libs/backend/modules/page/src/use-cases/create-page/tests/create-app.api.graphql, libs/backend/modules/page/src/use-cases/create-page/tests/create-app.api.graphql.gen.ts, libs/frontend/modules/app/src/graphql/AppBase.fragment.api.graphql, libs/frontend/modules/app/src/graphql/AppBase.fragment.api.graphql.gen.ts, libs/frontend/modules/app/src/use-cases/create-app/CreateApp.api.graphql, libs/frontend/modules/app/src/use-cases/create-app/CreateApp.api.graphql.gen.ts, libs/frontend/modules/app/src/use-cases/delete-app/DeleteApp.api.graphql, libs/frontend/modules/app/src/use-cases/delete-app/DeleteApp.api.graphql.gen.ts, libs/frontend/modules/app/src/use-cases/update-app/UpdateApp.api.graphql, libs/frontend/modules/app/src/use-cases/update-app/UpdateApp.api.graphql.gen.ts, libs/shared/codegen/graphql/src/types.api.graphql.gen.ts, schema.api.graphql
=> refactor: update dgraph service for app module #1109

libs/backend/modules/type/src/use-cases/type/get-types/tests/get-types.i.spec.ts
=> #1083 update get-types spec

libs/backend/modules/type/src/use-cases/type/get-types/get-types.query.ts, libs/frontend/modules/builder/src/Builder.tsx, libs/frontend/modules/builder/src/renderer/reactComponentFactory.tsx, libs/frontend/view/templates/DashboardTemplate.tsx, libs/tools/scripts/src/lint/git.sh, yarn.lock
fix: antd modal component is not blocking the header, sider and meta section
https://github.com/codelab-ai/codelab.ai/issues/1096
Fixes #
=> 1096 sandbox area builder

libs/frontend/model/infra/apollo/src/apolloClient.ts, libs/frontend/modules/builder/src/renderer/Renderer.tsx, libs/frontend/modules/builder/src/renderer/atomFactory.tsx, libs/frontend/modules/builder/src/renderer/handlers/renderElement.tsx, libs/frontend/modules/builder/src/renderer/hooks/HookElementWrapper.tsx, libs/frontend/modules/builder/src/renderer/reactComponentFactory.tsx, libs/frontend/modules/builder/src/renderer/utils/evalCss.ts, libs/frontend/presenter/container/src/providers/RenderProvider.tsx
https://user-images.githubusercontent.com/57956282/134645693-d5c2fce7-25b0-4c97-989a-8c951242db71.mp4
=> feat: dynamic css and fix render bug

libs/backend/modules/atom/src/application/atom.resolver.ts, libs/backend/modules/atom/src/use-cases/create-atom/tests/create-atom.api.graphql, libs/backend/modules/atom/src/use-cases/create-atom/tests/create-atom.api.graphql.gen.ts, libs/backend/modules/atom/src/use-cases/create-atom/tests/create-atom.i.spec.ts, libs/backend/modules/atom/src/use-cases/delete-atom/tests/delete-atom.api.graphql, libs/backend/modules/atom/src/use-cases/delete-atom/tests/delete-atom.api.graphql.gen.ts, libs/backend/modules/atom/src/use-cases/update-atom/tests/update-atom.api.graphql, libs/backend/modules/atom/src/use-cases/update-atom/tests/update-atom.api.graphql.gen.ts, libs/backend/modules/atom/src/use-cases/update-atom/tests/update-atom.i.spec.ts, libs/frontend/modules/atom/src/Atom.fragment.graphql, libs/frontend/modules/atom/src/Atom.fragment.graphql.gen.ts, libs/frontend/modules/atom/src/use-cases/delete-atom/DeleteAtoms.web.graphql, libs/frontend/modules/atom/src/use-cases/delete-atom/DeleteAtoms.web.graphql.gen.ts, libs/frontend/modules/atom/src/use-cases/update-atom/UpdateAtom.web.graphql, libs/frontend/modules/atom/src/use-cases/update-atom/UpdateAtom.web.graphql.gen.ts, libs/shared/codegen/graphql/src/types.api.graphql.gen.ts, schema.api.graphql
=> refactor: update dgraph service for atom module

libs/backend/modules/type/src/use-cases/type/update-enum-type/tests/update-enum-type.api.graphql, libs/backend/modules/type/src/use-cases/type/update-enum-type/tests/update-enum-type.api.graphql.gen.ts, libs/backend/modules/type/src/use-cases/type/update-enum-type/tests/update-enum-type.data.ts, libs/backend/modules/type/src/use-cases/type/update-enum-type/tests/update-enum-type.i.spec.ts, libs/backend/modules/type/src/use-cases/type/update-enum-type/update-enum-type.service.ts
=> fix: #1114 enum update

libs/backend/modules/app/src/application/app.resolver.ts, libs/backend/modules/app/src/use-cases/delete-app/delete-app.service.ts, libs/backend/modules/app/src/use-cases/delete-app/tests/delete-app.i.spec.ts, libs/backend/modules/app/src/use-cases/update-app/update-app.service.ts
=> refactor: refactoring dgraph service app module

libs/backend/modules/page/src/application/page.resolver.ts, libs/backend/modules/page/src/use-cases/delete-page/delete-page.service.ts, libs/backend/modules/page/src/use-cases/delete-page/tests/delete-page.i.spec.ts, libs/backend/modules/page/src/use-cases/update-page/tests/update-page.api.graphql, libs/backend/modules/page/src/use-cases/update-page/tests/update-page.api.graphql.gen.ts, libs/backend/modules/page/src/use-cases/update-page/tests/update-page.i.spec.ts, libs/frontend/modules/page/src/use-cases/page/update-page/UpdatePage.web.graphql, libs/frontend/modules/page/src/use-cases/page/update-page/UpdatePage.web.graphql.gen.ts, libs/shared/codegen/graphql/src/types.api.graphql.gen.ts, schema.api.graphql
=>  refactor: refactoring dgraph service page module

.circleci/config.yml, .env.example, apps/web/pages/api/graphql.ts, makefile
=> refactor: update CircleCI env var to use Dgraph cloud

libs/frontend/modules/builder/src/meta-pane/MetaPaneBuilder.tsx, libs/frontend/modules/builder/src/meta-pane/MetaPaneBuilderComponent.tsx, libs/frontend/modules/builder/src/meta-pane/MetaPaneBuilderPage.tsx, libs/frontend/modules/element/src/css-editor/ElementCssEditor.tsx, libs/frontend/modules/element/src/use-cases/element/move-element/MoveElementForm.tsx, libs/frontend/modules/element/src/use-cases/element/update-element-prop-transformation/UpdateElementPropTransformationForm.tsx, libs/frontend/modules/element/src/use-cases/element/update-element-props/UpdateElementPropsForm.tsx, libs/frontend/modules/element/src/use-cases/element/update-element/UpdateElementForm.tsx, libs/frontend/view/components/loadingIndicator/LoadingIndicator.tsx, libs/frontend/view/components/loadingIndicator/index.ts, libs/frontend/view/components/loadingIndicator/useTrackLoadingPromises.ts
=> fix: remove recoil from loading state

libs/frontend/modules/app/src/use-cases/create-app/createAppSchema.ts, libs/frontend/modules/app/src/use-cases/update-app/updateAppSchema.ts, libs/frontend/modules/atom/src/use-cases/create-atom/createAtomSchema.ts, libs/frontend/modules/element/src/use-cases/component/create-component/createComponentSchema.ts, libs/frontend/modules/element/src/use-cases/element/create-element/createElementSchema.ts, libs/frontend/modules/element/src/use-cases/element/update-element/updateElementSchema.ts, libs/frontend/modules/element/src/use-cases/hooks/add-hook-to-element/addHookToElementSchema.ts, libs/frontend/modules/element/src/use-cases/prop-mapping/create-prop-map-binding/createPropMapBindingSchema.ts, libs/frontend/modules/element/src/use-cases/prop-mapping/update-prop-map-binding/updatePropMapBindingSchema.ts, libs/frontend/modules/lambda/src/use-cases/create-lambda/createLambdaSchema.ts, libs/frontend/modules/lambda/src/use-cases/update-lambda/updateLambdaSchema.ts, libs/frontend/modules/library/src/use-cases/create-library/createLibrarySchema.ts, libs/frontend/modules/library/src/use-cases/update-library/updateLibrarySchema.ts, libs/frontend/modules/page/src/use-cases/create-page/createPageSchema.ts, libs/frontend/modules/page/src/use-cases/update-page/updatePageSchema.ts, libs/frontend/modules/tag/src/use-cases/create-tag/CreateTagSchema.ts, libs/frontend/modules/tag/src/use-cases/delete-tags/deleteTagsSchema.ts, libs/frontend/modules/tag/src/use-cases/update-tag/updateTagSchema.ts, libs/frontend/modules/type/src/shared/mapTypeSchemaToTypeInput.ts, libs/frontend/modules/type/src/use-cases/fields/create-field/createFieldSchema.ts, libs/frontend/modules/user/src/ownerSchema.ts
Form Inputs are not auto focused nor in the modal forms nor in the other type of forms  
Auto focus the first input of each form input
https://github.com/codelab-ai/codelab.ai/issues/1121
Fixes #
=> feat: auto-focus-form-inputs

libs/backend/abstract/codegen/src/nestjs-types.api.graphql.gen.ts, libs/backend/modules/app/src/use-cases/export-app/export-app.service.ts, libs/backend/modules/app/src/use-cases/export-app/test/export-app.i.spec.ts, libs/backend/modules/app/src/use-cases/import-app/import-app.service.ts, libs/backend/modules/page/src/use-cases/update-page/update-page.input.ts, libs/backend/modules/page/src/use-cases/update-page/update-page.service.ts, libs/shared/abstract/core/src/app/export/export-app.schema.ts, schema.api.graphql
=> 1206 exported hook page ref

package.json, yarn.lock
=> test: upgrade to cypress 9.1.1

README.md
=> fix: update readme vercel settings

.circleci/config.yml, .env.example, apps/web-e2e/src/plugins/index.ts, apps/web/pages/api/graphql.ts, libs/backend/infra/src/modules/dgraph/config/dgraph.config.ts
=> 0 env rename

.circleci/config.yml, .docker/startup.sh, .env.example, apps/cli/src/main.ts, apps/web-e2e/src/plugins/index.ts, apps/web/pages/api/graphql.ts, apps/web/pages/apps/[appId]/pages/[pageId]/builder.tsx, libs/backend/infra/src/modules/dgraph/config/dgraph.config.ts, libs/frontend/view/templates/Dashboard/DashboardTemplateMetaPane.tsx
=> 0 template refactor

.circleci/config.yml, .husky/pre-push, libs/backend/abstract/core/src/application/errors/bad-request-error.ts, libs/backend/abstract/core/src/application/errors/error-code.ts, libs/backend/abstract/core/src/application/errors/index.ts, libs/backend/modules/lambda/project.json, libs/backend/modules/lambda/src/application/lambda.error.ts, libs/backend/modules/lambda/src/application/lambda.service.ts, libs/backend/modules/lambda/src/use-cases/create-lambda/tests/create-lambda.i.spec.ts, libs/backend/modules/lambda/src/use-cases/delete-lambda/tests/delete-lambda.i.spec.ts, libs/backend/modules/lambda/src/use-cases/execute-lambda/tests/execute-lambda.i.spec.ts, libs/backend/modules/lambda/src/use-cases/get-lambda/tests/get-lambda.i.spec.ts, libs/backend/modules/lambda/src/use-cases/get-lambdas/tests/get-lambdas.i.spec.ts, libs/backend/modules/lambda/src/use-cases/update-lambda/tests/update-lambda.i.spec.ts, libs/backend/shared/testing/src/request.ts
CLOSES: #1274
- All backend lambda module's specs are disabled
- Enable them
- Fix any issues
- Throw error in mutation `updateLambda` if lamda is pending
- Update spec to wait until lambda is active to update
Fixes #1274
=> fix(libs-backend-modules-lambda): #1254 fix lambda specs

libs/frontend/modules/builder/src/sections/main-pane/tabs/MainPaneBuilderTreeTab.tsx, libs/frontend/modules/tag/src/use-cases/create-tag/CreateTagModal.tsx, libs/frontend/modules/tag/src/use-cases/delete-tags/DeleteTagsModal.tsx, libs/frontend/modules/tag/src/use-cases/delete-tags/useDeleteTagsForm.ts, libs/frontend/modules/tag/src/use-cases/get-tags/GetTagsTree.tsx, libs/shared/core/src/tree/tree.service.ts
https://user-images.githubusercontent.com/1405854/150472367-5726306b-c50f-432d-b23b-83c5ad820023.mp4
[#1286 ](https://github.com/codelab-ai/web/issues/1286)
Fixes #
- update tag tree
- fix delete tags modal
- fix check state of tag tree
=> fix: #1288 crud for tag tree

libs/backend/abstract/codegen/src/nestjs-types.api.graphql.gen.ts, libs/frontend/modules/builder/src/sections/main-pane/tabs/MainPaneBuilderTreeTab.tsx, libs/frontend/modules/element/src/providers/ElementGraphProvider.tsx, libs/frontend/modules/element/src/use-cases/element/create-element/CreateElementModal.tsx, libs/frontend/modules/tag/src/use-cases/get-tags/GetTagsTree.tsx, libs/shared/core/src/tree/tree.service.ts, schema.api.graphql
- CreateElementModal not opened in page builder [Issue video link](https://www.loom.com/share/530c0272d0ab402aaeba5fd68d25e837)
- Element Tree not showing in page builder [issue details](https://github.com/codelab-ai/web/issues/1298#issuecomment-1019531702)
Resolved above 2 issues.
https://user-images.githubusercontent.com/34818311/150996090-c1875d65-458e-4e31-8e0b-510560ad4cc4.mp4
Fixes #1312
=> Fix: builder issues

.circleci/config.yml, apps/cli/src/main.ts, apps/cli/src/utils/run-tasks.ts, apps/web-e2e/src/integration/builder-props.spec.ts, apps/web-e2e/src/integration/builder.spec.ts, libs/backend/abstract/codegen/src/nestjs-types.api.graphql.gen.ts, libs/backend/modules/atom/src/infastructure/repositories/atom.repository.ts, libs/backend/modules/atom/src/use-cases/upsert-atoms/upsert-atoms.service.ts
Enabled e2e testing for builder
Fixes #1359
=> 1359 enable e2e specs for builder

.docker/docker-compose.yaml, apps/web/src/neo4j-graphql/type-defs/pageSchema.ts, apps/web/src/neo4j-graphql/typeDefs.ts, libs/frontend/modules/app/src/graphql/App.endpoints.v2.graphql, libs/frontend/modules/app/src/graphql/App.endpoints.v2.graphql.gen.ts, libs/frontend/modules/app/src/graphql/App.fragment.v2.graphql, libs/frontend/modules/app/src/graphql/App.fragment.v2.graphql.gen.ts, libs/frontend/modules/app/src/provider/types.ts, libs/frontend/modules/app/src/provider/useProvideCurrentApp.ts, libs/frontend/modules/app/src/store/types.ts, libs/frontend/modules/page/src/graphql/Page.endpoints.v2.graphql, libs/frontend/modules/page/src/graphql/Page.endpoints.v2.graphql.gen.ts, libs/frontend/modules/page/src/graphql/Page.fragment.v2.graphql, libs/frontend/modules/page/src/graphql/Page.fragment.v2.graphql.gen.ts, libs/frontend/modules/page/src/graphql/index.ts, libs/frontend/modules/page/src/providers/types.ts, libs/frontend/modules/page/src/providers/useProvideCurrentPage.ts, libs/frontend/modules/page/src/sections/PageDetailHeader.tsx, libs/frontend/modules/page/src/store/index.ts, libs/frontend/modules/page/src/store/pageEndpoints.v2.ts, libs/frontend/modules/page/src/store/types.ts, libs/frontend/modules/page/src/use-cases/create-page/types.ts, libs/frontend/modules/page/src/use-cases/create-page/useCreatePageForm.ts, libs/frontend/modules/page/src/use-cases/delete-page/types.ts, libs/frontend/modules/page/src/use-cases/delete-page/useDeletePageForm.ts, libs/frontend/modules/page/src/use-cases/update-page/types.ts, libs/frontend/modules/page/src/use-cases/update-page/useUpdatePageForm.ts, libs/shared/abstract/codegen-v2/src/types.api.v2.graphql.gen.ts, libs/shared/abstract/codegen/src/types.api.graphql.gen.ts, schema.api.v2.graphql
=> refactor: page module to neo4j

.env.example, apps/api/project.json, apps/web/pages/api/v2/graphql.ts, apps/web/src/neo4j-graphql/getSchema.ts, apps/web/src/neo4j-graphql/resolvers.ts, apps/web/src/neo4j-graphql/type-defs/atomSchema.ts, apps/web/src/neo4j-graphql/typeDefs.ts, codegen.v2.yml, codegen.yml, libs/frontend/modules/atom/src/graphql/Atom.endpoints.v2.graphql, libs/frontend/modules/atom/src/graphql/Atom.endpoints.v2.graphql.gen.ts, libs/frontend/modules/atom/src/use-cases/export-atoms/ExportAtomsButton.tsx, libs/frontend/modules/atom/src/use-cases/import-atoms/ImportAtomsUpload.tsx, libs/shared/abstract/codegen-v2/src/types.api.v2.graphql.gen.ts, schema.api.v2.graphql
=> wip: custom resolver

apps/web/pages/components/index.tsx, apps/web/pages/tags/index.tsx, apps/web/src/neo4j-graphql/type-defs/tagSchema.ts, apps/web/src/neo4j-graphql/typeDefs.ts, libs/frontend/modules/tag/src/graphql/Tag.fragment.v2.graphql, libs/frontend/modules/tag/src/graphql/Tag.fragment.v2.graphql.gen.ts, libs/frontend/modules/tag/src/graphql/TagEdge.fragment.v2.graphql, libs/frontend/modules/tag/src/graphql/TagEdge.fragment.v2.graphql.gen.ts, libs/frontend/modules/tag/src/graphql/TagGraph.fragment.v2.graphql, libs/frontend/modules/tag/src/graphql/TagGraph.fragment.v2.graphql.gen.ts, libs/frontend/modules/tag/src/graphql/tag.endpoints.v2.graphql, libs/frontend/modules/tag/src/graphql/tag.endpoints.v2.graphql.gen.ts, libs/frontend/modules/tag/src/hooks/useTagTree.ts, libs/frontend/modules/tag/src/store/index.ts, libs/frontend/modules/tag/src/store/tagEndpoints.ts, libs/frontend/modules/tag/src/store/tagEndpoints.v2.ts, libs/frontend/modules/tag/src/use-cases/create-tag/CreateTagModal.tsx, libs/frontend/modules/tag/src/use-cases/create-tag/types.ts, libs/frontend/modules/tag/src/use-cases/create-tag/useCreateTagForm.ts, libs/frontend/modules/tag/src/use-cases/delete-tags/DeleteTagsModal.tsx, libs/frontend/modules/tag/src/use-cases/delete-tags/useDeleteTagsForm.ts, libs/frontend/modules/tag/src/use-cases/export-tags/ExportTagsButton.tsx, libs/frontend/modules/tag/src/use-cases/get-tags/GetTagsTree.tsx, libs/frontend/modules/tag/src/use-cases/import-tags/ImportTagsUpload.tsx, libs/frontend/modules/tag/src/use-cases/update-tag/UpdateTagModal.tsx, libs/frontend/modules/tag/src/use-cases/update-tag/index.ts, libs/frontend/modules/tag/src/use-cases/update-tag/useUpdateTagForm.ts, libs/shared/abstract/codegen-v2/src/types.api.v2.graphql.gen.ts, schema.api.v2.graphql
nest & dgraph
migrate tag to neo4j
- fetching gettreetag from neo4j
- creatting tag to neo4j
- deleting tag from neo4j
https://user-images.githubusercontent.com/1405854/153368070-560a1c6c-e5d5-4b37-b706-137f23ac3787.mp4
Fixes #1406
=> refactor(tags): migrate tag to neo4j

apps/web/src/graphql/schema/atom.schema.ts, libs/frontend/modules/atom/src/graphql/Atom.fragment.v2.graphql, libs/frontend/modules/atom/src/graphql/Atom.fragment.v2.graphql.gen.ts, libs/frontend/modules/atom/src/store/types.ts, libs/frontend/modules/atom/src/use-cases/components/index.ts, libs/frontend/modules/atom/src/use-cases/components/tree-select-field/index.ts, libs/frontend/modules/atom/src/use-cases/components/tree-select-field/tree-select-field.tsx, libs/frontend/modules/atom/src/use-cases/create-atom/CreateAtomModal.tsx, libs/frontend/modules/atom/src/use-cases/create-atom/createAtomSchema.ts, libs/frontend/modules/atom/src/use-cases/create-atom/useCreateAtomForm.ts, libs/frontend/modules/atom/src/use-cases/export-atoms/ExportAtomsButton.tsx, libs/frontend/modules/atom/src/use-cases/get-atoms/columns/TagsColumn.tsx, libs/frontend/modules/atom/src/use-cases/get-atoms/columns/index.ts, libs/frontend/modules/atom/src/use-cases/get-atoms/columns/types.ts, libs/frontend/modules/atom/src/use-cases/get-atoms/useAtomTable.tsx, libs/frontend/modules/atom/src/use-cases/update-atom/UpdateAtomModal.tsx, libs/frontend/modules/atom/src/use-cases/update-atom/useUpdateAtomForm.ts, libs/shared/abstract/codegen-v2/src/types.api.v2.graphql.gen.ts, schema.api.v2.graphql
=> refactor: assign tags to atom ui

libs/frontend/modules/builder/src/renderer/pipes/componentPipe.spec.ts, libs/frontend/modules/builder/src/renderer/pipes/reactNodePipe.spec.ts, libs/frontend/modules/builder/src/renderer/pipes/renderPropsPipe.spec.ts, libs/frontend/modules/builder/src/renderer/pipes/test/renderData.ts, libs/frontend/modules/builder/src/renderer/utils/transformPropsToComponentFn.spec.ts
=> fix: builder unit specs

apps/web-e2e/src/data/import-data.json, apps/web-e2e/src/integration/admin.spec.ts, apps/web-e2e/src/support/database/admin.ts, apps/web-e2e/src/support/database/graphql/admin.api.v2.1.graphql, apps/web-e2e/src/support/database/graphql/admin.api.v2.1.graphql.gen.ts, apps/web-e2e/src/support/database/index.ts
=> feat: integration test for admin import/export

apps/web/pages/admin/index.tsx, libs/frontend/model/infra/mobx/src/store.ts, libs/frontend/modules/admin/src/graphql/Admin.endpoints.v2.graphql.gen.ts, libs/frontend/modules/admin/src/store/admin.api.ts, libs/frontend/modules/admin/src/store/admin.service.ts, libs/frontend/modules/admin/src/store/adminEndpoints.ts, libs/frontend/modules/admin/src/store/index.ts, libs/frontend/modules/admin/src/use-cases/export/ExportButton.tsx, libs/frontend/modules/admin/src/use-cases/import/ImportButton.tsx, libs/frontend/modules/admin/src/use-cases/reset-data/ResetDataButton.tsx, libs/frontend/view/components/upload/ImportUpload.tsx
=> 1513 migrate admin to mobx

apps/web/pages/atoms/index.tsx, libs/frontend/modules/atom/src/store/atom.model.ts, libs/frontend/modules/atom/src/store/atom.service.ts, libs/frontend/modules/atom/src/use-cases/create-atom/CreateAtomModal.tsx, libs/frontend/modules/atom/src/use-cases/create-atom/createAtomSchema.ts, libs/frontend/modules/atom/src/use-cases/get-atoms/GetAtomsTable.tsx, libs/frontend/modules/atom/src/use-cases/get-atoms/columns/types.ts, libs/frontend/modules/atom/src/use-cases/get-atoms/useAtomTable.tsx, libs/frontend/modules/atom/src/use-cases/update-atom/UpdateAtomModal.tsx
=> 1531 connect tag to atom

apps/web/pages/apps/[appId]/pages/[pageId]/builder.tsx, apps/web/pages/apps/[appId]/pages/[pageId]/index.tsx, libs/frontend/modules/builder/src/renderer/index.ts, libs/frontend/modules/builder/src/renderer/utils/index.ts, libs/frontend/modules/builder/src/renderer/utils/platformState.ts, libs/frontend/modules/builder/src/sections/main-pane/MainPane.tsx, libs/frontend/modules/builder/src/sections/main-pane/builder-tree/BuilderTree.tsx, libs/frontend/modules/builder/src/sections/main-pane/builder-tree/BuilderTreeItemOverlay.tsx, libs/frontend/modules/builder/src/sections/main-pane/builder-tree/BuilderTreeItemTitle.tsx, libs/frontend/modules/builder/src/sections/main-pane/builder-tree/index.ts, libs/frontend/modules/builder/src/sections/main-pane/mobx-state/MobxState.tsx, libs/frontend/modules/builder/src/sections/main-pane/mobx-state/MobxStateModal.tsx, libs/frontend/modules/builder/src/sections/main-pane/mobx-state/MobxStateTree.tsx, libs/frontend/modules/builder/src/sections/main-pane/mobx-state/MobxStateTreeItem.tsx, libs/frontend/modules/builder/src/sections/main-pane/toolbox/Toolbox.tsx, libs/frontend/modules/store/src/store/store.model.ts, libs/shared/abstract/core/src/domain/page/page.fragment.graphql, libs/shared/abstract/core/src/domain/page/page.fragment.graphql.gen.ts
=> feat: add router apps and pages to mobx state

apps/web-e2e/src/data/import-data.json, data/import-test.json, data/mui-atoms-v2.json, libs/frontend/model/infra/mobx/src/store.ts, libs/frontend/modules/atom/src/store/import-atom.service.ts, libs/frontend/modules/builder/src/renderer/test/typedValueTranformers.spec.ts, libs/frontend/modules/type/src/store/import-type.service.ts
=> fix: import feature

libs/frontend/modules/builder/.babelrc, libs/frontend/modules/builder/src/renderer/element/ElementWrapper.ts, libs/frontend/modules/builder/src/renderer/utils/reduceComponentTree.tsx, libs/frontend/modules/element/src/store/element-tree.model.ts, libs/frontend/modules/element/src/store/element.model.ts, libs/frontend/modules/element/src/store/element.service.ts, libs/frontend/modules/type/src/props-form/codemirror-extensions.ts, libs/frontend/modules/type/src/store/type.service.ts
=> fix: some builder bugs 

libs/frontend/modules/element/src/css-editor/ElementCssEditor.tsx, libs/frontend/modules/type/src/props-form/form-controls/CodeMirror/CodeMirrorField.tsx, libs/frontend/modules/type/src/props-form/form-controls/index.ts, libs/frontend/view/components/editors/CodeMirror/CodeMirrorInput.tsx, libs/frontend/view/components/editors/CodeMirror/codemirror-extensions.ts, libs/frontend/view/components/editors/CodeMirror/index.ts, libs/frontend/view/components/editors/CodeMirror/types.ts, libs/frontend/view/components/editors/cssEditor/EmotionCssEditor.tsx, libs/frontend/view/components/index.ts, package.json, yarn.lock
https://user-images.githubusercontent.com/36730355/171337069-0c6c0f38-3c1a-476a-94d4-671324776a7e.mp4
Fixes #1582
=> feat(apps): #1582 integrate code mirror css

.circleci/config.yml, apps/web-e2e/src/integration/apps/css.spec.required.ts, libs/frontend/modules/type/src/props-form/form-controls/CodeMirror/CodeMirrorField.tsx, libs/frontend/view/components/editors/CodeMirror/CodeMirrorInput.tsx, libs/frontend/view/components/editors/CodeMirror/CodeMirrorModal.tsx, libs/frontend/view/components/editors/CodeMirror/styles.ts, libs/frontend/view/components/editors/CodeMirror/types.ts, libs/frontend/view/components/editors/cssEditor/EmotionCssEditor.tsx
=> feat(apps): #1613 integrate code mirror modal field

libs/backend/src/repositories/component/getDescendantComponentIds.cypher, libs/backend/src/repositories/component/index.ts, libs/backend/src/schema/component.schema.ts, libs/frontend/modules/builder/src/sections/config-pane/ConfigPane.tsx, libs/frontend/modules/element/src/use-cases/element/create-element/CreateElementModal.tsx, libs/frontend/modules/element/src/use-cases/element/update-element/UpdateElementForm.tsx, libs/frontend/modules/type/src/graphql/interface-form.endpoints.graphql, libs/frontend/modules/type/src/graphql/interface-form.endpoints.graphql.gen.ts, libs/frontend/modules/type/src/interface-form/fields/select-component/SelectComponent.tsx, libs/shared/abstract/codegen/src/ogm-types.gen.ts, libs/shared/abstract/codegen/src/types.api.graphql.gen.ts, schema.api.graphql
=> Component circular referance (UI solution)

libs/frontend/modules/builder/src/sections/explorer-pane/ElementContextMenu.tsx, libs/frontend/modules/builder/src/sections/explorer-pane/builder-tree/BuilderTree.tsx, libs/frontend/modules/component/src/store/component.service.ts, libs/frontend/modules/element/src/store/element.service.ts, libs/shared/abstract/core/src/domain/element/element.service.interface.ts
When converting an element to a component, the new component doesn't show up and throws an error
when clicked on, Fixed after refresh.
https://user-images.githubusercontent.com/51242349/178095873-7331183b-0aa7-49a5-9315-97bd52fbb36d.mp4
related #1630
=> Convert element to component issue

apps/cli/src/commands/export/export.command.ts, apps/cli/src/commands/import/import.command.ts
=> fix: cli not showing import and export commands

libs/frontend/modules/element/src/css-editor/components/InputNumberWithUnits.tsx, libs/frontend/modules/element/src/css-editor/css-layout-editor/PositionEditor.tsx
=> Fix zIndex in css editor

apps/web/pages/_app.tsx, libs/frontend/model/infra/mobx/src/create-root-store.ts, libs/frontend/model/infra/mobx/src/initalize-store.ts, libs/shared/abstract/core/src/service/root-store.interface.ts, libs/shared/abstract/core/src/ui/nextjs.interface.ts
Fix no user data available on first login
https://user-images.githubusercontent.com/36730355/181163311-2a223172-d0f9-48ec-b055-bb72c6532e09.mp4
#1678 
Fixes #1678
=> fix(apps): #1678 no user data on first time login

libs/frontend/modules/renderer/src/Renderer.tsx, libs/frontend/modules/renderer/src/atoms/antdAtoms/antdPropsCustomizer.ts, libs/frontend/modules/renderer/src/atoms/atoms.ts, libs/frontend/modules/renderer/src/atoms/muiAtoms/index.ts, libs/frontend/modules/renderer/src/atoms/muiAtoms/muiPropsCustomizer.ts
This PR applies the second solution discussed in #1662 (css + dealing with individual cases).
Fixes #1662
=> fix drawers/modals

libs/frontend/modules/builder/src/sections/content/Builder.tsx, libs/frontend/modules/builder/src/sections/content/BuilderTabs.tsx, libs/frontend/view/templates/Dashboard/DashboardTemplate.tsx
How it looks like after the change:
https://user-images.githubusercontent.com/51242349/182795700-828754e7-c19e-461d-9e6e-600613803c02.mp4
Fixes #1685
=> Confine builder overflow inside the builder component

apps/builder/pages/_sites/user/[user]/[app]/[page]/index.tsx, apps/builder/pages/apps/[appId]/pages/[pageId]/index.tsx, apps/builder/pages/apps/[appId]/provider.tsx, libs/frontend/modules/builder/src/sections/content/Builder-Component.tsx, libs/frontend/modules/builder/src/sections/content/BuilderTabs.tsx, libs/frontend/modules/renderer/src/render.service.ts, libs/shared/abstract/core/src/domain/builder/render.service.interface.ts
=> fix: restore provider page

apps/builder/pages/_middleware.ts, apps/builder/src/middleware/redirectExternalDomain.ts
=> fix: refactor redirect middleware

libs/frontend/modules/builder/src/sections/config-pane/PropsInspectorTab.tsx, libs/frontend/modules/element/src/store/element.service.ts, libs/frontend/view/components/editors/CodeMirror/CodeMirrorInput.tsx, libs/frontend/view/components/editors/CodeMirror/styles.ts, package.json, yarn.lock
=> fix: move element error

libs/frontend/abstract/types/src/pageType.ts, libs/frontend/modules/resource/src/use-cases/delete-resource/DeleteResourceModal.tsx, libs/frontend/view/sections/Menu/commonMenuItems.tsx
=> Resources page resets the state

libs/frontend/platform/atoms/src/custom/text/Text.tsx
=> Fix styles for text atoms

libs/frontend/modules/builder/src/hooks/usePropsInspector.ts, libs/frontend/modules/builder/src/sections/config-pane/PropsInspectorTab.tsx, libs/frontend/modules/store/src/store/models/store.model.ts, libs/frontend/modules/store/src/store/platformState.ts, libs/frontend/modules/store/src/use-cases/actions/get-actions/GetActionItem.tsx, libs/frontend/modules/store/src/use-cases/state/get-state/GetStateItem.tsx, libs/frontend/modules/store/src/view/StoreExplorerPane.tsx, libs/frontend/modules/type/src/props-form/PropsFields.tsx, libs/frontend/modules/type/src/props-form/form-controls/CodeMirror/CodeMirrorField.tsx, libs/frontend/modules/type/src/props-form/form-controls/Field.tsx, libs/frontend/modules/type/src/props-form/form-controls/SelectComponentField.tsx, libs/frontend/view/components/editors/CodeMirror/CodeMirrorInput.tsx, libs/frontend/view/components/editors/CodeMirror/CodeMirrorModal.tsx, libs/frontend/view/components/editors/CodeMirror/codemirror-extensions.ts, libs/frontend/view/components/editors/CodeMirror/types.ts
- Improve Store page UI
- Add `onSave` to `CodeMirrorModal` . used by Props inspector so we don't have to click two save buttons for save 
Fixes #1728
=> feat: nested objects autocompletion

libs/frontend/modules/builder/src/sections/explorer-pane/BuilderExplorerPane.tsx, libs/frontend/modules/element/src/use-cases/element/delete-element/DeleteElementModal.tsx
Select parent after element deletion is successful.
Fixes #1587
=> Delete element refactor

libs/frontend/modules/type/src/props-form/form-controls/ArrayField.tsx, libs/frontend/modules/type/src/props-form/form-controls/Field.tsx, libs/frontend/modules/type/src/props-form/form-controls/SelectEnumField.tsx, libs/shared/abstract/core/src/domain/type/field/field.interface.ts
=> Enum type dropdown

apps/builder/pages/atoms/index.tsx, libs/frontend/modules/atom/src/use-cases/get-atoms/GetAtomsTable.tsx, libs/frontend/modules/atom/src/use-cases/get-atoms/columns/LibraryColumn.tsx, libs/frontend/modules/atom/src/use-cases/get-atoms/columns/types.ts, libs/frontend/modules/renderer/src/atoms/atoms.ts
=> Correct library names in atoms table

apps/cli/src/repository/admin.repo.ts, libs/shared/abstract/codegen/src/types.api.graphql.gen.ts, schema.api.graphql
=> fix: cli reset

libs/frontend/modules/type/src/use-cases/types/create-type/CreateTypeModal.tsx, libs/frontend/modules/type/src/use-cases/types/update-type/UpdateTypeModal.tsx
=> fix: create update union type modal

.circleci/config.yml, apps/cli/src/commands/tasks/tasks.command.ts, libs/frontend/modules/element/src/use-cases/element/update-element-props/UpdateElementPropsForm.tsx
=> fix: cannot see/edit props in UpdateElementPropsForm

apps/builder-e2e/src/e2e/component.cy.ts, apps/builder/pages/apps/[appId]/pages/[pageId]/builder.tsx, libs/frontend/modules/builder/src/hooks/useBuilderRootClickHandler.ts, libs/frontend/modules/builder/src/sections/content/Builder.tsx, libs/frontend/modules/builder/src/sections/explorer-pane/BuilderExplorerPane.tsx, libs/frontend/modules/builder/src/sections/explorer-pane/ElementContextMenu.tsx, libs/frontend/modules/builder/src/sections/explorer-pane/builder-tree/BuilderTree.tsx, libs/frontend/modules/builder/src/store/builder.service.ts, libs/frontend/modules/element/src/use-cases/element/delete-element/DeleteElementModal.tsx, libs/shared/abstract/core/src/domain/builder/builder.service.interface.ts
- for component tree
- for page element tree
**Fix bug**
https://user-images.githubusercontent.com/36730355/190980502-39839c43-51d9-4583-80b5-9cb5bc0e261c.mp4
#1698
=> refactor: separate expandedElementIds

apps/builder/pages/apps/[appId]/pages/[pageId]/builder.tsx, apps/cli/src/commands/tasks/tasks.command.ts, apps/cli/src/repository/tag.repo.ts, libs/frontend/modules/builder/src/dnd/BuilderContext.tsx, libs/frontend/modules/builder/src/dnd/BuilderDropHandler.tsx, libs/frontend/modules/builder/src/dnd/useBuilderDnd.ts, libs/frontend/modules/builder/src/dnd/utils.ts, libs/frontend/modules/builder/src/sections/config-pane/ConfigPane-ComponentTabContainer/GetComponentItem.tsx
=> 1698 integrate drag and drop component picker

libs/frontend/domain/type/src/use-cases/fields/create-field/CreateFieldModal.tsx, libs/frontend/domain/type/src/use-cases/fields/update-field/UpdateFieldModal.tsx
=> field validation refactor

.circleci/config.yml
=> ci: add landing to build step

.circleci/config.yml, .env.example, .gitignore, .vscode/.gitignore, .yarn/.gitignore, terraform/.gitignore, terraform/.terraform.lock.hcl, terraform/README.md, terraform/auth0.tf, terraform/init.sh, terraform/main.tf, terraform/modules/auth0/action_assign_default_role.tf, terraform/modules/auth0/action_assign_jwt_claims.tf, terraform/modules/auth0/action_flow_bindings.tf, terraform/modules/auth0/client_machine.tf, terraform/modules/auth0/client_web.tf, terraform/modules/auth0/output.tf, terraform/modules/auth0/providers.tf, terraform/modules/auth0/roles.tf, terraform/modules/auth0/users.tf, terraform/modules/auth0/vars.tf, terraform/variables.tf
ci: migrate auth0 to current repo
ci: migrate auth0 to current repo
Fixes #
=> ci: migrate auth0 to current repo

.circleci/config.yml, apps/builder-e2e/src/e2e/types.cy.ts, apps/cli/src/commands/tasks/tasks.command.ts, libs/backend/abstract/codegen/src/ogm-types.gen.ts, libs/backend/application/src/repositories/type/field/field.repo.ts, libs/backend/infra/adapter/neo4j/src/schema/type/type.schema.ts, libs/frontend/abstract/core/src/domain/type/fragments/field.fragment.graphql.gen.ts, libs/frontend/abstract/core/src/domain/type/types/interface-type/interface-type.interface.ts, libs/frontend/domain/builder/src/sections/config-pane/ConfigPane-InspectorTabContainer/ConfigPane-InspectorTabContainer.tsx, libs/frontend/domain/builder/src/sections/config-pane/ConfigPane-InspectorTabContainer/ConfigPane-InspectorTabContainerStyle.tsx, libs/frontend/domain/builder/src/sections/config-pane/ConfigPane-InspectorTabContainer/data.ts, libs/frontend/domain/builder/src/sections/config-pane/ConfigPane.tsx, libs/frontend/domain/builder/src/store/builder.service.ts, libs/frontend/domain/renderer/src/test/setup/setupTest.ts, libs/frontend/domain/type/src/store/models/any-type.interface.ts, libs/frontend/domain/type/src/store/models/interface-type.model.ts, libs/frontend/domain/type/src/store/tests/typeTreeToJsonSchema.spec.ts, libs/frontend/domain/type/src/store/type.service.ts, libs/shared/abstract/codegen/src/types.api.graphql.gen.ts, schema.api.graphql
=> fix: regression bug interface fields not showing

libs/frontend/abstract/core/src/domain/element/element.model.interface.ts, libs/frontend/domain/builder/src/sections/explorer-pane/builder-tree/BuilderTreeItem-Title.tsx, libs/frontend/domain/element/src/store/element.model.ts, libs/frontend/domain/renderer/src/element/ElementWrapper.ts, package.json, yarn.lock
https://user-images.githubusercontent.com/51242349/194311949-9ef79e83-c7cd-418e-a6e9-9f8e081e8d72.mp4
Fixes #1214
=> Renderer Error Handling Module

.circleci/config.yml, apps/builder-e2e/src/e2e/builder.cy.ts, apps/builder/pages/atoms/index.tsx, libs/frontend/abstract/core/src/domain/action/action.service.interface.ts, libs/frontend/abstract/core/src/domain/app/app.service.interface.ts, libs/frontend/abstract/core/src/domain/atom/atom.service.interface.ts, libs/frontend/abstract/core/src/domain/component/component.service.interface.ts, libs/frontend/abstract/core/src/domain/domain/domain.service.interface.ts, libs/frontend/abstract/core/src/domain/element/element.service.interface.ts, libs/frontend/abstract/core/src/domain/page/page.service.interface.ts, libs/frontend/abstract/core/src/domain/resource/resource.service.interface.ts, libs/frontend/abstract/core/src/domain/store/store.service.interface.ts, libs/frontend/abstract/core/src/domain/tag/tag.service.interface.ts, libs/frontend/abstract/core/src/domain/type/type.service.interface.ts, libs/frontend/abstract/core/src/service/service.interface.ts, libs/frontend/domain/atom/src/graphql/atom.endpoints.graphql.gen.ts, libs/frontend/domain/atom/src/store/atom.service.ts, libs/frontend/domain/atom/src/use-cases/get-atoms/useAtomTable.tsx
test: removed unnecessary interceptions
feat: pagination is added for atoms page
fix: failing interfaces are fixed
Fixes #1843, #1892
=> feat: pagination is added for atoms page

apps/builder/pages/_sites/user/[user]/[app]/[page]/index.tsx, libs/backend/abstract/codegen/src/ogm-types.gen.ts, libs/frontend/abstract/core/src/domain/store/index.ts, libs/frontend/abstract/core/src/domain/store/store.model.interface.ts, libs/frontend/abstract/core/src/domain/store/store.service.interface.ts, libs/frontend/domain/atom/src/graphql/atom.endpoints.graphql, libs/frontend/domain/atom/src/graphql/atom.endpoints.graphql.gen.ts, libs/frontend/domain/renderer/src/typedValueTransformers/ActionTypedValueTransformer.ts, libs/frontend/domain/store/src/store/models/store.model.ts, libs/frontend/domain/store/src/use-cases/state/get-state/GetStateItem.tsx, libs/frontend/domain/store/src/use-cases/state/get-state/GetStateList.tsx, libs/frontend/domain/store/src/view/StoreEditorPane.tsx, libs/shared/abstract/codegen/src/types.api.graphql.gen.ts
=> refactor: store model context refactor

libs/frontend/abstract/core/src/domain/builder/builder.service.interface.ts, libs/frontend/domain/builder/src/store/builder.service.ts, libs/frontend/model/infra/mobx/src/create-root-store.ts
Fixes components list not loaded.
Fixes #1941
=> fix: components not loaded

libs/frontend/domain/type/src/interface-form/type-schema.factory.ts, libs/frontend/domain/type/src/use-cases/types/create-type/create-type.schema.ts, libs/frontend/domain/type/src/use-cases/types/update-type/UpdateTypeModal.tsx, libs/frontend/domain/type/src/use-cases/types/update-type/update-type.schema.ts
https://user-images.githubusercontent.com/51242349/196230528-4f7f2b0c-57c8-4083-bfc0-63868018560b.mp4
Fixes #1937 
Fixes #1953
=> fix: update enum type

apps/builder-e2e/src/e2e/components-tab.cy.ts, libs/frontend/domain/builder/src/sections/config-pane/ConfigPane-ComponentTabContainer/ComponentsGroupedByTag.tsx
Specs for components tab, test if the components list are loaded.
Fixes #1940
=> feat: add specs for components tab

libs/frontend/domain/element/src/use-cases/element/create-element/CreateElementModal.tsx, libs/frontend/domain/element/src/use-cases/element/update-element/UpdateElementForm.tsx, libs/frontend/domain/type/src/interface-form/fields/select-component/SelectComponent.tsx
=> fix: circular referance when setting render props type

apps/cli/src/commands/export/export.command.ts, apps/cli/src/selectionSets/actionSelectionSet.ts, libs/backend/infra/adapter/neo4j/src/selectionSets/appSelectionSet.ts, libs/backend/infra/adapter/neo4j/src/selectionSets/storeSelectionSet.ts
=> fix: user data export

.circleci/config.yml, apps/cli/src/commands/terraform/terraform.command.ts
=> fix: terraform master flow

.circleci/config.yml, terraform/modules/auth0/action_assign_default_role.tf
=> fix: terraform master

libs/backend/infra/adapter/neo4j/src/selectionSets/atomSelectionSet.ts
=> fix: atom type not returned from backend

libs/frontend/domain/renderer/src/test/typedValueTranformers.spec.ts
=> test: fix render props type rendering spec

libs/frontend/abstract/core/src/domain/action/action-base.interface.ts, libs/frontend/abstract/core/src/domain/resource/resource.model.interface.ts, libs/frontend/abstract/core/src/domain/store/store.model.interface.ts, libs/frontend/domain/renderer/src/renderer.model.ts, libs/frontend/domain/resource/src/store/resource.model.ts, libs/frontend/domain/store/src/store/models/api-action.model.ts, libs/frontend/domain/store/src/store/models/base-action.model.ts, libs/frontend/domain/store/src/store/models/code-action.model.ts, libs/frontend/domain/store/src/store/models/store.model.ts, libs/frontend/domain/store/src/use-cases/actions/update-action/UpdateActionModal.tsx
=> feat: support state expression in action/resources config 

apps/builder/pages/apps/[appId]/pages/[pageId]/builder.tsx, libs/frontend/abstract/core/src/domain/builder/builder.service.interface.ts, libs/frontend/domain/builder/src/hooks/useBuilderResize.ts, libs/frontend/domain/builder/src/sections/content/BaseBuilder.tsx, libs/frontend/domain/builder/src/sections/content/Builder.tsx, libs/frontend/domain/builder/src/sections/content/BuilderTabs.tsx, libs/frontend/domain/builder/src/store/builder.service.ts, libs/frontend/domain/page/src/view/PageDetailHeader.tsx, libs/frontend/domain/page/src/view/constants.ts
=> feat: screen size preview for builder page

libs/frontend/domain/type/src/store/models/array-type.model.ts, libs/frontend/domain/type/src/store/type.service.ts
=> fix: types page issues

libs/frontend/domain/builder/src/hooks/usePropCompletion.ts
=> fix: error when navigating to inspector -> props-map tab

apps/cli/src/commands/export/export.command.ts, apps/cli/src/commands/import/import.command.ts, apps/cli/src/commands/tasks/tasks.command.ts, apps/cli/src/repository/user.repo.ts
Commands:
- `yarn cli data import --stage dev|test`
- `yarn cli data export --stage dev|test`
Fixes #1997
=> feat: add stage flag to cli command: export, import

apps/builder/pages/apps/[appId]/pages/[pageId]/index.tsx, libs/frontend/abstract/core/src/domain/builder/renderer.model.interface.ts, libs/frontend/abstract/core/src/domain/element/element.model.interface.ts, libs/frontend/abstract/core/src/domain/element/element.service.interface.ts, libs/frontend/domain/element/src/store/element.model.ts, libs/frontend/domain/element/src/store/element.service.ts, libs/frontend/domain/renderer/src/atoms/antd/antdAtoms.ts, libs/frontend/domain/renderer/src/atoms/codelab/codelabAtoms.ts, libs/frontend/domain/renderer/src/atoms/dynamicLoader.ts, libs/frontend/domain/renderer/src/atoms/mui/muiAtoms.ts, libs/frontend/domain/renderer/src/element/DraggableElementWrapper.tsx, libs/frontend/domain/renderer/src/element/ElementWrapper.ts, libs/frontend/domain/store/src/store/models/code-action.model.ts, libs/frontend/domain/store/src/store/models/store.model.ts, libs/frontend/domain/type/src/interface-form/fields/select-default-value/SelectDefaultValue.tsx, libs/frontend/domain/type/src/store/field.service.ts, libs/frontend/domain/type/src/store/models/array-type.model.ts, libs/frontend/domain/type/src/store/type.service.ts, libs/frontend/domain/type/src/use-cases/fields/create-field/CreateFieldModal.tsx, libs/frontend/domain/type/src/use-cases/fields/create-field/field-utils.ts, libs/frontend/domain/type/src/use-cases/fields/update-field/UpdateFieldModal.tsx
=> feat: expose dom refs

libs/frontend/view/components/form/modal/ModalForm.Form.tsx
=> fix: cannot add item to array type

libs/frontend/domain/store/src/use-cases/state/get-state/GetStateItem.tsx
https://user-images.githubusercontent.com/117329462/203505173-b4f26fdd-fb69-4b41-a65a-23edf88ed997.mov
Fixes #2040
=> fix: default state name with key

apps/builder/pages/apps/[appId]/pages/[pageId]/index.tsx, libs/frontend/abstract/core/src/domain/action/action-base.interface.ts, libs/frontend/abstract/core/src/domain/element/element.model.interface.ts, libs/frontend/abstract/core/src/domain/element/element.service.interface.ts, libs/frontend/abstract/core/src/domain/prop/prop.model.interface.ts, libs/frontend/abstract/core/src/domain/resource/resource.model.interface.ts, libs/frontend/abstract/core/src/domain/store/store.model.interface.ts, libs/frontend/domain/element/src/store/element.model.ts, libs/frontend/domain/element/src/store/element.service.ts, libs/frontend/domain/prop/src/store/prop.model.ts, libs/frontend/domain/renderer/src/element/ElementWrapper.ts, libs/frontend/domain/renderer/src/renderer.model.ts, libs/frontend/domain/resource/src/store/resource.model.ts, libs/frontend/domain/store/src/store/models/api-action.model.ts, libs/frontend/domain/store/src/store/models/base-action.model.ts, libs/frontend/domain/store/src/store/models/code-action.model.ts, libs/frontend/domain/store/src/store/models/store.model.ts, libs/frontend/domain/store/src/use-cases/actions/update-action/UpdateActionModal.tsx
=> feat: state expression in apiAction

libs/frontend/abstract/core/src/domain/element/element.service.interface.ts, libs/frontend/domain/element/src/store/element.service.ts, libs/frontend/domain/element/src/use-cases/element/update-rich-text/UpdateRichTextForm.tsx
https://user-images.githubusercontent.com/117329462/203890293-52fb5c78-aa23-4af1-a5db-c64d7e8ea1d2.mov
> Local update instantly while api delayed
https://user-images.githubusercontent.com/117329462/204436371-bd63012c-3877-404c-89bb-1c9cae0930ff.mov
Fixes #2034
=> feat: debouncer for text props

libs/frontend/view/components/codeMirror/setup.ts
https://user-images.githubusercontent.com/117329462/203462998-830b2518-b1d4-4463-b391-d3bee5ada3e6.mov
Fixes #1986
=> fix: can't write { inside quotes

libs/frontend/domain/type/src/shared/TypeSelect.tsx, libs/frontend/domain/type/src/use-cases/fields/create-field/CreateFieldModal.tsx, libs/frontend/domain/type/src/use-cases/fields/update-field/UpdateFieldModal.tsx, libs/frontend/domain/type/src/use-cases/types/create-type/CreateTypeModal.tsx, libs/frontend/domain/type/src/use-cases/types/update-type/UpdateTypeModal.tsx
=> fix: TypeSelect types loading

apps/builder/pages/_sites/user/[user]/[app]/[page]/index.tsx, libs/frontend/abstract/core/src/domain/element/element-tree.interface.model.ts, libs/frontend/domain/builder/src/sections/content/Builder-Component.tsx, libs/frontend/domain/component/src/store/component.service.ts
because of more async UI loading - some parts of data may not be available yet and cause script error during initialization
=> fix(apps): fix script error (#2101)

libs/frontend/view/components/form/fields/ToggleExpressionField.tsx
=> fix(libs-frontend-view): fix script error in e2e test

libs/backend/infra/adapter/neo4j/src/cypher/type/getBaseTypes.cypher, libs/frontend/domain/type/src/store/type.service.ts, libs/frontend/domain/type/src/use-cases/fields/get-fields/FieldsTable.tsx, libs/frontend/domain/type/src/use-cases/types/get-types/GetTypesTable.tsx, libs/frontend/domain/type/src/use-cases/types/get-types/useTypesTableData.ts
- load sub types of current page only when expanded
- make typesList alphabetical
Fixes #2117 
Fixes #2090
=> fix(libs): fix empty type and kind column on types table (#2117)

.env.example, apps/landing/home/tutorials/TutorialsBody.tsx, apps/landing/pages/tutorials/index.tsx, apps/landing/utils/supabase.ts, libs/shared/env/src/env-public.ts, terraform/environments/ci/module-circleci.tf, terraform/environments/ci/symlink.sh, terraform/environments/ci/vars-supabase.symlink.tf, terraform/environments/prod/module-vercel.tf, terraform/environments/prod/symlink.sh, terraform/environments/prod/vars-supabase.symlink.tf, terraform/environments/shared/vars-supabase.tf, terraform/modules/circleci/environment-resource.tf, terraform/modules/circleci/vars.tf, terraform/modules/supabase/vars.tf, terraform/modules/vercel-landing/project.tf, terraform/modules/vercel-landing/vars-supabase.symlink.tf
- Integrate supabase to tutorials page
- Use data get from supabase instead of hard code
Fixes #1994
=> feat: integrate supabase to tutorials page

examples/todo-crud-app/README.md, examples/todo-crud-app/seed-data.json, examples/todo-crud-app/user-data.json
- Create `examples` where we store exported data for things we build.
- Add Todo app exported data.
Fixes #
=> feat: add exported data to examples

apps/builder/pages/atoms/index.tsx, apps/builder/pages/types/index.tsx, libs/frontend/domain/atom/src/use-cases/get-atoms/GetAtomsTable.tsx, libs/frontend/domain/type/src/use-cases/types/get-types/GetTypesTable.tsx
=> url driven pagination

libs/frontend/abstract/core/src/domain/element/element.service.interface.ts, libs/frontend/domain/builder/src/hooks/useElementTreeDrop/useElementTreeDrop.ts, libs/frontend/domain/element/src/store/element.service.ts
When component is drag-n-dropped into another component - create an instance of it.
https://user-images.githubusercontent.com/74900868/212316728-2ebc20af-4122-4828-a292-885f2286eef4.mov
Fixes #1753
=> fix: create instance of a component on DnD

apps/landing/home/TestimonialSection.tsx, libs/frontend/view/templates/SidebarNavigation/SidebarNavigation.tsx
Remove unnecessary border for the sidebar navigation.
Fixes #2147
=> fix: border offset

apps/builder/pages/admin/index.tsx, apps/builder/pages/apps/[appId]/domains/index.tsx, apps/builder/pages/apps/[appId]/pages/[pageId]/builder.tsx, apps/builder/pages/apps/[appId]/pages/[pageId]/index.tsx, apps/builder/pages/apps/[appId]/pages/index.tsx, apps/builder/pages/apps/index.tsx, apps/builder/pages/atoms/index.tsx, apps/builder/pages/lambdas/index.tsx, apps/builder/pages/resources/index.tsx, apps/builder/pages/tags/index.tsx, apps/builder/pages/types/index.tsx, libs/frontend/abstract/core/src/domain/user/user.interface.ts, libs/frontend/domain/user/src/store/user.model.ts, libs/frontend/presenter/container/src/pageHooks/index.ts, libs/frontend/presenter/container/src/pageHooks/useRenderedPage.ts, libs/frontend/view/sections/Menu/commonMenuItems.tsx, libs/frontend/view/templates/Dashboard/DashboardTemplate.tsx, libs/frontend/view/templates/Dashboard/Sidebar/SidebarNavigation.tsx, libs/frontend/view/templates/Dashboard/Sidebar/index.ts, libs/frontend/view/templates/Dashboard/index.ts, libs/frontend/view/templates/Dashboard/types.tsx
=> refactor: use route param hook and simplify template

apps/builder-e2e/src/e2e/components-tab.cy.ts, apps/builder-e2e/src/e2e/css.cy.ts, apps/builder/pages/apps/[appId]/pages/[pageId]/builder.tsx, libs/frontend/domain/builder/src/sections/editor-pane/EditorPane-Builder.tsx, libs/frontend/domain/builder/src/sections/explorer-pane/BuilderExplorerPane.tsx, libs/frontend/domain/component/src/use-cases/create-component/CreateComponentButton.tsx, libs/frontend/domain/element/src/use-cases/element/create-element/CreateElementButton.tsx, libs/frontend/domain/store/src/use-cases/actions/create-action/CreateActionButton.tsx, libs/frontend/domain/type/src/use-cases/fields/create-field/CreateFieldButton.tsx, libs/frontend/view/components/pane/EditorPaneHeader.tsx, libs/frontend/view/templates/Dashboard/DashboardTemplate-ExplorerPane.tsx, libs/frontend/view/templates/Dashboard/DashboardTemplate.tsx, libs/frontend/view/templates/ExplorerPaneTemplate.tsx
Moves the bottom store panel to the left panel
Fixes #2041
=> refactor(apps-builder): move store to the left pane

libs/shared/env/src/env-builder.ts
=> wip: temporarily log env variables for debugging

libs/shared/env/src/env-builder.ts
=> fix: revert commit which breaks e2e

libs/shared/config/src/flags.ts, libs/shared/config/src/graphql.ts, libs/shared/env/src/env-builder.ts
=> fix: fix flag values and URLs

apps/builder/middleware.ts
=> chore: remove logs that were added temporarily

apps/builder/pages/_sites/user/[user]/[app]/[page]/index.tsx, libs/frontend/abstract/types/src/pageProps.ts, libs/frontend/presenter/container/src/pageHooks/useRenderedPage.ts
Fix _sites page. Currently, it uses SSG but the page will regenerate on each request. In future commits, I am going to add regeneration by manual request instead.
Fixes #
=> fix: make _sites page working

libs/frontend/abstract/core/src/domain/builder/renderer.model.interface.ts, libs/frontend/abstract/core/src/domain/render/render.interface.ts, libs/frontend/domain/component/src/store/api.utils.ts, libs/frontend/domain/renderer/src/abstract/RenderOutput.ts, libs/frontend/domain/renderer/src/element/ElementWrapper.ts, libs/frontend/domain/renderer/src/renderPipes/atomRenderPipe.ts, libs/frontend/domain/renderer/src/renderPipes/conditionalRenderPipe.ts, libs/frontend/domain/renderer/src/renderPipes/nullRenderPipe.ts, libs/frontend/domain/renderer/src/renderPipes/passThroughRenderPipe.ts, libs/frontend/domain/renderer/src/renderer.model.ts, libs/frontend/domain/renderer/src/test/conditionalRenderPipe.spec.ts, libs/frontend/domain/renderer/src/test/renderer.spec.ts
Fixed the following:
- components in the main builder are not showing
- this is due to the `element` being passed [here](https://github.com/codelab-app/platform/blob/e40ff66f7a0f0af4a832975498b4eebf9e18893f/libs/frontend/domain/renderer/src/element/ElementWrapper.ts#L70) is not the rootElement of a component that has children, instead it is the parent of the rootElement.
- we are traversing it inside the [componentRenderPipe](https://github.com/codelab-app/platform/blob/e40ff66f7a0f0af4a832975498b4eebf9e18893f/libs/frontend/domain/renderer/src/renderPipes/componentRenderPipe.ts#L28) to get the rootElement but we haven't passed it [here](https://github.com/codelab-app/platform/blob/e40ff66f7a0f0af4a832975498b4eebf9e18893f/libs/frontend/domain/renderer/src/element/ElementWrapper.ts#L70)
- I …
=> fix: components not showing and error upon creation

apps/builder/pages/api/regenerate.ts
Manual static page regeneration of user pages works only when executed on the user domain. So for example, if we want to regenerate some pages for `some-user-app.com` domain - we should specify the header with the domain name, even though they share the same codebase.
https://user-images.githubusercontent.com/74900868/218331515-313809a0-cd03-45d8-9256-ebcfaf6b5bfa.mov
Fixes #1617
=> fix: static page regeneration issue

apps/builder/pages/api/regenerate.ts
Refactor ISR api endpoint
Fixes #1617
=> refactor: static page revalidation

libs/frontend/domain/element/src/components/RenderTypeCompositeField.tsx
Fixed Closes #2261 
- Fixed flickering error with AutoField Component
https://user-images.githubusercontent.com/87414033/219500986-32d8fee1-ada9-479c-a71f-651437d052c2.mp4
Fixes #2261 
Fixes #2262
=> fix: atom component flickering id and name

libs/frontend/domain/element/src/store/compute-element-name.service.ts
https://user-images.githubusercontent.com/51242349/219856399-7c827888-c0c9-4cba-9e82-a275a2c8862e.mp4
Fixes #2235
=> fix: prevent name picked by user from changing with render type

libs/frontend/domain/element/src/use-cases/element/update-element/UpdateElementForm.tsx, libs/frontend/view/components/form/components/Form.tsx
~The auto-update issue when selecting a node is introduced when we added some kind of computation for the name/slug. Theres [work](https://github.com/codelab-app/platform/pull/2264) being done that would change the behaviour again and could fix the issue but we can also prevent the submit when theres actually no changes in the form.~
~I added a logic in the [Form](https://github.com/codelab-app/platform/pull/2278/files#diff-fd9129e27b7bbdce155ea18b8a8f07101b9165b6afb1e4bd939da3528ce4846aR64) component so that it will only proceed to submit when theres actually some changes. If there is no changes, a no-op will run instead.~
Also moved [this](https://github.com/codelab-app/platform/pull/2278/files#diff-65a8b4d9c81576fe961a481ee992fcbc7681b6729e4cedd1889b7ac4048745e7R66) out of `useRef` so …
=> fix: autosave interfering as user types

libs/backend/infra/adapter/neo4j/src/schema/model/page.schema.ts
=> fix: add missing page model auth rules

libs/frontend/domain/app/src/use-cases/create-app/createAppSchema.ts, libs/frontend/domain/app/src/use-cases/update-app/updateAppSchema.ts, libs/frontend/domain/element/src/use-cases/element/create-element/createElementSchema.ts, libs/frontend/domain/element/src/use-cases/element/update-element/updateElementSchema.ts, libs/frontend/domain/page/src/use-cases/create-page/createPageSchema.ts, libs/frontend/domain/page/src/use-cases/update-page/updatePageSchema.ts, libs/shared/utils/src/uniform.ts
=> user friendly message for name validation error

apps/cli/src/use-cases/import/import-fields.ts, libs/backend/domain/element/src/repository/element.repo.ts, libs/backend/infra/adapter/neo4j/src/schema/model/action.schema.ts, libs/backend/infra/adapter/neo4j/src/selectionSets/elementSelectionSet.ts, libs/frontend/domain/app/src/store/app.service.ts, libs/frontend/domain/page/src/services/page.factory.ts, libs/frontend/domain/page/src/store/page.model.ts, libs/frontend/domain/page/src/store/page.service.ts, libs/shared/abstract/codegen/src/ogm-types.gen.ts, libs/shared/abstract/codegen/src/types.api.graphql.gen.ts, schema.api.graphql
- fix issue when creating an app
- ran codegen to update with the new types (preRenderAction, postRenderAction)
Still trying to make the builder work, right now the `GetRenderedPageAndCommonAppData` is failing due to outdated generated types and causing a null `rootElement`. Im also trying to build the builder but currently failing with some type issues.
Fixes #
=> fix: create app and trying to make the builder page work

libs/frontend/domain/atom/src/use-cases/get-atoms/GetAtomsTable.tsx, libs/frontend/domain/tag/src/use-cases/get-tags/GetTagsTable.tsx
=> fix: atom and tags tables are not scrollable

apps/websites/pages/[domain]/[page].tsx, apps/websites/pages/api/regenerate.ts, libs/frontend/abstract/core/src/domain/element/element-tree.interface.model.ts, libs/frontend/domain/element/src/store/element-tree/element-tree.model.ts, libs/frontend/domain/element/src/store/element.model.ts, libs/frontend/domain/element/src/use-cases/element/create-element/CreateElementButton.tsx, libs/frontend/domain/element/src/use-cases/element/delete-element/DeleteElementButton.tsx, libs/frontend/domain/element/src/use-cases/element/delete-element/DeleteElementModal.tsx, libs/frontend/domain/page/src/store/page.model.ts, libs/frontend/domain/page/src/store/page.service.ts
Fixes build and linting errors
=> fix: build and linting errors

apps/builder-e2e/src/e2e/builder.cy.ts, apps/builder-e2e/src/e2e/components-tab.cy.ts, apps/builder-e2e/src/e2e/props/createComponentInput.ts, apps/builder-e2e/src/support/database/app.ts, libs/backend/application/atom/src/use-case/seed-atoms/seed-atoms.service.ts, libs/backend/infra/adapter/neo4j/src/resolver/ogm-resolver/atom/field/atoms.ts, libs/frontend/abstract/core/src/domain/app/app.fragment.graphql, libs/frontend/domain/app/src/store/app.service.ts, libs/frontend/domain/atom/src/use-cases/update-atom/UpdateAtomModal.tsx, libs/frontend/domain/tag/src/store/tag.service.ts, libs/frontend/domain/tag/src/use-cases/update-tag/UpdateTagModal.tsx, libs/shared/abstract/codegen/src/ogm-types.gen.ts, libs/shared/abstract/codegen/src/types.api.graphql.gen.ts, schema.api.graphql
=> wip: fix e2e

libs/frontend/domain/element/src/components/RenderTypeCompositeField.tsx, libs/frontend/domain/element/src/components/SelectLinkElement.tsx, libs/frontend/domain/element/src/use-cases/element/create-element/CreateElementModal.tsx, libs/frontend/domain/element/src/use-cases/element/move-element/MoveElementForm.tsx, libs/frontend/domain/element/src/use-cases/element/update-element/UpdateElementForm.tsx, libs/frontend/domain/renderer/src/renderer.model.ts
=> fix: builder page crashing

libs/frontend/domain/component/src/store/component.model.ts, libs/frontend/domain/component/src/store/component.service.ts, libs/frontend/domain/component/src/use-cases/create-component/CreateComponentModal.tsx, libs/frontend/domain/element/src/store/element-tree/element-tree.service.ts
This fixes creating a component
Theres still an issue when selecting a component in the explorer, somehow the component is not being resolved properly even if it should be existing already
Im still figuring it out why is it not being resolved
Fixes #
=> fix: creating components

libs/frontend/abstract/core/src/domain/action/action.dto.interface.ts, libs/frontend/abstract/core/src/domain/action/actions/api-action/api-action.dto.interface.ts, libs/frontend/abstract/core/src/domain/resource/resource.fragment.graphql, libs/frontend/abstract/core/src/domain/resource/resource.fragment.graphql.gen.ts, libs/frontend/abstract/core/src/domain/store/index.ts, libs/frontend/abstract/core/src/domain/store/store.dto.interface.ts, libs/frontend/abstract/core/src/domain/store/store.model.interface.ts, libs/frontend/abstract/core/src/domain/store/store.repository.interface.ts, libs/frontend/domain/app/src/store/app.service.ts, libs/frontend/domain/page/src/store/page.repository.ts, libs/frontend/domain/page/src/store/page.service.ts, libs/frontend/domain/store/src/services/store.repository.ts, libs/frontend/domain/store/src/store/action.factory.ts, libs/frontend/domain/store/src/store/action.service.ts, libs/frontend/domain/store/src/store/apis/api.utils.ts, libs/frontend/domain/store/src/store/models/store.model.ts, libs/frontend/domain/store/src/store/store.service.ts, libs/shared/abstract/codegen/src/types.api.graphql.gen.ts
- Add store repository 
- Tweaks on action `DTO` types (keep only id reference ) 
Fixes #2291
=> refactor: store model

libs/backend/application/type/src/parser/matchers.spec.ts, libs/frontend/domain/domain/src/store/domain.model.ts, libs/frontend/domain/prop/src/store/prop.model.ts, scripts/jest/setupFiles.js
=> fix: unit tests

libs/frontend/abstract/core/src/domain/domain/domain.dto.interface.ts, libs/frontend/abstract/core/src/domain/domain/domain.model.interface.ts, libs/frontend/abstract/core/src/domain/domain/domain.repository.interface.ts, libs/frontend/abstract/core/src/domain/domain/index.ts, libs/frontend/domain/domain/src/services/domain.repository.ts, libs/frontend/domain/domain/src/services/index.ts, libs/frontend/domain/domain/src/store/domain.model.ts, libs/frontend/domain/domain/src/store/domain.service.ts, libs/frontend/domain/domain/src/use-cases/create-domain/CreateDomainModal.tsx, libs/frontend/domain/domain/src/use-cases/update-domain/UpdateDomainModal.tsx
=> wip: add domain repository

apps/builder/pages/apps/[appId]/pages/[pageId]/builder.tsx, apps/builder/pages/atoms/index.tsx, apps/websites/pages/[domain]/[page].tsx, libs/backend/application/tag/src/use-case/seed-tags/seed-tags.service.ts, libs/backend/application/type/src/use-case/seed-ant-design-fields/seed-ant-design-fields.service.ts, libs/backend/application/type/src/use-case/transform-ant-design-types/transform-ant-design-types.service.ts, libs/backend/domain/tag/src/model/tag.model.ts, libs/backend/domain/type/src/factory/type.factory.ts, libs/backend/domain/type/src/model/primitive-type.model.ts, libs/backend/domain/type/src/model/react-node-type.model.ts, libs/backend/domain/type/src/model/render-props-type.model.ts, libs/backend/domain/type/src/model/union-type.model.ts, libs/frontend/abstract/core/src/domain/page/page.service.interface.ts, libs/frontend/abstract/types/src/pageProps.ts, libs/frontend/domain/atom/src/store/atom.service.ts, libs/frontend/domain/atom/src/use-cases/get-atoms/index.ts, libs/frontend/domain/builder/src/sections/explorer-pane/builder-tree/BuilderTreeItem-ComponentTitle.tsx, libs/frontend/domain/renderer/src/renderPipes/componentRenderPipe.ts
=> fix: "websites" project and lint errors

libs/frontend/domain/element/src/use-cases/element/delete-element/delete-element.schema.ts, libs/frontend/view/components/form/hooks/uniformUtils.ts
Just fixing the incorrect schema for deleting an element.
https://user-images.githubusercontent.com/27695022/223966163-99bc02fe-3307-4d44-a366-2a970bfde13f.mp4
Fixes #2348
=> fix: incorrect delete element schema structure

libs/backend/domain/action/src/repository/action.repo.ts, libs/backend/domain/element/src/repository/element.repo.ts, libs/backend/domain/resource/src/repository/resource.repo.ts, libs/frontend/abstract/core/src/domain/atom/atom.model.interface.ts, libs/frontend/abstract/core/src/domain/atom/atom.repository.interface.ts, libs/frontend/abstract/core/src/domain/atom/atom.service.interface.ts, libs/frontend/abstract/core/src/domain/atom/index.ts, libs/frontend/domain/atom/src/store/atom.model.ts, libs/frontend/domain/atom/src/store/atom.repository.ts, libs/frontend/domain/atom/src/store/atom.service.ts, libs/shared/abstract/codegen/src/ogm-types.gen.ts
=> refactor: atoms repository

libs/frontend/domain/domain/src/store/domain.service.ts, libs/frontend/domain/domain/src/use-cases/update-domain/UpdateDomainModal.tsx
=> fix: fetch domain after create/update to get backend-generated data too

libs/frontend/domain/app/src/store/app.service.ts
=> fix: pageRef error when openning a page

libs/frontend/abstract/core/src/domain/type/fragments/type.fragment.graphql, libs/frontend/abstract/core/src/domain/type/fragments/type.fragment.graphql.gen.ts, libs/frontend/abstract/core/src/domain/type/type.repo.interface.ts, libs/frontend/abstract/core/src/domain/type/type.service.interface.ts, libs/shared/abstract/codegen/src/types.api.graphql.gen.ts
=> fix: projects build

libs/backend/infra/adapter/neo4j/src/selectionSet/componentSelectionSet.ts, libs/frontend/abstract/core/src/domain/app/app.dto.interface.ts, libs/frontend/abstract/core/src/domain/element/element.model.interface.ts, libs/frontend/abstract/core/src/domain/element/element.service.interface.ts, libs/frontend/domain/app/src/store/app.service.ts, libs/frontend/domain/component/src/store/component.service.ts, libs/frontend/domain/element/src/services/element.repo.ts, libs/frontend/domain/element/src/store/element.model.ts, libs/frontend/domain/element/src/store/element.service.ts
- [fixed issue where the atomRefs are not resolved for components because only elements in the page are loaded](https://github.com/codelab-app/platform/pull/2369/files#diff-e84d0b3998aae3c825257c64dab48ed1b4416cd88991d89a263768e5441d9de5R130)
- [fixed non-nullable issues by using the interfaceTypeSelectionSet that is also used for renderAtomType](https://github.com/codelab-app/platform/pull/2369/files#diff-8464bf614b59e79f4b85dabf9ef9d1821a7c055b43429cc89e779c50b153840aR15)
- did some code cleanups, removed unused methods
**Note: wasn't able to test completely due to some type issues encountered when trying to play around inspector config pane**
Fixes #
=> fix: ref issues on components

libs/frontend/abstract/core/src/domain/app/app.model.interface.ts, libs/frontend/abstract/core/src/domain/atom/atom.model.interface.ts, libs/frontend/abstract/core/src/domain/domain/domain.model.interface.ts, libs/frontend/abstract/core/src/domain/element/element.model.interface.ts, libs/frontend/abstract/core/src/domain/model.interface.ts, libs/frontend/abstract/core/src/domain/page/page.model.interface.ts, libs/frontend/abstract/core/src/domain/prop/prop.model.interface.ts, libs/frontend/abstract/core/src/domain/resource/resource.model.interface.ts, libs/frontend/abstract/core/src/domain/store/store.model.interface.ts, libs/frontend/abstract/core/src/domain/tag/tag.model.interface.ts, libs/frontend/abstract/core/src/domain/type/types/action-type/action-type.interface.ts, libs/frontend/abstract/core/src/domain/type/types/app-type/app-type.interface.ts, libs/frontend/abstract/core/src/domain/type/types/array-type/array-type.interface.ts, libs/frontend/abstract/core/src/domain/type/types/base-type/base-type.interface.ts, libs/frontend/abstract/core/src/domain/type/types/code-mirror-type/code-mirror-type.interface.ts, libs/frontend/abstract/core/src/domain/type/types/element-type/element-type.interface.ts, libs/frontend/abstract/core/src/domain/type/types/enum-type/enum-type.interface.ts, libs/frontend/abstract/core/src/domain/type/types/interface-type/interface-type.interface.ts, libs/frontend/abstract/core/src/domain/type/types/lambda-type/lambda-type.interface.ts, libs/frontend/abstract/core/src/domain/type/types/page-type/page-type.interface.ts, libs/frontend/abstract/core/src/domain/type/types/primitive-type/primitive-type.interface.ts, libs/frontend/abstract/core/src/domain/type/types/react-node-type/react-node-type.interface.ts, libs/frontend/abstract/core/src/domain/type/types/render-props-type/render-props-type.interface.ts, libs/frontend/abstract/core/src/domain/type/types/union-type/union-type.interface.ts
=> refactor: introduce IModel

libs/frontend/abstract/core/src/domain/type/field.dto.interface.ts, libs/frontend/abstract/core/src/domain/type/field/field.interface.ts, libs/frontend/abstract/core/src/domain/type/field/field.repo.interface.ts, libs/frontend/abstract/core/src/domain/type/field/field.service.interface.ts, libs/frontend/abstract/core/src/domain/type/field/index.ts, libs/frontend/domain/domain/src/store/domain.service.ts, libs/frontend/domain/type/src/services/field.repo.ts, libs/frontend/domain/type/src/store/field.service.ts, libs/frontend/domain/type/src/store/models/field.model.ts, libs/frontend/domain/type/src/use-cases/fields/delete-field/DeleteFieldModal.tsx
=> refactor: field repo

libs/frontend/abstract/core/src/domain/type/types/action-type/action-type.interface.ts, libs/frontend/abstract/core/src/domain/type/types/app-type/app-type.interface.ts, libs/frontend/abstract/core/src/domain/type/types/array-type/array-type.interface.ts, libs/frontend/abstract/core/src/domain/type/types/base-type/base-type.interface.ts, libs/frontend/abstract/core/src/domain/type/types/code-mirror-type/code-mirror-type.interface.ts, libs/frontend/abstract/core/src/domain/type/types/element-type/element-type.interface.ts, libs/frontend/abstract/core/src/domain/type/types/enum-type/enum-type.interface.ts, libs/frontend/abstract/core/src/domain/type/types/interface-type/interface-type.interface.ts, libs/frontend/abstract/core/src/domain/type/types/lambda-type/lambda-type.interface.ts, libs/frontend/abstract/core/src/domain/type/types/page-type/page-type.interface.ts, libs/frontend/abstract/core/src/domain/type/types/primitive-type/primitive-type.dto.interface.ts, libs/frontend/abstract/core/src/domain/type/types/primitive-type/primitive-type.interface.ts, libs/frontend/abstract/core/src/domain/type/types/react-node-type/react-node-type.interface.ts, libs/frontend/abstract/core/src/domain/type/types/render-props-type/render-props-type.interface.ts, libs/frontend/abstract/core/src/domain/type/types/union-type/union-type.interface.ts, libs/frontend/domain/type/src/store/base-type.ts, libs/frontend/domain/type/src/store/models/base-type.model.ts
remove toDeleteInput from base-type so typescript does not complain
Fixes #
=> fix: type model interfaces

libs/frontend/domain/type/src/store/field.service.ts
=> refactor: use interfaceType writeCache instead of writeFieldCache

libs/backend/application/admin/src/use-case/seed-data/seed-data.i.spec.ts, libs/backend/application/tag/src/use-case/seed-tags/seed-tags.service.ts
=> fix: field type issue

apps/builder-e2e/src/e2e/component.cy.ts, apps/builder-e2e/src/e2e/pages.cy.ts, apps/builder/pages/apps/index.tsx, apps/landing/home/HomeTemplate.tsx, apps/landing/pages/_app.tsx, libs/frontend/abstract/core/src/domain/component/component.model.interface.ts, libs/frontend/abstract/core/src/domain/element/element-tree.interface.model.ts, libs/frontend/abstract/core/src/domain/element/element.model.interface.ts, libs/frontend/domain/builder/src/sections/explorer-pane/builder-tree/BuilderTree.tsx, libs/frontend/domain/builder/src/store/builder.service.ts, libs/frontend/domain/component/src/services/component.repo.ts, libs/frontend/domain/component/src/store/component.model.ts, libs/frontend/domain/component/src/use-cases/create-component/CreateComponentModal.tsx, libs/frontend/domain/component/src/use-cases/update-component/UpdateComponentForm.tsx, libs/frontend/domain/element/src/components/RenderTypeCompositeField.tsx, libs/frontend/domain/element/src/store/element-tree/element-tree.model.ts, libs/frontend/domain/element/src/use-cases/element/create-element/CreateElementModal.tsx, libs/frontend/domain/element/src/use-cases/element/update-element/UpdateElementForm.tsx
Fixed a couple of component-related issues:
- issues with cloning (some of the component data was not cloned)
- issue with updating component props on form
- issue when ref id was used instead of actual element/component id
Fixes #
=> fix: component issues, landing project build

libs/backend/application/admin/src/use-case/seed-data/seed-data.i.spec.ts, libs/backend/application/atom/src/use-case/export-atoms.ts, libs/backend/application/tag/src/use-case/export-tags.ts, libs/backend/application/type/src/use-case/export-admin-types.ts, libs/backend/infra/adapter/neo4j/src/selectionSet/atomSelectionSet.ts, libs/backend/infra/adapter/neo4j/src/selectionSet/tagSelectionSet.ts
- field type issue
- remove owner from export
Fixes #
=> fix: import/export

libs/backend/infra/adapter/neo4j/src/selectionSet/elementSelectionSet.ts
Fixes the syntax error that causes the builder page to crash when there is an element
Fixes #
=> fix: syntax error on the element selection set

apps/builder-e2e/src/e2e/providers-page.cy.ts, libs/frontend/domain/app/src/store/app.service.ts, libs/frontend/domain/component/src/store/component.model.ts, libs/frontend/domain/page/src/store/page.repo.ts, libs/frontend/domain/renderer/src/renderer.model.ts, libs/frontend/domain/renderer/src/test/setup/setup-test.ts, libs/frontend/presenter/container/src/pageHooks/useRenderedPage.ts
- fix provider page rendering issues
- fix provider-page.cy e2e test
- update provider-page.cy spec to use Space component instead of ConfigProvider in order to avoid instabilities in headless mode while still validating all the required cases
Fixes #
=> fix: provider page issues and provider-page.cy spec

libs/frontend/view/templates/Dashboard/ResizeHandle.tsx
=> fix: remove resize handler width on hover

libs/backend/application/type/src/use-case/export-admin-types.ts
=> feat: nested apis export two levels

libs/frontend/abstract/core/src/domain/action/action.dto.interface.ts, libs/frontend/domain/builder/src/sections/explorer-pane/BuilderExplorerPane.tsx, libs/frontend/domain/store/src/store/action.factory.ts, libs/frontend/domain/store/src/store/action.service.ts, libs/frontend/domain/store/src/use-cases/actions/delete-action/DeleteActionsModal.tsx, libs/frontend/domain/store/src/use-cases/actions/update-action/UpdateActionModal.tsx
- prevent changing action type on update.
- misc refactors
Fixes #
=> refactor: action model

apps/builder/pages/apps/[appId]/pages/[pageId]/builder.tsx, apps/builder/pages/apps/[appId]/pages/[pageId]/index.tsx, libs/backend/infra/adapter/neo4j/src/cypher/component/getDescendantComponentIds.cypher, libs/frontend/domain/app/src/store/app.service.ts, libs/frontend/domain/builder/src/dnd/BuilderContext.tsx, libs/frontend/domain/builder/src/sections/config-pane/ConfigPane.tsx, libs/frontend/domain/builder/src/sections/explorer-pane/BuilderExplorerPane.tsx, libs/frontend/domain/builder/src/sections/explorer-pane/ElementContextMenu.tsx, libs/frontend/domain/builder/src/sections/explorer-pane/builder-tree/BuilderTree.tsx, libs/frontend/domain/builder/src/sections/explorer-pane/builder-tree/BuilderTreeItem-ComponentTitle.tsx, libs/frontend/domain/builder/src/sections/explorer-pane/builder-tree/BuilderTreeItem-Title.tsx, libs/frontend/domain/component/src/store/component.service.ts, libs/frontend/domain/component/src/use-cases/delete-component/DeleteComponentModal.tsx, libs/frontend/domain/element/src/components/RenderTypeCompositeField.tsx, libs/frontend/domain/element/src/store/element-tree/element-tree.util.ts, libs/frontend/domain/element/src/store/element.model.ts, libs/frontend/domain/element/src/store/element.service.ts, libs/frontend/domain/element/src/use-cases/element/create-element/CreateElementModal.tsx, libs/frontend/domain/element/src/use-cases/element/delete-element/DeleteElementModal.tsx, libs/frontend/domain/page/src/view/PageDetailHeader.tsx, libs/frontend/domain/type/src/interface-form/fields/select-component/SelectComponent.tsx, libs/frontend/domain/type/src/use-cases/fields/create-field/CreateFieldModal.tsx, libs/frontend/domain/type/src/use-cases/fields/delete-field/DeleteFieldModal.tsx, libs/frontend/domain/type/src/use-cases/fields/update-field/UpdateFieldModal.tsx
- fixes on some component issues
- cleanups for accessing services
Fixes #
=> fix: components issues and some cleanups

libs/frontend/domain/element/src/use-cases/element/update-element/update-element.schema.ts, libs/frontend/domain/tag/src/use-cases/create-tag/create.tag.schema.ts, libs/frontend/domain/tag/src/use-cases/update-tag/update-tag.schema.ts
Applied the solution described here: https://github.com/codelab-app/platform/issues/2314#issuecomment-1446116055
Fixes #2314
=> fix: nested required field makes the parent required too

libs/frontend/domain/tag/src/index.ts, libs/frontend/domain/tag/src/shared/TagSelect.tsx, libs/frontend/domain/tag/src/shared/index.ts, libs/frontend/domain/tag/src/use-cases/create-tag/CreateTagModal.tsx, libs/frontend/domain/tag/src/use-cases/create-tag/create.tag.schema.ts, libs/frontend/domain/type/src/store/type.service.ts, libs/frontend/domain/type/src/use-cases/types/create-type/CreateTypeModal.tsx
This PR fixes the issue for create type and create tag modal.
https://user-images.githubusercontent.com/51242349/228223870-d8cb5925-afea-4a13-90bd-adb47ec78b41.mp4
https://user-images.githubusercontent.com/51242349/228223861-8e5e96b3-94f9-45d8-92c1-3d28292849d0.mp4
Fixes #2382
=> fix: modal flashes incorrect validation error

apps/builder/pages/api/cypress/app.ts, libs/backend/domain/page/src/repository/page.repo.ts, libs/frontend/domain/app/src/store/app.service.spec.ts, libs/frontend/domain/renderer/src/test/setup/setup-test.ts, libs/frontend/domain/type/src/store/models/interface-type.model.ts, libs/frontend/domain/type/src/store/tests/setup-store.ts
- api/cypress/app endpoint was failing because store and api for pages were not created in DB
- also some fixes for unit tests
Fixes #
=> fix: api/cypress/app endpoint, some errors in unit test

libs/frontend/abstract/core/src/domain/action/action.repo.interface.ts, libs/frontend/abstract/core/src/domain/app/app.repo.interface.ts, libs/frontend/abstract/core/src/domain/atom/atom.repo.interface.ts, libs/frontend/abstract/core/src/domain/component/component.repo.interface.ts, libs/frontend/abstract/core/src/domain/domain/domain.repo.interface.ts, libs/frontend/abstract/core/src/domain/element/element.repo.interface.ts, libs/frontend/abstract/core/src/domain/page/page.repo.interface.ts, libs/frontend/abstract/core/src/domain/prop/prop.repo.interface.ts, libs/frontend/abstract/core/src/domain/resource/resource.repo.interface.ts, libs/frontend/abstract/core/src/domain/store/store.repo.interface.ts, libs/frontend/abstract/core/src/domain/tag/tag.repo.interface.ts, libs/frontend/domain/app/jest.config.ts, libs/frontend/domain/element/src/store/element.service.ts
Fix build after merge of this refactoring - https://github.com/codelab-app/platform/pull/2428
Fixes #
=> fix: build after graphql response was reduced

libs/frontend/domain/component/src/store/component.service.ts
https://user-images.githubusercontent.com/51242349/229198566-52730e2f-07f0-46ff-add2-97045d1e9efa.mp4
Fixes #2424
=> fix: clean residue left after deleting a component

.gitignore, scripts/vercel/platform/build.sh, tailwind.config.js, terraform/modules/circleci/environment-resource.tf
- fix build by replacing broken reference to `platform` project in `build.sh`
- fix e2e by adding `AUTH0_AUDIENCE` env variable to CI. It was missing and requests failed with an "unauthenticated" error
Fixes #
=> fix: build and e2e tests

data/export/admin/atoms/AntDesignMenu.json
=> chore: update antDesignMenu API seed data

libs/frontend/domain/type/src/store/models/field.model.ts, libs/frontend/domain/type/src/use-cases/fields/create-field/create-field.schema.ts, libs/frontend/view/components/form/hooks/uniformUtils.ts
This PR does some changes to the validation schema of `defaultValues` field of the field schema. Additionally, it fixes the issue of not being able to reset the value of the default value.
The main issue was that because `oneOf` is used in `fieldDefaultValues` definition and all the options provided are `nullable: true`, when the value is null, multiple intities are matched; hence the value is not valid because we want only one of them to match.
one question that comes to mind would be that there is a conditon that removes `defaultValues` feild from the required list if `validationRules.general.nullable == true`. However, the field not being required does not mean that it's value will not be checked against the schema. hence, the if consition here practically does nothing.
To fix that:
- …
=> fix: default values field validation schema

libs/frontend/domain/page/src/store/page.service.ts
=> fix: remove residue left when deleting page

libs/frontend/abstract/core/src/domain/component/component.model.interface.ts, libs/frontend/domain/component/src/store/component.model.ts, libs/frontend/domain/element/src/use-cases/element/create-element/CreateElementModal.tsx, libs/frontend/domain/element/src/use-cases/element/update-element/UpdateElementForm.tsx, libs/frontend/domain/type/src/interface-form/fields/select-component/SelectComponent.tsx
https://user-images.githubusercontent.com/51242349/231352652-0164695c-7e41-42a0-9efd-d00c72372331.mp4
Fixes #2460
=> fix: select component issues

apps/platform/pages/api/import/app.ts, libs/backend/abstract/core/src/page.interface.ts, libs/backend/application/app/src/use-case/export-apps.ts, libs/backend/application/app/src/use-case/import-apps.ts, libs/backend/domain/app/src/repository/app.repo.ts, libs/backend/domain/component/src/repository/component.repo.ts, libs/backend/domain/element/src/repository/get-descendants.ts, libs/backend/domain/element/src/repository/index.ts, libs/backend/domain/page/src/repository/page.repo.ts, libs/backend/infra/adapter/neo4j/src/selectionSet/appSelectionSet.ts, libs/backend/infra/adapter/neo4j/src/selectionSet/componentSelectionSet.ts, libs/backend/infra/adapter/neo4j/src/selectionSet/elementSelectionSet.ts, libs/backend/infra/adapter/neo4j/src/selectionSet/pageSelectionSet.ts, libs/backend/infra/adapter/neo4j/src/selectionSet/typeSelectionSet.ts, libs/frontend/domain/page/src/use-cases/create-page/create-page.schema.ts
App import and export were broken because of data model changed a lot (new props were introduced, the store moved from the app to pages, etc).
**Before:**
https://user-images.githubusercontent.com/74900868/232205350-ccc459d5-1bce-4520-ac38-22dfa9273bdd.mov
**After:**
https://user-images.githubusercontent.com/74900868/232205498-b51769dd-4965-4a56-8812-f472674b97f7.mov
https://user-images.githubusercontent.com/74900868/232205638-e192f620-efef-45cc-b1e0-5a7bd2072e28.mov
Fixes #2472
=> fix: app import and export

libs/frontend/abstract/core/src/domain/element/element.model.interface.ts, libs/frontend/domain/builder/src/sections/explorer-pane/ElementContextMenu.tsx, libs/frontend/domain/element/src/store/element.model.ts, libs/frontend/domain/element/src/store/element.service.ts, libs/frontend/domain/element/src/utils/makeAutoIncrementedName.ts
https://user-images.githubusercontent.com/51242349/231999286-d14c07f0-d206-43dc-a139-dec977ab27ad.mp4
Fixes #2473
=> fix: duplicate element

libs/frontend/domain/renderer/src/renderer.model.ts
Before this PR a separate function was used to render _app page. This function was not equivalent to how regular pages were rendered. Now the process is unified and the code is reused to render _app and regular pages.
https://user-images.githubusercontent.com/74900868/232859654-cf644edc-540d-446e-8906-1291e103e310.mov
Fixes #2485
=> fix: use common approach to render _app page

examples/portfolio-website/user-data.json
Added pages, menu with links for each page, and title on each page
Part of #2224
=> docs: update portfolio demo app with more features

libs/frontend/domain/renderer/src/renderPipes/atomRenderPipe.ts, libs/frontend/domain/renderer/src/renderer.model.ts
add highlight on select an atom
https://user-images.githubusercontent.com/47860740/233232092-4abce70e-a9d0-4779-b23c-8d9fb81f2bbf.mp4
#2481  highlight hovered/selected element in builder
Fixes #2481 highlight hovered/selected element in builder
=> 2481 highlight selected element

libs/frontend/domain/type/src/use-cases/types/create-type/CreateTypeModal.tsx, libs/frontend/domain/type/src/use-cases/types/get-types/tables/FieldsTable.tsx
enable drag as first fields and enhance onDrag function
https://user-images.githubusercontent.com/47860740/233808377-d5fb5c66-d306-41d9-9a62-c8a36b19ede9.mp4
#2524 can't put field at first on drag
Fixes #
#2524 can't put field at first on drag
=> 2524 cant put field at first on drag

libs/frontend/domain/builder/src/sections/content/Builder.tsx, libs/frontend/domain/builder/src/sections/overlay-toolbar/BuilderClickOverlay.tsx, libs/frontend/domain/renderer/src/renderPipes/atomRenderPipe.ts
add highlight overlay functionality  
https://user-images.githubusercontent.com/47860740/234229334-7db7d306-603f-40c7-9bfd-1377e4a8fd2b.mp4
Image
Fixes:
- #2516
=> fix: add  highlight clicked overlay

libs/frontend/domain/element/src/components/RenderTypeCompositeField.tsx, libs/frontend/domain/element/src/use-cases/element/create-element/CreateElementModal.tsx, libs/frontend/domain/element/src/use-cases/element/update-element/UpdateElementForm.tsx, libs/frontend/domain/type/src/interface-form/fields/select-component/SelectComponent.tsx
https://user-images.githubusercontent.com/51242349/234201563-3ba20097-b4c1-41c8-ad96-5ae93deff3cb.mp4
Fixes #2534
=> fix: prevent selecting parent component for ReactNodeType prop

libs/frontend/domain/builder/src/sections/content/Builder.tsx, libs/frontend/domain/builder/src/sections/explorer-pane/BuilderExplorerPane.tsx, libs/frontend/domain/builder/src/sections/explorer-pane/builder-tree/BuilderTree.tsx, libs/frontend/domain/builder/src/sections/overlay-toolbar/BuilderClickOverlay.tsx, libs/frontend/domain/builder/src/sections/overlay-toolbar/BuilderHoverOverlay.tsx, libs/frontend/domain/renderer/src/renderPipes/atomRenderPipe.ts, libs/frontend/presentation/view/components/hoverOverlay/ClickOverlay.tsx, libs/frontend/presentation/view/components/hoverOverlay/HoverOverlay.tsx
highlight element on hover and change the colors
https://user-images.githubusercontent.com/47860740/234722745-6be669f0-0850-4d38-a561-58345bfaf165.mp4
- #2545 
Fixes
- #2545
=> 2545 highlighted elements on hover

libs/frontend/domain/element/src/store/element.model.ts, libs/frontend/domain/element/src/use-cases/element/update-element-prop-transformation/UpdateElementPropTransformationForm.tsx
=> fix: enable propTransformationJs editor

libs/frontend/domain/element/src/css-editor/ElementCssEditor.tsx
=> fix: guiCss editor not updating element

libs/frontend/domain/builder/src/sections/explorer-pane/BuilderExplorerPane.tsx, libs/frontend/domain/builder/src/sections/explorer-pane/builder-tree/BuilderTree.tsx, libs/frontend/domain/builder/src/sections/explorer-pane/builder-tree/ItemTitleStyle.tsx, libs/frontend/domain/builder/src/sections/explorer-pane/builder-tree/antdTree.styles.ts, libs/frontend/presentation/view/templates/ExplorerPaneTemplate.tsx
https://user-images.githubusercontent.com/51242349/235211575-e85f1c76-a224-4d49-b85f-0adb6a198f45.mp4
Fixes #2543
=> style: improve explorer pane ui

libs/frontend/domain/element/src/store/element.service.ts
Once the component is updated (one of its elements was changed, deleted, or a new element was added to the component) - the instance of that component was not updated until the page was reloaded.
After this PR - any change in the component is synced to all component instances without the need to reload.
https://user-images.githubusercontent.com/74900868/235363520-bd84e6c6-eaad-495b-942d-6761b07adec2.mov
Fixes #2535
=> fix: update page when component changes

libs/frontend/presentation/view/components/hoverOverlay/ClickOverlay.tsx
make hight as builder 
https://user-images.githubusercontent.com/47860740/236564859-7ce579db-7742-42c6-bbca-3f6a219fb097.mp4
- #2555 
Fixes #
- #2555
=> fix: make hight as builder

libs/backend/domain/app/src/repository/app.repo.ts
upsert if exist on create an application  
- #2580 
Fixes #
- #2580
=> fix: update app if exist

libs/frontend/domain/atom/src/store/atom.service.ts, libs/frontend/domain/builder/src/sections/config-pane/ConfigPane-ComponentTabContainer/ComponentsGroupedByTag.tsx, libs/frontend/domain/builder/src/sections/config-pane/ConfigPane-ComponentTabContainer/GetComponentItem.tsx, libs/frontend/domain/builder/src/store/builder.service.ts
- fix broken 2 column layout
- fix component images not being displayed
- add tooltip for component name since most of them do not fit and it is hard to understand what the component is
Before
https://user-images.githubusercontent.com/74900868/236626538-54347f56-277f-42fb-86e0-1cc47e283166.mov
After
https://user-images.githubusercontent.com/74900868/236626453-3e46a523-1939-4a17-8e50-43b701633fdb.mov
Fixes #2492
=> fix: components tab fix and enhancements

libs/frontend/domain/builder/src/sections/content/Builder.tsx
make builder scrollable 
https://github.com/codelab-app/platform/assets/47860740/86c9e72a-67bc-4508-8247-0017f4254882
Fixes #2610
=> fix: make builder scrollaber

apps/platform/pages/api/export/component.ts, data/export/admin/components/GoogleFonts.json, data/export/admin/components/GoogleFontsPicker.json, libs/backend/abstract/core/src/export/admin.interface.ts, libs/backend/abstract/core/src/export/component.interface.ts, libs/backend/application/admin/src/data-paths.ts, libs/backend/application/admin/src/use-case/export-admin-data.service.ts, libs/backend/application/admin/src/use-case/import-admin-data/import-admin-data.service.ts, libs/backend/application/component/src/use-case/export-component.ts, libs/backend/application/type/src/use-case/export/export-admin-types.ts, libs/frontend/domain/component/src/use-cases/get-components/columns/ActionColumn.tsx
Allow component export/import. Components can be exported from the `Components Table` individually and can be imported through cli import.
Fixes #2562
Closes #2561
=> feat: export/import components

libs/frontend/domain/element/src/store/element.service.ts, libs/frontend/domain/element/src/use-cases/element/delete-element/DeleteElementModal.tsx
https://github.com/codelab-app/platform/assets/74900868/ba598246-ab7b-448b-8cb9-8b9b1db0ddfc
Fixes #2623
=> fix: convert element to component error

.github/PULL_REQUEST_TEMPLATE.md
=> chore: experiment with issue description

libs/frontend/abstract/core/src/domain/component/component.service.interface.ts, libs/frontend/domain/builder/src/sections/explorer-pane/BuilderExplorerPane.tsx, libs/frontend/domain/builder/src/sections/explorer-pane/StorePane.tsx, libs/frontend/domain/builder/src/sections/explorer-pane/tab-contents/CustomComponents.tsx
=> fix: restore store for components

libs/shared/config/src/env/env-platform.ts
=> wip: add logging to debug production issue

.github/PULL_REQUEST_TEMPLATE.md
=> chore: revert experiment with issue description

apps/platform-e2e/src/e2e/builder.cy.ts, apps/platform-e2e/src/e2e/component.cy.ts, apps/platform-e2e/src/support/builder/builder.command.ts, libs/frontend/abstract/core/src/domain/element/element.service.interface.ts, libs/frontend/domain/builder/src/sections/explorer-pane/BuilderExplorerPane.tsx, libs/frontend/domain/builder/src/sections/explorer-pane/BuilderExplorerPaneHeader.tsx, libs/frontend/domain/builder/src/sections/explorer-pane/ElementContextMenu.tsx, libs/frontend/domain/builder/src/sections/explorer-pane/builder-tree/BuilderTree.tsx, libs/frontend/domain/builder/src/sections/explorer-pane/builder-tree/BuilderTreeItemComponentTitle.tsx, libs/frontend/domain/builder/src/sections/explorer-pane/tab-contents/CustomComponents.tsx, libs/frontend/domain/element/src/store/element-form.service.ts, libs/frontend/domain/element/src/store/element.service.ts, libs/frontend/domain/element/src/use-cases/element/create-element/CreateElementButton.tsx, libs/frontend/domain/element/src/use-cases/element/create-element/CreateElementForm.tsx, libs/frontend/domain/element/src/use-cases/element/create-element/index.ts
replacement of add element modal add chiled with inline form
https://github.com/codelab-app/platform/assets/47860740/9c425689-60fb-43aa-9b81-039753f35ad9
https://github.com/codelab-app/platform/assets/47860740/5a47e652-aefb-40c0-878f-1974715ee28c
Fixes #2605
=> 2605 replacement of add element modal add chiled with inline form

apps/platform-e2e/src/e2e/css.cy.ts, apps/platform-e2e/src/e2e/providers-page.cy.ts, apps/platform-e2e/src/support/builder/builder.command.ts
=> fix: selector issues in e2e

libs/frontend/domain/renderer/src/atoms/html/html-atoms.ts
https://github.com/codelab-app/platform/assets/74900868/25a5b215-365f-49ba-8d7a-fc0746dd4d59
Fixes #2271
=> feat: add script atom

libs/frontend/domain/resource/src/use-cases/create-resource/create-resource.schema.ts
add title case to resources name
https://github.com/codelab-app/platform/assets/47860740/6628190a-65cd-4bdb-b2e9-0ee2f941e2b7
Fixes #2614
=> fix: add title case to resources name

libs/frontend/domain/builder/src/sections/explorer-pane/tab-contents/ComponentItem.tsx
fix edit button and delete inside a draggable container
https://github.com/codelab-app/platform/assets/47860740/6683b4cd-0d47-4afb-ba1d-c2cf1d908fa2
Fixes #2676
=> fix: edit button and delete inside draggable container

libs/frontend/presentation/view/sections/Menu/CommonMenuItems.tsx
rename component name
Fixes #2697
=> fix: rename component name

libs/frontend/domain/type/src/interface-form/fields/select-union-type-value/SelectUnionTypeValue.tsx
=> fix: cannot use UnionType inside ArrayType

libs/backend/application/user/src/use-case/export-user-data.ts
Sort data before export to provide consistent result on each export
Fixes #2730
=> refactor: provide consistent export

apps/platform/pages/api/vercel/[...domains].ts, libs/backend/infra/adapter/vercel/src/domain/add-domain.ts, libs/backend/infra/adapter/vercel/src/domain/get-domain-config.ts, libs/backend/infra/adapter/vercel/src/domain/get-project-domain.ts, libs/frontend/presentation/container/src/routerHooks/useCurrentApp.hook.ts
Cannot destructure functions that use `this` in the body - then context is lost and the value of `this` becomes undefined and the script errors appear
Fixes #2720
=> fix: script error because context loss

libs/frontend/domain/builder/src/sections/explorer-pane/BuilderPrimarySidebar.tsx
https://github.com/codelab-app/platform/assets/51242349/0b0ff080-766a-4bbd-aa75-547508d00f2e
Fixes #2742
=> fix: actions forms not accessible from explorer sidebar

libs/frontend/presentation/view/templates/Dashboard/DashboardTemplate.tsx
Fix vertical scrolling on page preview
https://github.com/codelab-app/platform/assets/74900868/69b882fd-4d98-4232-9cff-36ba33cb2f46
Fixes #2740
=> fix: enable vertical scroll on pages preview

libs/frontend/domain/type/src/store/type.service.ts
=> fix: nested types are not loaded

libs/frontend/domain/renderer/src/action-runner.model.ts, libs/frontend/domain/type/src/interface-form/ui-properties/action-type-ui-properties.ts, libs/frontend/shared/utils/src/state-expressions.ts
to use state expressions use `state` instead of `this`.
Fixes #2750
=> refactor: replace this with state

.yarn/patches/antd-npm-5.4.2-0091a657e9.patch, libs/backend/application/admin/src/use-case/import-admin-data/import-admin-data.service.ts, libs/frontend/domain/renderer/src/renderPipes/atom-render-pipe.ts, package.json, yarn.lock
make anchor and calender highlighted on select using yarn patch
https://github.com/codelab-app/platform/assets/47860740/61e1c76f-b296-4d15-a495-8fb4c2f7183b
Fixes #2603
=> refactor: not all elements are highlighted in builder

libs/frontend/domain/renderer/src/element-runtime-props.model.ts
=> fix: component props not available in transformFn

libs/frontend/domain/builder/src/sections/explorer-pane/BuilderPrimarySidebar.tsx
=> fix: branch build error

examples/portfolio-website/user-data.json, libs/backend/application/user/src/use-case/export-user-data.ts
- Completed home page
- Completed about page
- Completed mobile and desktop navigation between pages
- Started implementation of GitHub sign-in
Part of #2224
=> docs: complete "home" and "about" page for demo app

libs/frontend/domain/builder/src/sections/explorer-pane/BuilderPrimarySidebar.tsx
Return field modals that were accidentally removed
https://github.com/codelab-app/platform/assets/74900868/7c78a20b-f7bd-4c02-8520-d9f6f2e04ade
Fixes #2785
=> fix: return create/update field modals

libs/frontend/domain/type/src/interface-form/type-schema.factory.ts
=> fix: nested types default field values not populated

libs/backend/application/type/src/use-case/export/export-admin-types.ts
=> fix: nested types not exported

libs/frontend/abstract/core/src/domain/type/field/field.service.interface.ts, libs/frontend/domain/app/src/store/app.service.ts
Additionally delete page stores, fields, and corresponding interfaces
https://github.com/codelab-app/platform/assets/74900868/f5e70a9c-900a-4597-bb1b-416f19df5883
Fixes #2810
=> fix: delete page dependencies on app deletion

libs/backend/domain/page/src/repository/page.repo.ts
When app is exported - also include the components that are used as `childMapperComponent`.
Fixes #2816
=> fix: export childMapper components

data/export/admin/atoms/React-Quill.json, data/export/admin/components/PageTitle.json, yarn.lock
add React quill atom to exported data
Fixes #2269
=> feat: create atom to render md content

libs/frontend/domain/renderer/src/element/element-wrapper.ts, libs/frontend/domain/renderer/src/element/wrapper.utils.ts
=> fix: customText prop added as an element attribute

libs/frontend/domain/renderer/src/element/get-styled-components.ts
https://github.com/codelab-app/platform/assets/74900868/e0d938bf-4869-4d99-b2b1-85482f7925c3
Fixes #2836
=> fix: allow HTML atoms to be styled

libs/frontend/domain/page/src/store/page.service.ts
=> fix: error when deleting page

libs/tools/workspace/project.json
Fixes this error in ci
Fixes #2874
=> fix: tools-workspace build in ci

apps/platform-e2e/src/e2e/atoms.cy.ts, apps/platform/pages/atoms/index.tsx, libs/frontend/abstract/core/src/domain/atom/atom.service.interface.ts, libs/frontend/abstract/core/src/ui/atoms-tree.interface.ts, libs/frontend/abstract/core/src/ui/index.ts, libs/frontend/domain/atom/src/store/atom-form.service.ts, libs/frontend/domain/atom/src/store/atom.service.ts, libs/frontend/domain/atom/src/use-cases/get-atoms/AtomForm.tsx, libs/frontend/domain/atom/src/use-cases/get-atoms/AtomsPrimarySidebar.tsx, libs/frontend/domain/atom/src/use-cases/get-atoms/AtomsTreeItem.tsx, libs/frontend/domain/atom/src/use-cases/get-atoms/AtomsTreeView.tsx, libs/frontend/domain/atom/src/use-cases/get-atoms/columns/types.ts, libs/frontend/domain/atom/src/use-cases/get-atoms/dataSource/atom-library.ts, libs/frontend/domain/atom/src/use-cases/get-atoms/index.ts, libs/frontend/domain/atom/src/use-cases/update-atom/UpdateAtomForm.tsx, libs/frontend/domain/atom/src/use-cases/update-atom/index.ts, libs/frontend/domain/type/src/use-cases/types/primary-sidebar/TypesPrimarySidebar.tsx, libs/frontend/presentation/codelab-ui/src/layout/hooks/index.ts, libs/frontend/presentation/codelab-ui/src/layout/hooks/useToolbarPagination.hook.tsx, libs/frontend/presentation/codelab-ui/src/layout/index.ts, libs/frontend/presentation/codelab-ui/src/views/CuiHeaderBreadcrumb/CuiHeaderBreadcrumb.tsx, libs/frontend/presentation/codelab-ui/src/views/CuiSidebarToolbar/CuiSidebarToolbarItem.tsx
https://github.com/codelab-app/platform/assets/74900868/aa81b0ec-92ce-4cd4-9932-09e04b94a9bf
Fixes #2715
=> refactor: use cui components for Atoms page

libs/frontend/abstract/core/src/domain/store/store.service.interface.ts, libs/frontend/domain/store/src/use-cases/actions/create-action/CreateActionForm.tsx, libs/frontend/domain/store/src/use-cases/actions/hooks/index.ts, libs/frontend/domain/store/src/use-cases/actions/hooks/use-action-schema.hook.ts, libs/frontend/domain/store/src/use-cases/actions/update-action/UpdateActionForm.tsx, libs/frontend/domain/type/src/use-cases/fields/create-field/CreateFieldForm.tsx, libs/frontend/domain/type/src/use-cases/fields/hooks/index.ts, libs/frontend/domain/type/src/use-cases/fields/hooks/use-field-schema.hook.ts, libs/frontend/domain/type/src/use-cases/fields/update-field/UpdateFieldForm.tsx, libs/frontend/presentation/view/components/form/hooks/uniformUtils.hook.ts
https://github.com/codelab-app/platform/assets/74900868/98de719a-6dfc-4ffd-8a3a-6c6a4d22281d
Fixes #2849
=> fix: add UI validation for duplicated field/action name

libs/frontend/domain/element/src/store/element.model.ts
Uploading Screen Recording 2023-08-02 at 19.26.42.mov…
Fixes #2869
=> fix: include style props in element create request

libs/frontend/abstract/core/src/domain/prop/prop.service.interface.ts, libs/frontend/domain/element/src/store/element.service.ts, libs/frontend/domain/element/src/use-cases/element/update-element/UpdateElementForm.tsx, libs/frontend/domain/prop/src/store/prop.service.ts
=> fix: props left over after atom is changed

apps/platform-e2e/src/e2e/store/child-mapper-api-actions-with-props.cy.ts, apps/platform-e2e/src/e2e/store/nested-api-actions.cy.ts, apps/platform-e2e/src/e2e/store/pre-render-api-action-and-set-state.cy.ts, examples/e-commerce/README.md, examples/e-commerce/server/sample-products.js, examples/e-commerce/server/server.js, examples/e-commerce/user-data.json, libs/backend/domain/app/src/repository/app.repo.ts, libs/backend/domain/element/src/repository/element.repo.old.ts, libs/backend/infra/adapter/cli/src/commands/import/import.service.ts, libs/frontend/abstract/core/src/constant.ts, libs/frontend/abstract/core/src/domain/render/action.runner.model.interface.ts, libs/frontend/abstract/core/src/domain/render/renderer.model.interface.ts, libs/frontend/domain/element/src/store/element.model.ts, libs/frontend/domain/renderer/src/action-runner.model.ts, libs/frontend/domain/renderer/src/element/element-wrapper.ts, libs/frontend/domain/renderer/src/renderer.model.ts, libs/frontend/domain/renderer/src/typedPropTransformers/action-type-transformer.ts, libs/frontend/domain/store/src/store/action.factory.ts, libs/frontend/presentation/container/src/pageHooks/useRenderedComponent.hook.ts
I've also added a user data that can be imported inside the `examples` folder so anyone can try the current e-commerce app.
This also includes some fixes around missing refs.
Testing nested actions - POST api call to add a product to the cart, then GET api call to fetch the updated cart, then updates the cart in the state which is used to show the count of products in the cart
https://github.com/codelab-app/platform/assets/27695022/fb395865-cec8-4c33-bc7e-0d2f143847d9
<br />
Modal for the cart using the child mapper + state sharing
https://github.com/codelab-app/platform/assets/27695022/cd39215d-c988-41aa-b355-d9df2ae61053
<br />
Using an API action on the child mapper component instances on the decrease/increase item logic in cart. In code, its something like this
```
const …
```
=> feat: fixes while trying to replicate "add to cart" functionality from e-commerce

libs/frontend/presentation/codelab-ui/src/layout/CuiNavigationBar/CuiNavigationBar.tsx
https://github.com/codelab-app/platform/assets/74900868/93413709-4ff4-4816-8e40-d317bbba2152
Fixes #2911
=> fix: don't render next/link on disabled menu items

libs/backend/application/app/src/use-case/import-components.ts
https://github.com/codelab-app/platform/assets/74900868/9efe1910-038c-4663-8cce-80765bdc2a3d
Fixes #2916
=> fix: update element childMapperComponent on import

libs/frontend/domain/renderer/src/test/setup/setup-test.ts, libs/frontend/domain/renderer/src/test/typed-prop-tranformers.spec.ts, libs/frontend/domain/type/src/interface-form/ui-properties/code-mirror-type-ui-properties.ts, yarn.lock
=> fix: builds fail

libs/frontend/domain/builder/src/sections/explorer-pane/ElementContextMenu.tsx
=> fix: add child on context menu not working

libs/frontend/domain/store/src/store/models/store.model.ts, libs/frontend/domain/store/src/store/store.service.ts
Do not re-create store and store.state when not necessary.
Uploading Screen Recording 2023-08-26 at 10.11.14.mov…
Fixes #2910
=> fix: persist store state on NextLink navigation

libs/backend/domain/store/src/model/store.model.ts, libs/frontend/abstract/core/src/domain/store/store.model.interface.ts, libs/frontend/domain/store/src/store/action.service.ts, libs/frontend/domain/store/src/store/models/api-action.model.ts, libs/frontend/domain/store/src/store/models/store.model.ts, libs/shared/abstract/core/src/store.dto.interface.ts
=> fix: build issue on master

libs/backend/infra/adapter/graphql/src/schema.ts, libs/backend/infra/adapter/serverless/src/app/app.module.ts
In order for `@unique` directive to work we need to call `assertIndexesAndConstraints` 
Fixes #2964
=> fix: restore assert indexes and constraints

apps/platform/pages/apps/[userName]/[appSlug]/components/[componentSlug]/builder.tsx, apps/platform/pages/apps/[userName]/[appSlug]/components/[componentSlug]/index.tsx, libs/frontend/abstract/types/src/page-type.ts, libs/frontend/domain/page/src/view/PageDetailHeader.tsx, libs/frontend/presentation/container/src/pageHooks/useRenderedComponent.hook.ts
=> feat: custom components preview

apps/platform-e2e/src/e2e/store/actions-inside-code-actions.cy.ts, examples/e-commerce-shopify/README.md, examples/e-commerce-shopify/user-data.json, libs/frontend/abstract/core/src/domain/element/element.model.interface.ts, libs/frontend/abstract/core/src/domain/store/store.model.interface.ts, libs/frontend/domain/element/src/store/element.model.ts, libs/frontend/domain/renderer/src/action-runner.model.ts, libs/frontend/domain/renderer/src/element/element-wrapper.ts, libs/frontend/domain/renderer/src/expresssion-transformer.service.ts, libs/frontend/domain/renderer/src/renderer.model.ts, libs/frontend/domain/store/src/store/models/store.model.ts, libs/frontend/domain/type/src/interface-form/ui-properties/primative-ui-properties.ts, libs/frontend/shared/utils/src/state-expressions.ts
I included a sample app that can be imported which uses the shopify storefront api
These are so far what I think while using shopify
- they have this structure for the graphql queries/mutations about edges, nodes, etc and so extracting the actual data from the response may not be neat
- Implementing the "add to cart" and "update cart" functionality is quite more complicated since we have to store more IDs to make the mutations work - https://shopify.dev/docs/api/storefront/2023-07/mutations/cartLinesUpdate. So theres a product id, then product variant id, then cart id, then cart line id.
Display of products from shopify -> cart logic -> checkout
https://github.com/codelab-app/platform/assets/27695022/1ce553f2-e8cc-4186-b232-260e137158e1
Fixes #2926 
Fixes #2961
=> fix: some fixes while trying to use shopify api

.circleci/config.yml, .circleci/config/commands/restore-workspace.yml, apps/platform-e2e/src/e2e/builder/builder.cy.ts, apps/platform-e2e/src/e2e/builder/child-mapper.cy.ts, apps/platform-e2e/src/e2e/builder/form.cy.ts, apps/platform-e2e/src/e2e/builder/state-sharing.cy.ts, apps/platform-e2e/src/e2e/component/component.cy.ts, apps/platform-e2e/src/e2e/store/child-mapper-api-actions-with-props.cy.ts, apps/platform-e2e/src/e2e/store/nested-api-actions.cy.ts, apps/platform-e2e/src/e2e/store/pre-render-api-action-and-set-state.cy.ts, apps/platform-e2e/src/support/builder/builder.command.ts, examples/e-commerce-shopify/user-data.json, libs/frontend/abstract/core/src/domain/element/element.model.interface.ts, libs/frontend/domain/app/src/store/app.service.spec.ts, libs/frontend/domain/component/src/store/component.model.ts, libs/frontend/domain/element/src/store/element.model.ts, libs/frontend/domain/renderer/src/component-runtime-props.model.ts, libs/frontend/presentation/view/components/form/hooks/uniformUtils.hook.ts
This PR fixes the e2e tests that got broken due to recent changes where we skip the CI and the e2e tests did not run. These are the tests that got fixed
- builder.cy.ts
- child-mapper.cy.ts
- form.cy.ts
- state-sharing.cy.ts
- component.cy.ts
- child-mapper-api-actions-with-props.cy.ts
- nested-api-actions.cy.ts
- pre-render-api-action-and-set-state.cy.ts
- css.cy.ts
All these e2e tests are passing locally. I am still figuring out why they are failing in the CI, and some are being skipped.
We can merge this now so that the build in master is fixed. I will make another PR under https://github.com/codelab-app/platform/issues/2651 for fixing the execution of the e2e tests step in CI
Fixes #2986
=> fix: e2e tests and some CI issues

libs/frontend/presentation/view/components/hoverOverlay/ClickOverlay.tsx
https://github.com/codelab-app/platform/assets/74900868/65a6fcba-b1e7-43a9-93af-15ad0302a410
Fixes #2993
=> fix: show overlay under element if no space above

libs/backend/application/tag/src/use-case/import-tags.command.service.ts
=> fix: tags import (isRoot does not exist in schema)

libs/frontend/domain/type/src/store/field.service.ts
https://github.com/codelab-app/platform/assets/51242349/eedc48d9-c162-40bc-bf5e-218a03961f82
Fixes #3003
=> fix: cannot set default value of field to falsy value

libs/frontend/abstract/core/src/domain/app/app-development.service.interface.ts, libs/frontend/abstract/core/src/domain/atom/atom.ref.ts, libs/frontend/domain/app/src/use-cases/app-development/app-development.service.ts
=> fix: hydrate store actions to avoid script errors

libs/frontend/domain/renderer/src/renderer.model.ts
Fix error coming from editor js when adding child element
Fixes #
=> fix: editor js error

apps/platform-e2e/src/e2e/admin.cy.ts, apps/platform-e2e/src/e2e/atoms.cy.ts, apps/platform-e2e/src/e2e/builder/builder.cy.ts, apps/platform-e2e/src/e2e/builder/child-mapper.cy.ts, apps/platform-e2e/src/e2e/builder/form.cy.ts, apps/platform-e2e/src/e2e/builder/in-app-routing.cy.ts, apps/platform-e2e/src/e2e/builder/state-sharing.cy.ts, apps/platform-e2e/src/e2e/component/component.cy.ts, apps/platform-e2e/src/e2e/component/convert-element-to-component.cy.ts, apps/platform-e2e/src/e2e/css.cy.ts, apps/platform-e2e/src/e2e/pages.cy.ts, apps/platform-e2e/src/e2e/providers-page.cy.ts, apps/platform-e2e/src/e2e/resources.cy.ts, apps/platform-e2e/src/e2e/store/actions-inside-code-actions.cy.ts, apps/platform-e2e/src/e2e/store/child-mapper-api-actions-with-props.cy.ts, apps/platform-e2e/src/e2e/store/nested-api-actions.cy.ts, apps/platform-e2e/src/e2e/store/pre-render-api-action-and-set-state.cy.ts, apps/platform-e2e/src/e2e/tag.cy.ts, apps/platform-e2e/src/e2e/types.cy.ts, apps/platform-e2e/src/support/builder/builder.command.ts, libs/frontend/domain/app/src/use-cases/app-development/useAppDevlopment.hook.ts, libs/frontend/domain/builder/src/sections/config-pane/ConfigPane-InspectorTabContainer/ConfigPaneInspectorTabContainer.tsx, libs/frontend/domain/builder/src/sections/explorer-pane/builder-tree/ElementTreeView.tsx, libs/frontend/domain/component/src/services/component.repo.ts, libs/frontend/domain/component/src/store/component.model.ts, libs/frontend/domain/component/src/store/component.service.ts, libs/frontend/domain/element/src/services/element.service.ts, libs/frontend/domain/element/src/store/element.model.ts, libs/frontend/domain/element/src/use-cases/element/update-element/UpdateElementForm.tsx, libs/frontend/domain/element/src/use-cases/element/update-element/update-element.schema.ts
Trying to fix the e2e tests, starting with the child-mapper spec
Fixes #
=> test: fixing the e2e tests in the dev branch

libs/frontend/domain/renderer/src/element/text-editor/TextRenderer.tsx, libs/frontend/domain/renderer/src/test/setup/setup-test.ts
This PR makes all the specs under the `frontend-domain-renderer` lib pass, basically when running `nx test frontend-domain-renderer`
Fixes #3050
=> fix: renderer specs

data/export-v2/admin/atoms/AntDesignMenu.json, data/export-v2/admin/atoms/AntDesignSelect.json, data/export-v2/admin/atoms/AntDesignSteps.json, libs/backend/application/atom/src/use-case/import-atom.command.service.ts, libs/backend/application/tag/src/use-case/import-tags.command.service.ts, libs/backend/application/type/src/use-case/import/import-api.command.service.ts
=> fix: import fixes to upsert by ID

libs/frontend/domain/element/src/services/element.domain.service.ts, libs/frontend/domain/element/src/store/element.model.ts, libs/frontend/domain/element/src/tests/element.domain.spec.ts
In this PR we add test cases for moving elements.
Fixes #
=> feat: add test cases for moving element

libs/backend/application/admin/src/use-case/import/import-admin-data.command.service.ts, libs/backend/application/admin/src/use-case/seed-framework/import-export.i.spec.ts, libs/backend/application/shared/src/data/read-admin-data.service.ts, libs/backend/shared/util/src/file/resolve-workspace-root.ts, libs/frontend/application/app/src/use-cases/app-development/app-development.endpoints.graphql.gen.ts, libs/frontend/application/renderer/src/test/typed-prop-tranformers.spec.ts
=> fix: lint, unit and integration jobs on ci

apps/platform/pages/_app.tsx, libs/frontend/abstract/domain/src/element/element.model.interface.ts, libs/frontend/application/builder/src/sections/overlay-toolbar/BuilderClickOverlay.tsx, libs/frontend/application/element/src/css-editor/ElementCssEditor.tsx, libs/frontend/application/element/src/css-editor/components/ValuePicker.tsx, libs/frontend/application/element/src/css-editor/inherited-styles/InheritedStyles.tsx, libs/frontend/application/element/src/css-editor/style.hook.ts, libs/frontend/application/element/src/css-editor/tailwind-class-editor/TailwindClassEditor.tsx, libs/frontend/application/element/src/services/clone-element.service.ts, libs/frontend/application/renderer/src/renderPipes/atom-render-pipe.ts, libs/frontend/domain/element/src/store/element-style.model.ts, libs/frontend/domain/element/src/store/element.model.ts
=> refactor: move element.styles to separate model

libs/backend/application/admin/src/use-case/seed-framework/import-export.i.spec.ts
=> refactor: simplify files content comparison

libs/backend/domain/store/src/model/store.model.ts, libs/frontend/abstract/application/src/renderer/renderer.model.interface.ts, libs/frontend/abstract/application/src/renderer/runtime-container-node/runtime-container-node.dto.ts, libs/frontend/abstract/application/src/renderer/runtime-container-node/runtime-container-node.model.interface.ts, libs/frontend/abstract/application/src/renderer/runtime-container-node/runtime-container-node.ref.ts, libs/frontend/abstract/application/src/renderer/runtime-element/runtime-element.model.interface.ts, libs/frontend/abstract/application/src/renderer/runtime-element/runtime-element.ref.ts, libs/frontend/abstract/application/src/renderer/runtime.model.interface.ts, libs/frontend/abstract/domain/src/atom/atom.ref.ts, libs/frontend/application/app/src/use-cases/app-development/app-development.endpoints.graphql, libs/frontend/application/builder/src/sections/explorer-pane/builder-tree/ElementTreeItemTitle.tsx, libs/frontend/application/element/src/use-cases/element/update-element-props/UpdateElementPropsForm.tsx, libs/frontend/application/renderer/src/renderer.application.service.ts, libs/frontend/application/renderer/src/renderer.model.ts, libs/frontend/application/renderer/src/runtime-action.model.ts, libs/frontend/application/renderer/src/runtime-container-node.model.ts, libs/frontend/application/renderer/src/runtime-store.model.ts, libs/frontend/infra/mobx/src/create-root-store.ts, libs/frontend/presentation/container/src/pageHooks/utils.ts
=> WIP: restore basic rendering

libs/frontend/abstract/application/src/renderer/renderer.model.interface.ts, libs/frontend/abstract/application/src/renderer/renderer.service.interface.ts, libs/frontend/abstract/application/src/renderer/runtime-container-node/runtime-container-node.model.interface.ts, libs/frontend/abstract/application/src/renderer/runtime-element/runtime-element.model.interface.ts, libs/frontend/application/app/src/use-cases/app-development/app-development.endpoints.graphql, libs/frontend/application/app/src/use-cases/app-development/app-development.endpoints.graphql.gen.ts, libs/frontend/application/app/src/use-cases/app-development/app-development.service.ts, libs/frontend/application/app/src/use-cases/app-development/useAppDevlopment.hook.ts, libs/frontend/application/builder/src/sections/config-pane/PropsInspectorTab.tsx, libs/frontend/application/component/src/services/component.application.service.ts, libs/frontend/application/element/src/services/clone-element.service.ts, libs/frontend/application/element/src/services/element.service.ts, libs/frontend/application/renderer/src/renderPipes/child-mapper-render-pipe.ts, libs/frontend/application/renderer/src/renderPipes/children-render-pipe.ts, libs/frontend/application/renderer/src/renderPipes/component-instance-children-render-pipe.ts, libs/frontend/application/renderer/src/renderPipes/page-render-pipe.ts, libs/frontend/application/renderer/src/renderPipes/pre-render-pipe.ts, libs/frontend/application/renderer/src/renderPipes/render-pipe.factory.ts, libs/frontend/application/renderer/src/renderer.application.service.ts, libs/frontend/application/renderer/src/renderer.model.ts, libs/frontend/application/renderer/src/runtime-component-prop.model.ts, libs/frontend/application/renderer/src/runtime-container-node.model.ts, libs/frontend/application/renderer/src/runtime-element.model.ts, libs/frontend/domain/element/src/store/element.model.ts, libs/frontend/domain/prop/src/store/prop.model.ts, libs/shared/abstract/codegen/src/types.api.graphql.gen.ts
- Simplify `renderChildren` by moving some parts to `renderPipe`
- Fix `convertElementToComponent` use case
- Fix `deleteElement` use case
- Load and Hydrate all components in `app.development` use case  
- Fix Props Inspector 
Fixes #
=> wip: simplify runtime element

libs/backend/abstract/codegen/src/ogm-types.gen.ts, libs/backend/infra/adapter/neo4j/src/schema/type/type.schema.ts, libs/frontend/abstract/domain/src/type/fragments/union-type.fragment.graphql.gen.ts, libs/frontend/application/type/src/interface-form/fields/select-union-type-value/SelectUnionTypeValue.tsx, libs/frontend/application/type/src/interface-form/tests/InterfaceForm.test.tsx, libs/frontend/application/type/src/interface-form/tests/schema.data.ts, libs/frontend/application/type/src/interface-form/tests/schema.data.util.ts, libs/frontend/application/type/src/interface-form/tests/setup-store.ts, libs/frontend/application/type/src/interface-form/tests/type-tree-to-json-schema.spec.ts, libs/frontend/application/type/src/interface-form/type-schema.factory.ts, libs/shared/abstract/codegen/src/types.api.graphql.gen.ts, schema.graphql, scripts/jest/setupFiles.js
=> test: type transformer specs

apps/platform-api/tsconfig.json, apps/platform/pages/api/auth/[...auth0].ts, libs/backend/application/admin/src/use-case/seed-data/seeder.application.service.ts
- fix compilation error
- remove redundant request to `setup-dev` endpoint
Fixes #
=> fix: compilation error

apps/platform/pages/_document.tsx, apps/platform/pages/admin/index.tsx, apps/platform/pages/atoms/index.tsx, apps/platform/pages/index.tsx, libs/backend/application/admin/src/use-case/scrape/scrape-ant-design-data.ts, libs/backend/application/admin/src/use-case/scrape/scrape-html-data.ts
=> fix: revert experimental changes

apps/platform/pages/_app.tsx
=> fix: builder layout issue

libs/backend/abstract/codegen/src/ogm-types.gen.ts, libs/backend/infra/adapter/neo4j/src/cypher/element/getElementDependantTypes.cypher, libs/backend/infra/adapter/neo4j/src/cypher/element/getElementTypes.cypher, libs/backend/infra/adapter/neo4j/src/cypher/element/index.ts, libs/backend/infra/adapter/neo4j/src/resolver/ogm-resolver/element/element.resolver.provider.ts, libs/backend/infra/adapter/neo4j/src/resolver/ogm-resolver/element/tests/element.resolver.spec.ts, libs/backend/infra/adapter/neo4j/src/resolver/ogm-resolver/element/util/get-dependant-types.ts, libs/backend/infra/adapter/neo4j/src/resolver/pure-resolver/type/type.resolver.ts, libs/backend/infra/adapter/neo4j/src/schema/model/element.schema.ts, libs/backend/infra/adapter/neo4j/src/selectionSet/type-selection-set.ts, libs/frontend/abstract/domain/src/element/element.fragment.graphql, libs/frontend/abstract/domain/src/element/element.fragment.graphql.gen.ts, libs/frontend/application/app/src/use-cases/app-development/app-development.endpoints.graphql, libs/frontend/application/app/src/use-cases/app-development/app-development.endpoints.graphql.gen.ts, libs/frontend/application/app/src/use-cases/app-development/app-development.service.ts, libs/frontend/application/app/src/use-cases/app-development/useAppDevlopment.hook.ts, libs/shared/abstract/codegen/src/types.api.graphql.gen.ts, schema.graphql
Custom resolver for getting all types that an element depends on.
Fixes #3139
Closes #3078
=> 3139 element types resolver

libs/frontend/infra/mobx/src/root.store.ts
=> 3159 services not initialized

apps/platform/pages/_document.tsx, data/export-v3/admin/atoms/AntDesignMenu.json, data/export-v3/admin/atoms/AntDesignSelect.json, data/export-v3/admin/atoms/AntDesignSteps.json, data/export-v3/admin/components/GoogleFonts.json, libs/backend/application/shared/src/use-cases/use-case.ts, libs/frontend/abstract/domain/src/component/component-development.fragment.graphql, libs/frontend/abstract/domain/src/component/component-development.fragment.graphql.gen.ts, libs/frontend/abstract/domain/src/element/element.fragment.graphql, libs/frontend/abstract/domain/src/element/element.fragment.graphql.gen.ts, libs/frontend/abstract/domain/src/page/page.fragment.graphql, libs/frontend/abstract/domain/src/page/page.fragment.graphql.gen.ts, libs/frontend/application/app/src/use-cases/app-development/app-development.endpoints.graphql, libs/frontend/application/app/src/use-cases/app-development/app-development.endpoints.graphql.gen.ts, libs/frontend/application/app/src/use-cases/app-production/app-production.endpoints.graphql.gen.ts, libs/shared/abstract/codegen/src/types.api.graphql.gen.ts
=> fix: lint, codegen and Import/export specs

libs/frontend/application/dnd/jest.config.ts, libs/frontend/application/dnd/src/DropIndicator.tsx, libs/frontend/application/dnd/src/DropOverlay.tsx, libs/frontend/application/dnd/src/MakeChildrenDraggable.tsx, libs/frontend/application/dnd/src/MakeChildrenDroppable.tsx, libs/frontend/application/dnd/src/tests/Dnd.test.tsx, libs/frontend/application/dnd/src/tests/MakeElementTree.tsx, libs/frontend/application/dnd/src/tests/TestDndContext.tsx, libs/frontend/application/dnd/src/tests/test-data.ts
=> test: add unit tests for dnd ui

scripts/digitalocean/platform/build.sh, scripts/digitalocean/platform/run.sh
=> refactor: migrate platform to DigitalOcean hosting

libs/backend/infra/adapter/neo4j/src/selectionSet/element-selection-set.ts
=> fix: app does not open when element of type component is used

apps/platform-e2e/src/e2e/css.cy.ts, libs/frontend/application/element/src/css-editor/components/SegmentedSelect.tsx
Add `data-test-id` for important DOM content nodes in order to reliably find it in e2e tests and not risking to select something else after each refactoring
Part of #3171
=> fix: css.cy e2e test

libs/frontend/application/renderer/src/runtime-element.model.ts
Re-render element if new children was added
Before:
https://github.com/codelab-app/platform/assets/74900868/2d60aec3-1b20-4c2f-bc36-7aed3ebb87cf
After:
https://github.com/codelab-app/platform/assets/74900868/ce0232f5-80cd-4bf2-8d56-7470770aeec8
Part of #3171
=> fix: newly added children are not rendered until refresh

libs/frontend/application/app/src/services/app.service.ts
Before:
https://github.com/codelab-app/platform/assets/74900868/470eb86c-9c81-4150-8e1e-2c30758bba0b
After:
https://github.com/codelab-app/platform/assets/74900868/ab4f27b9-8678-4276-b0fa-c8cff0f36868
Part of #3171
=> fix: impossible to delete apps

libs/frontend/application/element/src/css-editor/border/BorderRadiusEditor.tsx, libs/frontend/application/element/src/css-editor/components/ValuePicker.tsx, libs/frontend/application/element/src/css-editor/components/ValueSlider.tsx, libs/frontend/application/element/src/css-editor/css.ts, libs/frontend/application/element/src/css-editor/spacing/SpacingPopover.tsx, libs/frontend/application/element/src/css-editor/style.hook.ts
=> fix: minor issues in styles editor

libs/frontend/application/atom/src/services/atom.service.ts
=> fix: interfaceType fields not loaded

.env.example, .env.test.example, libs/backend/infra/adapter/codelab/src/graphql/endpoint.config.ts, libs/shared/config/src/env/services/endpoint.ts, terraform/environments/ci/module-circleci.tf, terraform/environments/prod/module-do-codelab.tf, terraform/environments/shared/vars-platform-api.tf, terraform/modules/circleci/environment-resource.tf, terraform/modules/digitalocean-codelab/platform-api.tf, terraform/modules/digitalocean-codelab/platform-web.tf, terraform/modules/digitalocean-codelab/vars.tf
=> refactor: platform-api ENV vars

libs/frontend/application/renderer/src/runtime-store.model.ts
=> fix: new state variables are not defined

libs/frontend/application/builder/src/sections/overlay-toolbar/BuilderClickOverlay.tsx
=> fix: cannot delete elements

libs/frontend/abstract/application/src/renderer/runtime-prop/runtime-prop.model.interface.ts, libs/frontend/application/element/src/use-cases/element/update-element-props/UpdateElementPropsForm.tsx, libs/frontend/application/renderer/src/runtime-component-prop.model.ts, libs/frontend/application/renderer/src/runtime-element-prop.model.ts, libs/frontend/application/renderer/src/runtime-store.model.ts, libs/frontend/application/renderer/src/test/runtime-element-props.spec.ts, libs/frontend/application/renderer/src/test/setup/setup.ts, libs/frontend/application/renderer/src/typedPropTransformers/action-type-transformer.ts
=> fix: pass renderer specs

libs/frontend/application/renderer/src/element/StyledComponent.tsx
=> fix: component builder crashes

apps/platform-api/src/graphql/graphql.module.ts, libs/backend/infra/adapter/neo4j/src/schema/model/app.schema.ts, libs/backend/infra/adapter/neo4j/src/schema/model/atom.schema.ts, libs/backend/infra/adapter/neo4j/src/schema/model/component.schema.ts, libs/backend/infra/adapter/neo4j/src/schema/model/page.schema.ts, libs/backend/infra/adapter/neo4j/src/schema/model/user.schema.ts, libs/backend/infra/adapter/neo4j/src/schema/type/type.schema.ts
Fix authentication in neo4j schema level. As the result:
- not authenticated users would not be able to perform some of the graphql queries
- basic role-based access control is implemented
https://github.com/codelab-app/platform/assets/74900868/407ef077-201c-42eb-969f-ec9230bc583f
Part of #3238
=> refactor: enable authentication in schema

apps/platform-e2e/src/e2e/builder/child-mapper.cy.ts, apps/platform-e2e/src/e2e/builder/components.data.ts, libs/backend/application/component/src/component.application.module.ts, libs/backend/application/store/src/store.application.module.ts, libs/frontend/application/element/src/use-cases/element/update-element/update-element.schema.ts, libs/frontend/application/renderer/src/runtime-container-node.model.ts, libs/frontend/application/renderer/src/runtime-element.model.ts, libs/frontend/presentation/view/components/form/schema/id.schema.ts
=> chore: child-mapper e2e refactor

apps/platform-e2e/src/e2e/store/nested-api-actions.cy.ts, apps/platform-e2e/src/e2e/store/pre-render-api-action-and-set-state.cy.ts, apps/platform-e2e/src/support/commands/builder/builder.command.ts, libs/backend/application/redirect/src/redirect.i.spec.ts, libs/frontend/application/redirect/src/services/redirect.service.ts, libs/frontend/application/store/src/use-cases/actions/create-action/CreateActionForm.tsx, libs/frontend/application/type/src/interface-form/fields/select-resource/SelectResource.tsx, libs/frontend/domain/action/src/action.domain.service.ts, libs/frontend/domain/action/src/store/action.factory.ts, libs/frontend/domain/component/src/component.domain.service.ts, libs/frontend/domain/store/src/store.domain.service.ts, libs/frontend/domain/type/src/field.domain.service.ts, libs/frontend/domain/type/src/models/array-type.model.ts, libs/frontend/domain/type/src/models/code-mirror-type.model.ts, libs/frontend/domain/type/src/models/element-type.model.ts, libs/frontend/domain/type/src/models/enum-type.model.ts, libs/frontend/domain/type/src/models/interface-type.model.ts, libs/frontend/domain/type/src/models/primitive-type.model.ts, libs/frontend/domain/type/src/models/type.factory.ts, libs/frontend/domain/type/src/models/union-type.model.ts, libs/frontend/presentation/view/components/form/schema/ref.schema.ts
- fixed some of the actions specs
- refactored tests to seed Resource though API rather than UI
- fixed lint errors (mostly renaming `somethingDTO` to `somethingDto`
Part of #3249
=> fix: lint errors and action e2e specs

libs/frontend/presentation/view/components/form/components/Form.tsx
=> fix: interfaceForm unit test error

apps/platform-e2e/src/e2e/production.cy.ts, apps/platform-e2e/src/support/e2e.ts, libs/frontend/abstract/application/src/app/app.service.interface.ts, libs/frontend/application/app/src/services/app.service.ts, libs/frontend/application/app/src/use-cases/app-development/app-development.endpoints.graphql, libs/frontend/application/app/src/use-cases/app-development/app-development.endpoints.graphql.gen.ts, libs/frontend/application/app/src/use-cases/build-app/BuildAppModal.tsx, libs/frontend/application/page/src/use-cases/get-pages/PageTreeItem.tsx, libs/frontend/application/renderer/src/runtime-element-prop.model.ts, libs/frontend/application/renderer/src/runtime-store.model.ts, libs/frontend/domain/domain/src/static-regeneration.ts, libs/shared/abstract/codegen/src/types.api.graphql.gen.ts, libs/shared/config/src/env/services/endpoint.ts, terraform/modules/digitalocean-codelab/platform-api.tf, terraform/modules/digitalocean-codelab/platform-web.tf, terraform/modules/digitalocean-codelab/platform-websites.tf
- Added Cypress test that checks if user app is available in production
- Fix script error in production websites when URLs were concatenated incorrectly
- Refactored app/pages build functionality to not duplicate code
- Fixed graphql query that used duplicated elements
- Improved error/success handling when app/pages is build for production
Fixes #3287 
Also part of #3063
=> feat: production websites fixes and enhancements

apps/platform-e2e/src/e2e/builder/child-mapper.cy.ts, apps/platform-e2e/src/e2e/builder/child-mapper.setup.ts, apps/platform-e2e/src/e2e/builder/in-app-routing.cy.ts, apps/platform-e2e/src/e2e/builder/in-app-routing.setup.ts, apps/platform-e2e/src/e2e/component/convert-element-to-component.cy.ts, apps/platform-e2e/src/e2e/component/convert-element-to-component.setup.ts, apps/platform-e2e/src/e2e/store/child-mapper-api-actions-with-props.cy.ts, apps/platform-e2e/src/e2e/store/child-mapper-api-actions-with-props.setup.ts, apps/platform-e2e/src/e2e/store/nested-api-actions.cy.ts, apps/platform-e2e/src/e2e/store/nested-api-actions.data.ts, apps/platform-e2e/src/e2e/store/nested-api-actions.setup.ts, apps/platform-e2e/src/e2e/store/pre-post-api-action.cy.ts
- refactors the nested-api-actions spec to seed via API
- creation of page state is still done via UI
- added test case for error action
- separate setupTest functions on the other spec files
Relates #3249
=> chore: refactor nested-api-actions spec

apps/platform-e2e/src/e2e/store/actions-inside-code-actions.cy.ts, apps/platform-e2e/src/e2e/store/actions-inside-code-actions.data.ts, apps/platform-e2e/src/e2e/store/actions-inside-code-actions.setup.ts
This is for refactoring the `actions-inside-code-actions` spec to use the APIs for seeding. The spec covers the test for calling a code action and api action inside a code action with arguments.
Relates #3249
=> chore: refactor actions-inside-code-actions spec

libs/backend/application/component/src/component.application.controller.ts, libs/frontend/abstract/application/src/component/component.application.service.interface.ts, libs/frontend/abstract/types/src/model/model.data.ts, libs/frontend/application/builder/src/sections/explorer-pane/ComponentsPrimarySidebar.tsx, libs/frontend/application/builder/src/sections/explorer-pane/tab-contents/ComponentItem.tsx, libs/frontend/application/builder/src/sections/explorer-pane/tab-contents/ComponentList.tsx, libs/frontend/application/builder/src/sections/explorer-pane/tab-contents/CustomComponents.tsx, libs/frontend/application/component/src/services/component.application.service.ts, libs/frontend/application/component/src/use-cases/import-component/ImportComponentDialog.tsx, libs/frontend/application/component/src/use-cases/import-component/index.ts, libs/frontend/application/component/src/use-cases/index.ts
- Restore the ability to import and export custom components from builder
[Screencast from 02 أفريل, 2024 CET 03:36:58 ص.webm](https://github.com/codelab-app/platform/assets/33001357/602ca1c3-0971-4c04-ba62-9e6802eb82b4)
Fixes #3307
=> feat: import export component

libs/frontend/abstract/application/src/admin/admin.service.interface.ts, libs/frontend/abstract/application/src/app/app.service.interface.ts, libs/frontend/application/admin/src/admin.service.ts, libs/frontend/application/app/src/services/app.service.ts, libs/frontend/application/app/src/use-cases/get-apps/ItemDropdown.tsx, libs/frontend/application/app/src/use-cases/import-app/ImportAppDialog.tsx
=> refactor: move import export to app service

libs/frontend/application/renderer/src/wrappers/TextEditorWrapper.tsx
=> fix: text editor value persistance

libs/frontend/application/element/src/use-cases/element/update-element/UpdateElementForm.tsx, libs/frontend/application/renderer/src/model/runtime-element.model.ts
=> fix: remove child mapper for render type component

libs/frontend/application/type/src/graphql/create-type.endpoints.graphql, libs/frontend/application/type/src/graphql/create-type.endpoints.graphql.gen.ts, libs/frontend/application/type/src/graphql/type.api.ts, libs/shared/abstract/codegen/src/types.api.graphql.gen.ts
=> fix: typo in create rich text types endpoint

data/export-v3/admin/atoms/AntDesignLayoutSider.json, data/export-v3/admin/atoms/AntDesignMenu.json, libs/frontend/shared/utils/src/dynamic-loader.ts
https://github.com/codelab-app/platform/assets/74900868/cec4f688-3bcf-4d33-9834-c05558f0232d
Fixes #2956
=> fix: theme prop was lost for some components

apps/e2e/src/e2e/builder/state-sharing.cy.ts
=> fix: state-sharing.cy e2e spec

libs/frontend/application/component/src/use-cases/component-list/component-list.use-case.ts, libs/frontend/application/component/src/use-cases/import-component/ImportComponentDialog.tsx, libs/frontend/application/component/src/use-cases/import-component/import-component-data.use-case.ts
=> fix: component create and import workflows

libs/frontend/application/prop/src/services/prop.service.ts
Fixed the following problem: 
https://github.com/user-attachments/assets/948e25b6-70bd-4065-a304-2b559628b2db
Fixes #3694
=> fix: app being unmounted recursively

data/export-v3/admin/atoms/AntDesignAffix.json, data/export-v3/admin/atoms/AntDesignBackTop.json, data/export-v3/admin/atoms/AntDesignCard.json, examples/atoms-demo-app/ant-design-atoms-demo.json, libs/frontend/application/element/src/use-cases/create-element/CreateElementForm.tsx, libs/frontend/application/element/src/use-cases/create-element/CreateElementPopover.tsx, libs/frontend/application/element/src/use-cases/create-element/create-element.schema.ts, libs/frontend/application/prop/src/services/prop.service.ts, libs/frontend/application/renderer/src/components/StyledComponent.tsx, libs/frontend/application/renderer/src/store/runtime-element.model.ts
=> fix: atoms apis, demo app updated and platform fixes

libs/frontend/application/element/src/services/element.service.ts
=> fix: script error on attempt to change renderType to component

libs/frontend/abstract/application/src/builder/builder.service.interface.ts, libs/frontend/application/builder/src/sections/explorer-pane/builder-tree/ElementTreeView.tsx, libs/frontend/presentation/container/src/providers/BuilderProvider.tsx
=> fix: reset selected element when switching pages

data/export-v3/admin/atoms/AntDesignCascader.json, data/export-v3/admin/atoms/AntDesignCheckbox.json, data/export-v3/admin/atoms/AntDesignCheckboxGroup.json, examples/atoms-demo-app/ant-design-atoms-demo.json, libs/backend/application/type/src/use-case/api/export-api.command.service.ts, libs/shared/domain/module/field/src/field.mapper.ts, libs/shared/utils/src/sort/index.ts, libs/shared/utils/src/sort/sort-fields-for-export.ts
Also fixed fields ordering: exporting fields in correct order depending on prevSibling/nextSibling). This is required to be able to import fields in a single run with correct connectivity
Fixes #
=> fix: Checkbox and CheckboxGroup atoms and create demo

data/export-v3/admin/atoms/AntDesignCollapse.json, data/export-v3/admin/atoms/AntDesignConfigProvider.json, examples/atoms-demo-app/ant-design-atoms-demo.json, libs/frontend/application/store/src/use-cases/create-action/create-action.schema.ts
=> fix: atoms apis and CreateAction form

libs/frontend/presentation/components/codemirror/src/CodeMirrorInput.tsx, libs/frontend/presentation/components/form/src/fields/CodeMirrorGraphqlField.tsx, package.json, pnpm-lock.yaml
=> fix: autocompletion did not work for expressions
