codelab-app/platform

libs/components/ui/src/components/form/Form.types.ts
libs/components/ui/src/components/form/data/Form-4--node.data.ts
libs/components/ui/src/components/select/Select.spec.tsx
libs/shared/interface/props/src/index.ts
libs/shared/interface/props/src/props.ts
libs/tools/eslint-config-codelab/.eslintrc.base.yml

Described in #118 
Described in #118 
Fixes #
#118

fix(libs): #118 fix Lib Form(Form.types.ts) wrong type definition

---

apps/web/src/node/ButtonGroup.tsx
apps/web/src/node/ModalForm.tsx
libs/components/ui/src/components/table/Table.tsx
libs/core/renderer/src/TreeDom.tsx

Even if you specify the type in generic in TreeDom.render, it will not validate the resulted React component props for validness 
- Static analysis can validate React component props
- Autocompletion work 
Fixes #

refactor(libs-core-renderer): add the ability to specify the returned type for TreeDom renderer

---

documentation/getting-started/4-getting-started.md

fix mistype. 
'env.dev' -> '.env'
Fixes #

docs: update 4-getting-started.md

---

apps/web/src/graph/updateVertex/UpdateVertexForm.tsx
libs/alpha/ui/antd/src/components/rgl/RGL.tsx
libs/frontend/src/renderer/RenderComponents.tsx
libs/frontend/src/renderer/elementFactory.tsx
package.json
yarn.lock

Currently, the react-grid-layout library re-renders the layout
only if it detects a change in the key of the child, and doesn't care about the data-grid property
So, a workaround is to incorporate the data-grid property into the key to make sure we rerender it
There seems to be a fix [here](https://github.com/STRML/react-grid-layout/issues/718),  but it doesn't appear in the main codebase
fixes #557

557 re render components

---

data/customComponents/Query.csv
libs/frontend/shared/src/components/query/Query.tsx

Fixes issues with the Query component
Note - after this, query props needs to get pass down as object from the lambda, e.g.: 
```
return {
data: [..]
}
```
instead of:
`return [..data]`

0 query fix

---

libs/modules/app-api/src/app.resolver.ts
libs/modules/app-api/src/use-cases/delete-app/test/delete-app.i.spec.ts
libs/modules/app-api/src/use-cases/get-app/get-app.service.ts
libs/modules/atom-api/src/infrastructure/atom.resolver.ts
libs/modules/atom-api/src/use-cases/delete-atom/test/delete-atom.i.spec.ts
libs/modules/atom-api/src/use-cases/get-atom/get-atom.service.ts
libs/modules/element-api/src/component/component.resolver.ts
libs/modules/element-api/src/component/use-cases/get-component/get-component.service.ts
libs/modules/element-api/src/element.resolver.ts
libs/modules/element-api/src/use-cases/delete-element/test/delete-element.i.spec.ts
libs/modules/element-api/src/use-cases/get-element-graph/get-element-graph.service.ts
libs/modules/lambda-api/src/use-cases/delete-lambda/test/delete-lambda.i.spec.ts
libs/modules/page-api/src/page.resolver.ts
libs/modules/page-api/src/use-cases/get-page/get-page.service.ts
libs/modules/type-api/src/use-cases/type/delete-type/test/delete-type.i.spec.ts
schema.api.graphql

Before some getX resolvers threw NotFound error (i.e. used getOneOrThrow from DgraphRepository)
This was inconsistent 
Now all getX resolvers return null if not found

chore: remove throwing on not found in getModel queries

---

libs/frontend/model/domain/src/element-tree/ElementGraphTreeAdapter.ts
libs/frontend/model/infra/apollo/src/links/graphqlApiLink.ts
libs/frontend/modules/element/src/css-editor/ElementCssEditor.tsx
libs/frontend/presenter/container/src/providers/PageProvider.tsx
libs/frontend/view/components/mapper/Mapper.tsx
libs/frontend/view/components/propMapper/PropMapper.tsx

- Fixed getComponentById issue, which prevented Mapper to work properly
- Removed some console.logs
- Fixed css editor not saving if you close it too quickly

0 small fixes

---

.husky/pre-commit
.husky/pre-push
libs/backend/modules/atom/src/domain/data/Divider.json
libs/backend/modules/atom/src/domain/data/GridCol.json
libs/backend/modules/atom/src/domain/data/GridRow.json
libs/backend/modules/atom/src/domain/data/Layout.json
libs/backend/modules/atom/src/domain/data/LayoutSider.json
libs/backend/modules/atom/src/domain/data/Space.json

add encoded props for layout components
Fixes #1094

feat: add encoded props for layout components

---

libs/backend/modules/element/src/use-cases/element/get-element/tests/get-element.api.graphql
libs/backend/modules/element/src/use-cases/element/get-element/tests/get-element.api.graphql.gen.ts
libs/backend/modules/element/src/use-cases/element/hooks/add-hook-to-element/config-inputs/recoil-state-hook-config.input.ts
libs/backend/modules/element/src/use-cases/element/hooks/add-hook-to-element/tests/add-hook-to-element.i.spec.ts
libs/backend/modules/hook/src/application/hook-config/recoil-state-hook-config.model.ts
libs/backend/modules/hook/src/domain/hook-config/recoil-state-hook-config.schema.ts
libs/frontend/modules/builder/src/meta-pane/MetaPaneBuilderComponent.tsx
libs/frontend/modules/builder/src/meta-pane/MetaPaneBuilderPage.tsx
libs/frontend/modules/builder/src/renderer/Renderer.tsx
libs/frontend/modules/builder/src/renderer/handlers/renderElement.tsx
libs/frontend/modules/builder/src/renderer/hooks/HookElementWrapper.tsx
libs/frontend/modules/builder/src/renderer/hooks/HookHandler.ts
libs/frontend/modules/builder/src/renderer/hooks/handlers/useGraphqlMutationHook.ts
libs/frontend/modules/builder/src/renderer/hooks/handlers/useGraphqlQueryHook.ts
libs/frontend/modules/builder/src/renderer/hooks/handlers/useRecoilStateHook.ts
libs/frontend/modules/builder/src/renderer/hooks/useHookFactory.ts
libs/frontend/modules/builder/src/renderer/reactComponentFactory.tsx
libs/frontend/modules/element/src/graphql/HookConfig.fragment.graphql
libs/frontend/modules/element/src/graphql/HookConfig.fragment.graphql.gen.ts
libs/frontend/modules/element/src/graphql/HookConfig.fragment.web.graphql.gen.ts
libs/frontend/modules/element/src/use-cases/hooks/add-hook-to-element/AddHookToElementForm.tsx
libs/frontend/modules/element/src/use-cases/hooks/add-hook-to-element/addHookToElementSchema.ts
libs/frontend/modules/element/src/use-cases/update-element/UpdateElementForm.tsx
libs/shared/abstract/core/src/enums/hooks/index.ts
libs/shared/abstract/core/src/enums/hooks/persistence-type.ts
libs/shared/codegen/graphql/src/types.api.graphql.gen.ts
schema.api.graphql

- Fixes #1119 
- Fixed builder refetch bug - when assigning component to an element it didn't update 
- Added ability to persist recoil state hook data in local storage or session storage, use the persisted field when adding a RecoilState hook to an element
- Added ability to pass variables to GraphqlQuery and GraphqlMutation hooks. All element props are passed as variables, apollo seems to manage it well since it filters out unnecessary variables (i.e. ones not defined in the query/mutation block with $)
Note: the hook pipe is before propTransformationJsPipe and loopingRenderPipe, so it won't receive transformed or looped props. Only persisted props and props from parent mappings will be used as variables. That means we might need to lift some props up in order to use them as graphql …

feat: persisted recoil state, graphql variables and bug fixes

---

codegen.yml
libs/tools/rtk-query/.babelrc
libs/tools/rtk-query/.eslintrc.json
libs/tools/rtk-query/README.md
libs/tools/rtk-query/jest.config.js
libs/tools/rtk-query/package.json
libs/tools/rtk-query/src/config.ts
libs/tools/rtk-query/src/index.ts
libs/tools/rtk-query/src/visitor.ts
libs/tools/rtk-query/tsconfig.json
libs/tools/rtk-query/tsconfig.lib.json
libs/tools/rtk-query/tsconfig.spec.json
nx.json
package.json
scripts/postinstall.sh
tsconfig.base.json
workspace.json
yarn.lock

This plugins extends the official one https://www.graphql-code-generator.com/docs/plugins/typescript-rtk-query with the following :
- Ability to use `gqlImport` to use typed queries instead of pure strings
- Escape empty endpoints files such fragments (doesn't inject api code unless there is a valid endpoints)  
Fixes #

1151 integrate redux (create codegen plugin)

---

libs/backend/infra/src/modules/dgraph/dgraph.schema.ts
libs/backend/modules/element/src/application/element.validator.ts
libs/backend/modules/element/src/use-cases/element/delete-element/delete-element.service.ts
libs/backend/modules/element/src/use-cases/element/get-element-graph/get-element-graph.service.ts
libs/frontend/modules/builder/src/main-pane/useExpandedNodes.tsx
libs/frontend/modules/element/src/use-cases/element/elementEndpoints.ts
libs/shared/core/src/tree/tree.service.ts

- Fixed issue where it prevented deleting any elements with error message (Element is referenced)
- Restricted deleting only referenced components instead
- Fixed path finding bug
- Fixed element tree not updating after deletion
- Fixed issue related to not deleting parent-children relationship when deleting elements

fix: delete element issue

---

libs/frontend/modules/atom/src/use-cases/create-atom/CreateAtomButton.tsx
libs/frontend/modules/atom/src/use-cases/export-atoms/ExportAtomsButton.tsx
libs/frontend/modules/lambda/src/use-cases/create-lambda/CreateLambdaButton.tsx

- Create atom, lambda button don't work
- Export atom button requires 2 clicks to export atom
- Fix all behaviors above

fix(apps): #1247 fix buttons: Create atom,lambda,Export atom

---

libs/frontend/modules/element/src/store/api.utils.ts

Apparently Neo4j is rejecting the update query because it is asking to add another component for INSTANCE_OF_COMPONENT of an element, which is not allowed. We need to first remove the current one then add the new one. 
related #1630 
https://user-images.githubusercontent.com/51242349/177499407-a245110b-b8a5-4bfa-86de-223eefa0744f.mp4

Changing the component of an element error

---

libs/frontend/modules/element/src/store/element.service.ts
libs/shared/abstract/core/src/domain/element/element.service.interface.ts

There seem to have been a mismatch between the new param of `ElementService.convertElementToComponent` and the one of `IElementService.convertElementToComponent` in #1638 causing all CI to fail.

Fix ElementService interface/class mismatch

---

libs/frontend/modules/builder/src/sections/config-pane/ConfigPane.tsx
libs/frontend/modules/element/src/use-cases/element/delete-element/DeleteElementButton.tsx
libs/frontend/modules/element/src/use-cases/element/move-element/MoveElementForm.tsx

This PR fixes:
- [ANNOYING] The root element of a component can be deleted.
- [Annoying] Children of an element are listed as potential parents.
For more details see 9 and 10 in #1630 
Related: #1630

Config Pane Enhancements/Fixes

---

libs/frontend/modules/builder/src/sections/explorer-pane/ElementContextMenu.tsx

fixes: [CRASH/ERROR] (Right click -> Edit Component) on an element that is an instance of component redirects to 404 page.
Related: #1630

fix Edit Component option redirects to 404

---

apps/builder/pages/admin/index.tsx
apps/builder/pages/apps/[appId]/domains/index.tsx
apps/builder/pages/apps/[appId]/pages/[pageId]/builder.tsx
apps/builder/pages/apps/[appId]/pages/index.tsx
apps/builder/pages/apps/[appId]/store.tsx
apps/builder/pages/apps/index.tsx
apps/builder/pages/atoms/index.tsx
apps/builder/pages/resources/index.tsx
apps/builder/pages/tags/index.tsx
apps/builder/pages/types/index.tsx
apps/builder/pages/types/interfaces/[interfaceId]/index.tsx
libs/frontend/modules/user/src/store/user.model.ts
libs/frontend/view/sections/Menu/commonMenuItems.tsx
libs/shared/abstract/core/src/domain/user/user.interface.ts

- I opted for having all the items at all times, but if no appId and/or pageId is available, the item would be disabled. I think this would provide a good user experience as users would see the cause and effect of their actions clearly (i.e. when they select an app or page and the sidebar button gets activated).
- The appId and pageId are stored in mobX.
https://user-images.githubusercontent.com/51242349/183489721-c8cc4b32-c135-443c-9c0d-62d0fa3bb53c.mp4
Fixes #1671

Sidebar Confusion

---

libs/frontend/modules/atom/src/store/atom.model.ts
libs/frontend/modules/atom/src/store/custom-text-injection-whitelist.ts
libs/frontend/modules/element/src/store/element.model.ts
libs/frontend/modules/element/src/use-cases/element/update-inner-html/UpdateInnerHtmlForm.tsx
libs/frontend/modules/renderer/src/element/ElementWrapper.ts
libs/frontend/modules/renderer/src/element/wrapper.utils.ts
libs/frontend/modules/renderer/src/renderer.model.ts
libs/frontend/modules/renderer/src/test/renderAtomPipe.spec.ts
libs/frontend/modules/renderer/src/test/setup/setupTest.ts
libs/frontend/modules/renderer/src/test/typedValueTranformers.spec.ts
libs/frontend/platform/atoms/src/custom/text/Text.tsx
libs/shared/abstract/core/src/domain/atom/atom.interface.ts
libs/shared/abstract/core/src/domain/element/element.model.interface.ts

This PR injects custom text (html) into elements by injecting a `<span>` element with it's inner html set to the custom text. This feature is enabled only for a selected number of Atoms since some atoms do not accept children.
https://user-images.githubusercontent.com/51242349/184231157-85b2cc59-1693-4af6-8a96-5b86bd96f1c3.mp4
Fixes #1709

InnerHtml Editor Enhanced

---

apps/builder/pages/apps/[appId]/pages/[pageId]/builder.tsx
apps/builder/pages/apps/[appId]/provider.tsx
libs/frontend/modules/builder/src/sections/config-pane/ConfigPane-InspectorTabContainer/ConfigPane-InspectorTabContainer.tsx
libs/frontend/modules/builder/src/sections/config-pane/ConfigPane.tsx
libs/frontend/modules/element/src/use-cases/element/update-element-props/UpdateElementPropsForm.tsx

A shortcut button in props sidebar tab that redirects to the interface of the selected atom.
https://user-images.githubusercontent.com/51242349/183854198-fe7ee3b1-d74d-45f1-9dec-c96c19b65a6b.mp4
Fixes #1704

Shortcut to Atom's interface

---

libs/frontend/view/components/resizable/useResizable.ts

After window resize, aparently, motion decides to translate the border with the same delta when resizing a panel. The current solution is just forcing 0px translation.
Fixes #1668

Stuck panel border fix

---

libs/frontend/modules/builder/src/hooks/useBuilderHotkeys.ts

fix: disable deleting the root element using hotkeys
This PR disables deleting the root element of a page using hotkeys. 
It also includes fix for the bug where pressing `del` on a non-root element would open delete modal for the root element.
Fixes #1775 @melhamin make sure this format

1755 disallow deleting root element

---

libs/frontend/modules/element/src/store/element.service.ts
libs/frontend/modules/type/src/store/type.service.ts
libs/shared/abstract/core/src/domain/element/element.service.interface.ts

This PR fixes prop data left over in the elements after the prop is deleted from an atom API. 
Fixes #1758

fix: prop data left over after delete

---

libs/frontend/modules/element/src/store/element.service.ts

This is an add-on parameter that skips the updating cache when we want to make multiple changes to an element, and bulk updates the cache. It's not used anymore as we have a bulk update function that takes multiple mutations, and we can provide our own update cache function
#1800

fix: remove update cache fn from element.service

---

apps/builder-e2e/src/e2e/component.cy.ts
apps/builder/pages/apps/[appId]/pages/[pageId]/builder.tsx
apps/builder/pages/apps/[appId]/pages/[pageId]/index.tsx
libs/backend/adapter/neo4j/src/selectionSets/componentSelectionSet.ts
libs/frontend/modules/component/src/store/component.service.ts
libs/shared/abstract/core/src/domain/component/component.service.interface.ts

refactor: init component tree on builder, pass only components to init

---

libs/frontend/modules/element/src/use-cases/element/update-element-props/UpdateElementPropsForm.tsx
libs/frontend/modules/type/src/props-form/PropsForm.tsx

This also fixes a bug causing element prop changes from being saved

fix: autosave typo

---

apps/cli/src/use-cases/seed/parser.service.ts
libs/backend/adapter/neo4j/src/cypher/type/field/connectField.cypher
libs/backend/adapter/neo4j/src/schema/type/field.schema.ts
libs/backend/adapter/neo4j/src/selectionSets/typeSelectionSet.ts
libs/frontend/modules/element/src/use-cases/element/update-element-props/UpdateElementPropsForm.tsx
libs/frontend/modules/type/src/interface-form/type-schema.factory.ts
libs/frontend/modules/type/src/interface-form/types.ts
libs/frontend/modules/type/src/store/models/field.model.ts
libs/frontend/modules/type/src/store/tests/typeTreeToJsonSchemaTestData.ts
libs/frontend/modules/type/src/store/type.service.ts
libs/frontend/modules/type/src/use-cases/fields/create-field/CreateFieldModal.tsx
libs/frontend/modules/type/src/use-cases/fields/create-field/createFieldSchema.ts
libs/frontend/modules/type/src/use-cases/fields/get-fields/FieldsTable.tsx
libs/frontend/modules/type/src/use-cases/fields/update-field/UpdateFieldModal.tsx
libs/shared/abstract/codegen/src/ogm-types.gen.ts
libs/shared/abstract/codegen/src/types.api.graphql.gen.ts
libs/shared/abstract/core/src/domain/type/field.dto.interface.ts
libs/shared/abstract/core/src/domain/type/field/field.interface.ts
libs/shared/abstract/core/src/domain/type/fragments/field.fragment.graphql
libs/shared/abstract/core/src/domain/type/fragments/field.fragment.graphql.gen.ts
libs/shared/abstract/core/src/domain/type/type.service.interface.ts
schema.api.graphql

This PR introduces the validation module for InterfaceType Fields as discussed in #1760. The only difference is that the validation will be stored in the DB as a stringified JSON because Neo4J doesn't support nested data on relationships.
TODO:
https://user-images.githubusercontent.com/51242349/192883113-2c77682e-20ca-43e5-bc93-97738befb23a.mp4
Fixes #1760

Validation Module

---

.yarn/patches/cypress-npm-10.10.0-c25bdaa71e.patch
apps/builder-e2e/src/e2e/component.cy.ts
libs/frontend/abstract/core/src/domain/component/component.dto.interface.ts
libs/frontend/abstract/core/src/domain/element/element-tree.interface.model.ts
libs/frontend/abstract/core/src/domain/element/element.service.interface.ts
libs/frontend/abstract/core/src/ui/tree.interface.ts
libs/frontend/domain/builder/src/hooks/useElementTreeDrop/useElementTreeDrop.ts
libs/frontend/domain/builder/src/sections/explorer-pane/ElementContextMenu.tsx
libs/frontend/domain/builder/src/sections/explorer-pane/builder-tree/BuilderTree.tsx
libs/frontend/domain/component/src/store/api.utils.ts
libs/frontend/domain/component/src/store/component.service.ts
libs/frontend/domain/component/src/use-cases/create-component/CreateComponentModal.tsx
libs/frontend/domain/component/src/use-cases/create-component/createComponentSchema.ts
libs/frontend/domain/component/src/use-cases/update-component/UpdateComponentForm.tsx
libs/frontend/domain/component/src/use-cases/update-component/UpdateComponentModal.tsx
libs/frontend/domain/component/src/use-cases/update-component/createComponentSchema.ts
libs/frontend/domain/element/src/store/api.utils.ts
libs/frontend/domain/element/src/store/element-tree.model.ts
libs/frontend/domain/element/src/store/element.model.ts
libs/frontend/domain/element/src/store/element.service.ts
libs/frontend/domain/renderer/src/element/ElementWrapper.ts
package.json
yarn.lock

TODO: 
Fixes #1913
Fixes #1918 based on https://github.com/codelab-app/builder/issues/1918#issuecomment-1275070169

fix: element duplication, conversion into component, and moving between components

---

apps/builder/pages/apps/[appId]/pages/[pageId]/index.tsx
libs/frontend/domain/renderer/src/render.service.ts

Fixes page content is not rendered after navigating from other sidebar tabs to the `Builder` tab.
Fixes #1929

fix: page not rendered after clicking on Builder tab

---

libs/frontend/abstract/core/src/constant.ts
libs/frontend/abstract/core/src/domain/element/element.service.interface.ts
libs/frontend/abstract/core/src/domain/prop/prop.dto.interface.ts
libs/frontend/domain/element/src/store/element.model.ts
libs/frontend/domain/element/src/store/element.service.ts
libs/frontend/domain/element/src/use-cases/element/update-rich-text/UpdateRichTextForm.tsx
libs/frontend/domain/prop/src/store/prop.model.ts
libs/frontend/domain/renderer/src/element/ElementWrapper.ts
libs/frontend/domain/renderer/src/test/renderAtomPipe.spec.ts
libs/frontend/domain/renderer/src/test/setup/setupTest.ts
libs/frontend/domain/renderer/src/test/typedValueTranformers.spec.ts
libs/frontend/domain/type/src/store/field.service.ts

This PR includes a frontend solution for removing props that are left over in elements props after deleting it from atom's api. Replaces existing solution that updates element element props after the prop is deleted from atom's api.
Fixes #1758

fix: filter out props keys that are not defined in atom api

---

libs/frontend/domain/renderer/src/element/DraggableElement.tsx
libs/frontend/domain/renderer/src/element/draggableElement.util.ts
libs/frontend/domain/type/src/use-cases/types/get-types/GetTypesTable.tsx

fix: stop element tree from re-rendering on mouse move

---

libs/backend/infra/adapter/neo4j/src/cypher/element/getDescendants.cypher

fix: get descendants cypher retrieves siblings alongside children

---

libs/frontend/domain/renderer/src/renderer.model.ts

Fixes the error thrown after removing a prop of type `ReactNodeType` from element props.
Fixes #1977

fix: remove prop of type ReactNode error

---

apps/builder-e2e/cypress.test.config.ts
apps/builder-e2e/project.json

- Show all existing tests instead of a single test in cypress development environment
- Add run server in cypress dev configuration

fix: remove spec pattern from cypress test config

---

apps/builder-e2e/src/e2e/providersPage.cy.ts
apps/builder/pages/apps/[appId]/pages/[pageId]/builder.tsx
libs/frontend/domain/builder/src/sections/config-pane/ConfigPane-InspectorTabContainer/ConfigPane-InspectorTabContainer.tsx
libs/frontend/domain/builder/src/sections/config-pane/ConfigPane.tsx
libs/frontend/domain/element/src/use-cases/element/update-element-props/UpdateElementPropsForm.tsx
libs/frontend/view/templates/Dashboard/DashboardTemplate-ConfigPane.tsx
libs/frontend/view/templates/Dashboard/DashboardTemplate.tsx

This PR fixes the scrolling issue of the props panel. Some portion of the content was rendered out of the screen because the panel had 100% height but was shifted to 48px from the top (because of the header). Also, padding is added for the last child in the panel so it is displayed better.
Some minor changes to the related codebase were made: removed unused functions, commented code, and fixed some warnings from vscode.
Before             |  After
Fixes #1988

1988 props panel scroll issue

---

libs/frontend/domain/type/src/interface-form/fields/select-action/SelectAction.tsx
libs/frontend/domain/type/src/interface-form/fields/select-app/SelectApp.tsx
libs/frontend/domain/type/src/interface-form/fields/select-atom/SelectAtom.tsx
libs/frontend/domain/type/src/interface-form/fields/select-component/SelectComponent.tsx
libs/frontend/domain/type/src/interface-form/fields/select-element/SelectElement.tsx
libs/frontend/domain/type/src/interface-form/fields/select-page/SelectPage.tsx
libs/frontend/domain/type/src/interface-form/fields/select-resource/SelectResource.tsx
libs/frontend/domain/type/src/interface-form/fields/select-store/SelectStore.tsx
libs/frontend/domain/type/src/interface-form/type-schema.factory.ts

There is an issue with `antd` Select component when it is rendered inside a scrollable container.
In official documentation for this component (https://ant.design/components/select/) as a valid solution suggested to customize `getPopupContainer` prop which defines where the dropdown menu will be rendered (default is body).
As a fix - the dropdown menu should render next to the select component in DOM.
This fix was applied to all places where there was a chance to get this issue.
Note: It is possible to define `getPopupContainer` method on `ConfigProvider` node inside of `_app.tsx`, but this does not work for us. Most of the Select components are rendered in forms using `teraform-antd`. This package uses the Select component from `antd/lib/select` location, and this component does not take …

fix: select component issue when inside scrollable container

---

.env.example
.env.test.example
apps/builder-e2e/cypress.ci.config.ts
apps/builder-e2e/cypress.test.config.ts
apps/builder-e2e/src/support/e2e.ts
apps/builder-e2e/src/support/env.ts
apps/builder/pages/api/graphql.ts
libs/frontend/domain/user/src/uses-cases/upsert-user/upsert-user.ts
libs/shared/adapter/logging/src/winston-driver.ts
libs/shared/env/src/env.ts

- Set `CYPRESS_ENABLE_LOGGING` in cypress config to enable logging in e2e test
- Set `NEXT_API_ENABLE_LOGGING` in `.env` to enable logging next API request/response. For enabling in e2e test, set the env in command section when starting server
`apps/builder-e2e/project.json`
```js
"test": {
"commands": [
{
"command": "npx wait-on --interval 1000 --delay 3000 'http://127.0.0.1:3001' && echo 'READY'"
},
{
"command": "NEXT_API_ENABLE_LOGGING=true nx serve-test builder -c test"
}
]
},
```
- Use existing logs, remove unused logs
Fixes #2009

tweak log behaviors in e2e, next API

---

apps/builder-e2e/src/data/tag.ts

Rework names of the tags that are used in the tags.cy.ts spec. The failing test was trying to delete the tag with the name "Delete-Tag-0", but tags with the names "Delete-Tag-0-0" and "Delete-Tag-0-1" also matched the "contains" condition. In the "before" hook, depending on what tag is created first - determined final tags order in the grid. And sometimes the wrong tag gets deleted ("Delete-Tag-0-1" instead of "Delete-tag-0") and the assertion fails. With new names - there is no way some different tag will match the selector
Fixes #2015

test(apps-builder-e2e): stabilize tags.cy e2e test (#2015)

---

apps/cli/src/use-cases/seed/types/enum-type-map.ts

When on the Props form some value is selected from the dropdown (EnumType) - pascal case value is used and passed as a parameter to the component. Such values are invalid and they are ignored by components. So most of the Enum properties do not work for many of the atoms. For example there is "shape" dropdown for Button atom exists. The corresponding dropdown had values equal to "Square" and "Circle", but this are invalid values, "square" and "circle" must be used instead. So this commit swaps key and value, and now all dropdowns will render on UI user-friendly Pascal case name and will use lower-case strings as values.
Before            |  After
Fixes #

fix(apps-cli): fix key/value seed data for enums (Preparation step for the task #1553)

---

apps/builder/pages/atoms/index.tsx
libs/backend/abstract/codegen/src/ogm-types.gen.ts
libs/backend/application/src/repositories/atom/atom.repo.ts
libs/backend/infra/adapter/neo4j/src/cypher/atom/atoms.cypher
libs/backend/infra/adapter/neo4j/src/cypher/atom/atomsWithLimit.cypher
libs/backend/infra/adapter/neo4j/src/cypher/atom/index.ts
libs/backend/infra/adapter/neo4j/src/cypher/index.ts
libs/backend/infra/adapter/neo4j/src/infra/ogm.ts
libs/backend/infra/adapter/neo4j/src/schema/schema.ts
libs/frontend/domain/atom/src/graphql/atom.endpoints.graphql
libs/frontend/domain/atom/src/graphql/atom.endpoints.graphql.gen.ts
libs/frontend/domain/atom/src/use-cases/get-atoms/GetAtomsTable.tsx
libs/frontend/domain/atom/src/use-cases/get-atoms/useAtomTable.tsx
libs/frontend/view/components/table/useColumnSearchProps.tsx
libs/shared/abstract/codegen/src/types.api.graphql.gen.ts
schema.api.graphql

fix atom table filter (server side filtering)

---

libs/frontend/domain/renderer/src/Renderer.tsx

emotion inserts style tags with user classes in the top of the head and the antd styles are inserted later which gives them higher priority. Add emotion wrapper for the app and setup emotion to append style tag at the bottom of the head
Before            |  After
Fixes #2048

fix(libs-frontend-domain): fix user style precedence (#2048)

---

libs/frontend/domain/element/src/css-editor/css-layout-editor/DisplayEditor.tsx
libs/frontend/domain/element/src/css-editor/css-layout-editor/PositionEditor.tsx

- Extend display options
- Remove duplicate zIndex option
| Before  | After |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/117329462/206350140-85bb13e2-d0ef-41d0-9344-59bfa42657eb.png) | ![image](https://user-images.githubusercontent.com/117329462/206350056-feb76d89-f257-4884-8c44-9bcd53e49cb3.png) |
Fixes #2082

feat: display option improvement

---

apps/builder/pages/_sites/user/[user]/[app]/[page]/index.tsx
apps/builder/pages/apps/[appId]/pages/[pageId]/index.tsx
libs/frontend/abstract/core/src/domain/builder/render.service.interface.ts
libs/frontend/domain/renderer/src/render.service.ts
libs/frontend/domain/renderer/src/renderer.model.ts
libs/frontend/domain/renderer/src/typedValueTransformers/ReactNodeTypedValueTransformer.ts
libs/frontend/domain/renderer/src/typedValueTransformers/RenderPropsTypedValueTransformer.ts
libs/frontend/shared/utils/src/stateExpressions.ts

After expressions with JSX transpilation were added the bundle size increased a lot. Load the "babel" package dynamically in order to fix this
Before            |  After
Fixes #

fix: PART 1: load babel transpiler using dynamic import (-50% bundle size) (#2101)

---

libs/frontend/presenter/container/src/pageHooks/useLoadRenderedPage.ts
libs/shared/utils/src/transform/strings.ts

- Fix issue when it became impossible to switch between pages via the dropdown in the header (after the page redirection feature was introduced)
- Revert changes where string API was deleted. Comment it instead
Fixes #

fix: fix page switching (#2101)

---

libs/frontend/domain/app/src/store/app.service.ts
libs/shared/adapter/logging/src/winston-driver.ts
libs/shared/config/src/flags.ts
libs/shared/config/src/graphql.ts

Preview builds for the builder app were broken. In this PR couple of issues are solved:
- mixed protocols error: the app uses HTTPS protocol to load all the resources but HTTP for graphql endpoint. Browsers block requests in such situations for security reasons. 
- serverless functions on vercel can not access the file system (it is read-only). So our logger failed on an attempt to write logs to files and the graphql endpoint crashed. Disabled login to file system for now.
- graphql requests for all preview builds share the same endpoint - `https://admin.codelab.app/api/graphql`. This causes the requests to fail because of the CORS issue. Use the graphql endpoint that is on the same origin (endpoint of the preview build)
- fix the error on creating the second app. Pages `slug` property …

fix: fix preview builds on PRs

---

apps/builder/pages/apps/[appId]/pages/[pageId]/builder.tsx
libs/frontend/domain/builder/src/sections/config-pane/ConfigPane-InspectorTabContainer/ConfigPane-InspectorTabContainer.tsx
libs/frontend/domain/builder/src/sections/config-pane/ConfigPane.tsx
libs/frontend/domain/element/src/use-cases/element/update-element-props/UpdateElementPropsForm.tsx

- can now add, edit, or delete a prop on the builder page
[edit-type-on-builder.webm](https://user-images.githubusercontent.com/27695022/211051824-09d1bb73-9a9c-4365-8f80-f71f5f1b13e6.webm)
Fixes #2136

feat(apps-builder): implement editing of type API in the builder page

---

apps/builder/pages/types/index.tsx
libs/backend/application/src/repositories/atom/atom.repo.ts
libs/frontend/domain/atom/src/use-cases/get-atoms/GetAtomsTable.tsx
libs/frontend/domain/type/src/store/type.service.ts
libs/frontend/domain/type/src/use-cases/types/get-types/GetTypesTable.tsx
libs/frontend/domain/type/src/use-cases/types/get-types/getTypeHooks.ts
libs/frontend/domain/type/src/use-cases/types/get-types/index.ts
libs/frontend/domain/type/src/use-cases/types/get-types/useTypesTableData.ts

In addition to fixing non-adjacent pages data, this PR removes the support for navigating to the selected id in /types url query.
Fixes #2079

fix: paginating non-adjacent pages

---

libs/frontend/abstract/core/src/domain/builder/renderer.model.interface.ts
libs/frontend/domain/renderer/src/element/ElementWrapper.ts
libs/frontend/domain/renderer/src/element/wrapper.utils.ts
libs/frontend/domain/renderer/src/renderer.model.ts

- add the `isBuilder` to the `Renderer` model so it can be used to conditionally wrap the element with `DraggableElementWrapper` if `isBuilder` is `true`
- the element will not be wrapped with `DraggableElementWrapper` if `isBuilder` is false (e.g. when in `.../pages/{pageId})` for view mode)
**view mode:**
**builder mode:**
Fixes #2094

refactor: dont wrap the element with DraggableElementWrapper if not on builder

---

apps/builder/pages/atoms/index.tsx
libs/frontend/domain/atom/src/use-cases/get-atoms/GetAtomsTable.tsx
libs/frontend/domain/atom/src/use-cases/get-atoms/columns/PropsColumn.tsx
libs/frontend/domain/atom/src/use-cases/get-atoms/columns/types.ts
libs/frontend/domain/atom/src/use-cases/get-atoms/useAtomTable.tsx

Here I used the same buttons used in the Builder. however, I've hidden them under `Edit API` button so we load the interfaces on demand instead of loading all of them with the initial page load.
https://user-images.githubusercontent.com/51242349/211617103-f33564e1-630a-44c9-80cc-0253b4cfbf81.mp4
Fixes #2153

Add fields modifying modals to atoms page

---

libs/frontend/abstract/core/src/domain/builder/builder.interface.ts
libs/frontend/abstract/core/src/domain/builder/builder.service.interface.ts
libs/frontend/domain/builder/src/hooks/useBuilderResize.ts
libs/frontend/domain/builder/src/sections/content/BaseBuilder.tsx
libs/frontend/domain/builder/src/sections/content/Builder.tsx
libs/frontend/domain/builder/src/store/builder.service.ts
libs/frontend/domain/page/src/view/PageDetailHeader.tsx
libs/frontend/domain/page/src/view/constants.ts

Inspired by Webflow's design, I've changed the builder size breakpoints into a range instead of a single value. Also, when a specific device type is selected the builder is allowed to be resized only in the range associated with that device.
https://user-images.githubusercontent.com/51242349/212045941-07e3b520-4245-4d75-970f-8067a5f4db0f.mp4
https://user-images.githubusercontent.com/51242349/212046607-8982c5cc-9d13-468f-b555-b8c3049f92c3.mp4
Fixes #2107

Builder size selector enhancements

---

libs/frontend/abstract/core/src/domain/builder/builder.interface.ts
libs/frontend/abstract/types/src/utils.tsx
libs/frontend/domain/builder/src/dnd/useDndDropHandlers.ts
libs/frontend/domain/builder/src/sections/content/Builder.tsx
libs/frontend/domain/renderer/src/Renderer.tsx
libs/frontend/domain/renderer/src/element/DraggableElement.tsx
libs/frontend/domain/renderer/src/element/draggableElement.util.ts
libs/frontend/domain/renderer/src/utils/index.ts
libs/frontend/domain/renderer/src/utils/makeDropIndicatorStyle.ts

The root element needs to be droppable so that we can drop a draggable element into it.
The logic for creating a first child should also be fixed.
https://user-images.githubusercontent.com/27695022/212038489-1736bbae-554e-4d5a-921d-d1e03921a881.mp4
https://user-images.githubusercontent.com/27695022/211850769-23c0e841-638d-410c-9079-4f18001878a3.mp4
Fixes #2106

fix: cannot dnd atom to the builder if it is the first element

---

libs/frontend/domain/element/src/store/element.service.ts

use component instance counter instead of id for component instance name to provide better user experience
Before            |  After
Fixes #1753

fix: use counter instead of id for component instance name

---

libs/frontend/domain/builder/src/dnd/useDndDropHandlers.ts
libs/frontend/domain/renderer/src/element/ElementWrapper.ts
libs/frontend/domain/renderer/src/element/wrapper.utils.ts
libs/frontend/domain/renderer/src/utils/makeDropIndicatorStyle.ts

- the `data-component-id` prop is stored on the global props context in the whole component
- this is used to determine if the element to be rendered is inside a component
- drag and drop feature is only added to component's root element or elements not in a component
- wrap the whole component with `<span>` instead of fragment to be able to apply drag and drop to the whole component (will also work if first children is multiple siblings)
- <span> should have less effect than `<div>` to the layout
- fix creating and moving an element inside an element + before first child
- add `zIndex` to the indicatorStyle so that it shows properly when theres a sibling element and there is no margin between
https://user-images.githubusercontent.com/27695022/212916296-522aff46-6ab3-43a1-b097-1bdca1f56628 …

fix(libs-frontend-domain-renderer): component should be draggable only as a whole

---

apps/builder/pages/apps/[appId]/pages/[pageId]/builder.tsx
libs/frontend/domain/builder/src/dnd/useDndDropHandlers.ts

- Add auto increment logic to the slug of the new dnd'ed element if theres an existing same atoms in the current element tree
- Theres still a chance that the new slug is also already existing in the current element tree. To keep the solution simple for now, it will throw an error if the same slug already exists. Though it should rarely happen, these are some cases it could happen:
- a different atom with slug `antdesignbutton-5` then you just dnd'ed the new actual 5th button
- renamed the slug of the last same atom from `antdesignbutton-4` to `antdesignbutton-5` then you just dnd'ed the new actual 5th button
- I also notice that the same page element tree is being used in the builder context when in the component view and if there is an `antdesignbutton-5` in the page tree, dnd'ing a 5th …

fix: drag and dropping the same atom twice fails the second time

---

libs/frontend/domain/app/src/store/app.model.ts

Because provider tree was moved to `_app` page, app model doesn't need to extend `ElementTreeService` 
Fixes #

refactor: remove tree service from app model

---

libs/frontend/domain/renderer/src/Renderer.tsx

We could do more optimization around the builder so that it doesn't cause too much re-rendering. But for now, we can use `useMemo` on the `renderRoot` to prevent too much re-rendering.
https://user-images.githubusercontent.com/27695022/213487452-f79f5b55-de93-4b98-8b2b-0f0ab7e9a2b6.mp4
Fixes #2189

fix: builder is rendering too much when dragging into the builder

---

libs/frontend/domain/builder/src/sections/config-pane/ConfigPane-ComponentTabContainer/GetComponentItem.tsx
libs/frontend/domain/element/src/store/api.utils.ts
libs/frontend/domain/element/src/store/element.service.ts

The issue is that we are not passing the `propsData` when creating an element.
We need to include `propsData` which should be a JSON that contains api fields that has a default value. Upon creation of the element, we need to check which type fields have a `defaultValues` not null or undefined. Then we generate the JSON and pass it on the `propsData` and it should create a `prop` connected to the created element, and has default values.
https://user-images.githubusercontent.com/27695022/213431366-18ce92d3-e244-46b5-bda2-43a297b47658.mp4
https://user-images.githubusercontent.com/27695022/213431410-2f91480e-8cda-46f9-8743-0a19d6f2e944.mp4
Fixes #2070

fix: Atoms are not populated with default values

---

libs/frontend/abstract/core/src/domain/atom/atom.model.interface.ts
libs/frontend/abstract/core/src/domain/component/component.model.interface.ts
libs/frontend/domain/builder/src/hooks/usePropsInspector.ts
libs/frontend/domain/builder/src/sections/config-pane/ConfigPane-InspectorTabContainer/ConfigPane-InspectorTabContainer.tsx
libs/frontend/domain/builder/src/sections/config-pane/PropsInspectorTab.tsx
libs/frontend/domain/component/src/store/api.utils.ts
libs/frontend/domain/component/src/store/index.ts
libs/frontend/domain/component/src/use-cases/update-component-props/UpdateComponentPropsForm.tsx
libs/frontend/domain/type/src/interface-form/type-schema.factory.ts

This PR is for allowing to view and edit the component props in component builder.
Currently, we only show the props inspector if the node type is "Element". Since components can also have props in the component builder, we can update the props inspector to also show on "Component" type.
I updated the `usePropsInspector` so that it can support both node type and user can also update the props in the component builder.
In this video, I tested in component props inspector:
- editing the props and it updated the api values in the props tab
- updated the api in the Props tab and it updated the values in the props inspector
- updated the props in the code mirror modal
- clearing the props resets the props to default values set in the api …

feat: props inspector on component props

---

libs/frontend/domain/builder/src/sections/explorer-pane/BuilderExplorerPane.tsx
libs/frontend/view/templates/ExplorerPaneTemplate.tsx

fixes side panel incorrect padding style
Fixes #2213
Closes #2213

fix(apps-builder): side panel incorrect padding

---

libs/frontend/domain/renderer/src/ExtraElementProps.ts
libs/frontend/domain/renderer/src/renderer.model.ts

Upon investigation, it seems this [part](https://github.com/codelab-app/platform/blob/master/libs/frontend/domain/renderer/src/renderer.model.ts#L327) causes the current `props` to be recursively added to the element in this [part](https://github.com/codelab-app/platform/blob/master/libs/frontend/domain/renderer/src/renderer.model.ts#L334). But what causes the infinite renders is the use of  [this.elementPropMap.set](https://github.com/codelab-app/platform/blob/master/libs/frontend/domain/renderer/src/ExtraElementProps.ts#L35) which always sets a new object to the element even if there is no change in the props.
This PR:
- spreads the `propsForCurrentElement` into the new `props` instead of putting it inside another `props`
- used [Ramda's whereEq](https://ramdajs.com/docs/#whereEq) on …

fix: infinite render when creating state variable

---

libs/frontend/domain/renderer/src/element/DraggableElement.tsx

There was a setTimeout function used as a workaround to fix some rendering issues with some atoms like AntDesignImage. I removed the setTimeout function and things seemed to be working flawlessly. Please see the image below.
Fixes #2161

fix(draggable-element component): refactor DraggableElement to not use setTimeout

---

apps/builder-e2e/src/e2e/providersPage.cy.ts
libs/frontend/abstract/core/src/domain/atom/atom.service.interface.ts
libs/frontend/domain/atom/src/store/atom.service.ts
libs/frontend/domain/builder/src/sections/content/BuilderTabs.tsx
libs/frontend/domain/type/src/interface-form/fields/select-atom/SelectAtom.tsx

During the demo app creation, some issues were detected and fixed:
- spinner appeared before the tabs component and it caused a layout shift (components below the spinner jumped down and up)
- requests for atoms were repeated a lot of times, use atom service with caching instead of manual request. Those requests are slowing down the production builder site a lot:
https://user-images.githubusercontent.com/74900868/217049644-9601e326-208e-416f-a06d-49d5bf6c787b.mov
- fix instability in e2e test because of - https://github.com/codelab-app/platform/issues/2235
#2224 
@vladyslav-polishchuk can remove fixes keyword so it’s linked at least

fix: fixes layout shift and duplicated requests

---

libs/frontend/domain/element/src/store/element.service.ts

This fixes the bug where if the element props on the component's descendants get updated, the config pane will keep loading for the descendants.
Turns out, the cloned elements' ids are being overwritten when the real element is updated and somehow messes up the getting of active element tree for the selected node because the refs for the actual element will be faulty [here](https://github.com/codelab-app/platform/blob/50cae3fe053102f6908ec313d15bee7639fac514/libs/frontend/domain/element/src/store/element.model.ts#L111)
In this video, im testing if the config pane will still keep loading when the descendant element props are being updated (due to the autosave happening currently when selecting a node)
https://user-images.githubusercontent.com/27695022/219381935-a7533697-2eb2-4d7c-bc84-92eb5 …

fix: cloned element id is being overwritten causing the props in config to keep loading

---

libs/frontend/abstract/core/src/domain/component/component.model.interface.ts
libs/frontend/domain/component/src/store/component.model.ts
libs/frontend/domain/element/src/store/element.model.ts

- Component children were not rendered because the clone id never matched the container id.
This is the first issue fixed under #2258. (see video in issue)
- Component props are not passed to child elements
This is the second issue fixed under #2258. (see video in issue)
Fixes #2258

fix: children of component instance not rendered (part 1)

---

apps/builder-e2e/src/e2e/component.cy.ts
libs/backend/infra/adapter/neo4j/src/schema/model/component.schema.ts
libs/frontend/domain/component/src/store/component.service.ts
libs/frontend/domain/renderer/src/renderer.model.ts

Fixed 2 issues:
- issue when the component instance was updated and childrenContainerElement property was reset to the original element instead of the cloned one and no children rendered again.
- issue when component instance children were impossible to render inside of the non-root component element
Update e2e test cases for components:
- case for handling component children rendering
- case for component props passing
Fixes #2258

fix: component issues and add additional e2e cases

---

apps/builder-e2e/src/e2e/providersPage.cy.ts

Full page reload initiated by `cy.go('back')` sometimes was preventing the request from being finished. And the settings on ConfigProvider were not always saved. Get rid of browser navigation and use the header menu to navigate between pages, which fixes instability and is also faster
Fixes #2280

fix: get rid of cy.go which does page reload

---

libs/frontend/domain/component/src/store/api.utils.ts

When the component was created, the root element was created as well, but no "props" were created for it.
This results in inability to set any props for this root element in the future since the "update" mutation was used and it does nothing if "props" does not exist
Before 
https://user-images.githubusercontent.com/74900868/219870083-ed823ebb-f8d7-44a6-af2a-4b8186a4d2e3.mov
After
https://user-images.githubusercontent.com/74900868/219870089-399bbfb0-05c7-4142-b9cb-7c4ed8d0d415.mov
Fixes #2239

fix: can't set props on component root element

---

apps/builder-e2e/src/e2e/component.cy.ts
apps/builder-e2e/src/e2e/types.cy.ts
apps/builder-e2e/src/support/antd/form/form.commands.ts
apps/builder-e2e/src/support/antd/form/form.types.ts
apps/builder-e2e/src/support/antd/table/table.command.ts
apps/builder-e2e/src/support/antd/table/table.types.ts
libs/frontend/domain/builder/src/hooks/usePropsInspector.ts
libs/frontend/domain/element/src/use-cases/element/update-element-props/UpdateElementPropsForm.tsx
libs/frontend/domain/type/src/interface-form/fields/select-default-value/SelectDefaultValue.tsx
libs/frontend/domain/type/src/interface-form/type-schema.factory.ts
libs/frontend/domain/type/src/interface-form/ui-properties/primativeUiProperties.ts
libs/frontend/domain/type/src/store/tests/schema.data.ts
libs/frontend/domain/type/src/use-cases/fields/create-field/CreateFieldModal.tsx
libs/frontend/domain/type/src/use-cases/fields/create-field/createFieldSchema.ts
libs/frontend/domain/type/src/use-cases/types/get-types/tables/FieldsTable.tsx
libs/frontend/view/components/form/fields/CodeMirrorField.tsx
libs/frontend/view/components/form/fields/ToggleExpressionField.tsx

This PR is for validating the edited props in the props inspector with the Element's atom/component interfaceType. The validator is created when props inspector is mounted and will use the selected element's interfaceType to generate the schema to be used for the validation against the editable props.
Also moved [this](https://github.com/codelab-app/platform/pull/2250/files#diff-5dbea52d1684a4f6c0b3927d9494c9298debec9fdedf981a37957d7e4570fa09L44) out of `ref` so that when it is updated, it automatically re-renders the props form with the new values
This PR also includes updating the `defaultValues` field so that if the `nullable` for the prop is not true, it will require the `defaultValues` and will display an error if not provided. The `nullable` field is also hidden when the type is …

feat: add validations to props inspector

---

libs/frontend/domain/builder/src/sections/config-pane/ConfigPane.tsx
libs/frontend/domain/builder/src/sections/explorer-pane/BuilderExplorerPane.tsx
libs/frontend/domain/builder/src/sections/stickyTabBarRenderer.tsx
libs/frontend/view/templates/Dashboard/DashboardTemplate-ExplorerPane.tsx
package.json
yarn.lock

This PR fixes scrolling issues in the builder.
Fixes #2244

Fix builder scrolling issues

---

libs/frontend/domain/app/src/store/api.utils.ts

restore `pageContainerElement` which allows attaching regular page elements to provider page elements. without it only provider elements will be rendered
Fixes #2301

fix: regular page elements not rendering in builder

---

apps/builder-e2e/src/e2e/admin/admin.cy.ts
apps/builder-e2e/src/e2e/apps.cy.ts
apps/builder-e2e/src/e2e/providers-page.cy.ts
apps/builder-e2e/src/support/nextjs-auth0/commands/login.ts

It seems that the user data needs to be upserted first before calling the mutations for seeding the data for testing.
I updated the [loginSession](https://github.com/codelab-app/platform/pull/2320/files#diff-36371f76c76798c489abdf2ec5b8891c261a5ab11d4ca2f756bc6e685d2e62a2R17) so that it visits the page where the [upsert of user data will happen](https://github.com/codelab-app/platform/blob/master/apps/builder/pages/apps/index.tsx#L62) before proceeding with the mutations.
Fixes #2319

fix: forbidden errors in e2e tests

---

terraform/modules/auth0/action_upsert_user.tf

Auth0 login hook failed to create a user on the first login since now the `id` is a required parameter

fix: user creation mutation now requires id

---

libs/frontend/abstract/core/src/domain/element/element-tree.interface.model.ts
libs/frontend/abstract/core/src/domain/element/element.service.interface.ts
libs/frontend/domain/builder/src/sections/explorer-pane/BuilderExplorerPane-Header.tsx
libs/frontend/domain/builder/src/sections/explorer-pane/BuilderExplorerPane.tsx
libs/frontend/domain/builder/src/sections/explorer-pane/ElementContextMenu.tsx
libs/frontend/domain/builder/src/sections/explorer-pane/builder-tree/BuilderTree.tsx
libs/frontend/domain/builder/src/sections/explorer-pane/builder-tree/BuilderTreeItem-ComponentTitle.tsx
libs/frontend/domain/builder/src/sections/explorer-pane/builder-tree/BuilderTreeItem-ElementTitle.tsx
libs/frontend/domain/builder/src/sections/explorer-pane/builder-tree/BuilderTreeItem-Title.tsx
libs/frontend/domain/component/src/use-cases/create-component/CreateComponentButton.tsx
libs/frontend/domain/element/src/store/element-modal.service.ts
libs/frontend/domain/element/src/store/element-tree.model.ts
libs/frontend/domain/element/src/use-cases/element/create-element/CreateElementButton.tsx
libs/frontend/domain/element/src/use-cases/element/create-element/CreateElementModal.tsx

This PR implements the following:
1. Adds `+` button for each component.
2. changes the style of create element and create component buttons by adding a descriptive text to it.
3. limits the parent element options to the scope of the create element button
4. if selected builder tree node is outside the scope of the element modal the root element of the element tree will be used as the parent element.
https://user-images.githubusercontent.com/51242349/221829889-ca87a6b3-efaf-4369-b1f4-7bd9c5475a38.mp4
Fixes #2308 
Fixes #2256

fix: Parent Element should show name instead of ID

---

libs/frontend/domain/renderer/src/renderer.model.ts

Fixes styles of elements of the `_app` page that are rendered inside other pages are not working.
Fixes #2236

fix: styles passed through css prop not working

---

apps/builder/pages/api/regenerate.ts
apps/websites/pages/[domain]/[page].tsx
apps/websites/pages/api/regenerate.ts
libs/backend/graphql/src/resolvers/index.ts
libs/backend/graphql/src/resolvers/page/index.ts
libs/frontend/domain/app/src/use-cases/build-app/BuildAppModal.tsx
libs/frontend/domain/domain/src/staticRegeneration.ts
libs/frontend/domain/page/src/use-cases/get-pages/GetPagesItem.tsx

- fixed auth0 403 error when requested to regenerate app pages.
Now the flow is the following:
user clicks the "rebuild" button on UI -> request to the builder backend is sent (admin.codelab.app) -> builder backend redirects the request to the appropriate domain of the websites project (for example to codelab-demo.online/api/regenerate). Each backend endpoint is protected by auth0 so an unauthenticated user will not be able to trigger the regeneration of any page.
- fixed website page routing after automatic slugs were implemented
after automatic slugs were implemented it became hard to navigate to user pages since they started to look like this: `https://codelab-demo.online/3-fe-3-e-3-b-3-0852-4056-9625-d-7-ba-490-a-125-a-home`. Used slugified page name to navigate to pages instead
Fixes …

fix: not authenticated error on page regeneration

---

examples/portfolio-website/user-data.json
libs/frontend/domain/app/src/store/api.utils.ts

- Fix when the providers' page does not render child page content
- Add the initial version of the Portfolio app to "examples" so that the progress is saved and anyone from developers can import it and use it as an example
Fixes #2224

docs: add initial Portfolio app version to "examples"

---

apps/builder-e2e/src/support/database/page.ts
apps/builder/pages/apps/[appId]/pages/[pageId]/index.tsx
libs/backend/infra/adapter/neo4j/src/schema/model/page.schema.ts
libs/frontend/abstract/core/src/constant.ts
libs/frontend/abstract/core/src/domain/page/page.dto.interface.ts
libs/frontend/abstract/core/src/domain/page/page.fragment.graphql
libs/frontend/abstract/core/src/domain/page/page.fragment.graphql.gen.ts
libs/frontend/abstract/core/src/domain/page/page.model.interface.ts
libs/frontend/abstract/core/src/ui/nextjs.interface.ts
libs/frontend/domain/builder/src/sections/content/BuilderTabs.tsx
libs/frontend/domain/page/src/services/page.factory.ts
libs/frontend/domain/page/src/store/page.model.ts
libs/frontend/domain/page/src/store/page.repository.ts
libs/frontend/domain/page/src/store/page.service.ts
libs/frontend/domain/page/src/use-cases/create-page/CreatePageModal.tsx
libs/frontend/domain/page/src/use-cases/create-page/create-page.schema.ts
libs/frontend/domain/page/src/use-cases/update-page-tab/UpdatePageTabForm.tsx
libs/frontend/domain/page/src/use-cases/update-page-tab/update-page-tab.schema.ts
libs/frontend/domain/page/src/use-cases/update-page/UpdatePageModal.tsx
libs/frontend/domain/page/src/use-cases/update-page/update-page.schema.ts
libs/shared/abstract/codegen/src/ogm-types.gen.ts
libs/shared/abstract/codegen/src/types.api.graphql.gen.ts
schema.api.graphql

- remove `getServerSideProps` from pages since in production we use Static Site Generation, which is completely serverless and no server props are supported
- return system pages names (from "Provider", "NotFound", "ServerError" to "_app", "404", "500")
- fix console error about deprecated `Tabs.Tabpane` usage
Fixes #

refactor: remove "getServerSideProps" and revert system page names

---

libs/frontend/abstract/core/src/domain/element/element.model.interface.ts
libs/frontend/domain/element/src/services/element.repo.ts
libs/frontend/domain/element/src/store/element.model.ts
libs/frontend/domain/element/src/store/element.service.ts
libs/frontend/domain/element/src/use-cases/element/move-element/MoveElementForm.tsx

- removed the `make*inputs` methods
- this follows the optimistic update we are trying to implement where we update the cache first then do network calls in a transaction
The issue was that the elements are not resolved correctly when there are multiple elements with the same `parent` because it is being treated as the same as `firstChild` relationship in [here](https://github.com/codelab-app/platform/blob/0d0ff6c1057095cd9232c0eb5a1547854ae06119/libs/backend/infra/adapter/neo4j/src/schema/model/element.schema.ts#L13).
This PR makes sure the connected nodes are correctly updated in the cache so that the [input](https://github.com/codelab-app/platform/pull/2354/files#diff-b94c779f8caff32713bbc7c19a7ac77b8ca9ef6e419712f7b16b4d45e235626cR403) is correctly generated for …

fix: elements swapping issues

---

libs/frontend/abstract/core/src/domain/element/element.service.interface.ts
libs/frontend/domain/builder/src/sections/explorer-pane/BuilderExplorerPane-Header.tsx
libs/frontend/domain/builder/src/sections/explorer-pane/ElementContextMenu.tsx
libs/frontend/domain/builder/src/sections/explorer-pane/builder-tree/BuilderTreeItem-ComponentTitle.tsx
libs/frontend/domain/element/src/use-cases/element/create-element/CreateElementButton.tsx
libs/frontend/domain/element/src/use-cases/element/create-element/CreateElementModal.tsx

This fixes the issue where when creating an element, the form fields get reset while still processing and this is due to updating the cache first before the actual save and is causing the CreateElementModal to re-render because the [element options](https://github.com/codelab-app/platform/pull/2373/files#diff-1e051f74cebcc472394998ff540f6d5e0788a178f1b5d90e79abff5581e44887L67) got updated.
This PR is for supplying the create modal with the element options upon opening so that the options does not change while the modal is open.
https://user-images.githubusercontent.com/27695022/225651739-0cce78e0-323b-4128-bee9-fa536d91ef3d.mp4
<br />
https://user-images.githubusercontent.com/27695022/225651930-8c792def-717b-4d13-bab2-0ffc8d2cee7d.mp4
Fixes #

fix: element creation shows error and resets fields while processing

---

libs/frontend/domain/atom/src/use-cases/get-atoms/useAtomTable.tsx

this pr fixes an infinite loop in `atomsTable` that was caused by calling `getAllAtoms.execute()` which triggers re-rendering which in turns updates the `pagination` object that leads to firing `useEffect` and so on 
Fixes #

Fix atomsTable infinite rendering loop

---

libs/frontend/abstract/core/src/domain/builder/renderer.model.interface.ts
libs/frontend/domain/builder/src/store/builder.service.ts
libs/frontend/domain/component/src/store/component.service.ts
libs/frontend/domain/element/src/store/element.service.ts
libs/frontend/domain/renderer/src/element/ElementWrapper.ts
libs/frontend/domain/renderer/src/renderer.model.ts

This PR fixes two issues:
1. When adding a component to the builder page then selecting the component node, it crashes because the wrong ref was being used (the clone instead of the original)
2. Changing the props in the component instance is not taking effect on the component descendant elements because the component instance props is not being passed down
Tested selecting the component nodes and updating the component instance props
https://user-images.githubusercontent.com/27695022/226685940-92cc208b-05e9-4f75-a298-c86aeb0171b9.mp4
Fixes #

fix: components instance issues

---

libs/frontend/domain/page/src/services/page.factory.ts
libs/frontend/domain/page/src/store/page.service.ts

Root element was missing reference to parent page which caused script error on attempt to open newly created page:
Fixes #

fix: script error on new page creation

---

libs/shared/domain/mapper/src/orm/reconnect.ts

Fixes bug in `reconnectNodeIds`, which causes only one node to be connected.
Fixes #2333

fix: bug in reconnectNodeIds

---

.circleci/config.yml
.docker/Dockerfile
apps/builder-e2e/src/e2e/css.cy.ignore.ts
apps/builder-e2e/src/e2e/store.cy.ignore.ts
libs/frontend/abstract/core/src/domain/element/element-tree.interface.model.ts
libs/frontend/domain/app/src/store/app.model.ts
libs/frontend/domain/element/src/store/element-tree/element-tree.model.ts
libs/frontend/domain/element/src/use-cases/element/create-element/CreateElementModal.tsx
libs/frontend/domain/type/src/store/type-pagination.service.ts
libs/shared/data/test/src/element.data.ts

- after the package dependencies update, Object.hasOwn is used internally which is only available starting from node 16.9.0. So node version is updated to fix build on CI
- fix data import issue, when an empty file with HtmlDiv caused the import to fail
- fix app creation issue. Since Page and Component models inherit ElementTree model and both of them had name property, this caused conflict when `page.name` executed computed property from the base (ElementTree) model.
- fix invalid page root element name in e2e mock data
Fixes #

fix: ci build, app create issue, invalid e2e data, import issue

---

libs/frontend/domain/element/src/store/element.model.ts
libs/frontend/domain/prop/src/store/prop.service.ts

When an element is updated, its existing props gets messed up because the `props` are also included on the update input and it was incorrectly structured that its making the current props to be wrapped inside another `data` like
```
{
"data": {
"data": {
"name":"Title",
"required":false,
"hidden":false,
"colon":true,
"label":"Title"
}
}
}
```
We actually dont need to include the props anymore when updating the element since we now update the props via `propService` when we update it on the props form or props inspector
https://user-images.githubusercontent.com/27695022/228260937-58fb191c-eb8c-445b-94f0-9add6b35fd78.mp4
<br />
https://user-images.githubusercontent.com/27695022/228261039-0f43b35e-63c0-4ecf-aea3-31dcb5862765.mp4
Fixes #

fix: props are messed up when updating the element

---

libs/backend/infra/adapter/neo4j/src/selectionSet/actionSelectionSet.ts
libs/backend/infra/adapter/neo4j/src/selectionSet/componentSelectionSet.ts
libs/backend/infra/adapter/neo4j/src/selectionSet/storeSelectionSet.ts
libs/frontend/domain/app/src/store/app.service.ts
libs/frontend/domain/renderer/src/element/ElementWrapper.ts
libs/frontend/domain/renderer/src/element/wrapper.utils.ts

- cleanup the ElementWrapper a bit by removing the DnD wrapper since its not currently working properly and might [need some re-works](https://github.com/codelab-app/platform/issues/2248)
- add component props references upon loading the page to fix ref error when a component instance references it
- fixed BE crashes when theres a component instance in the builder due to some missing fields in the selection set
**Still crashing in FE due to some cyclic logic issue. Maybe this will be fixed along with the other [PR](https://github.com/codelab-app/platform/pull/2416)**
This shows too many rendering happening when hovering on the builder section, which should be temporarily fixed by removing DnD wrapper for now
https://user-images.githubusercontent.com/27695022/228608467-8a03409e-8437-4431-8a …

refactor: some cleanups and attempt to fix crashes

---

libs/backend/domain/element/src/model/element.model.ts
libs/frontend/abstract/core/src/domain/element/element.dto.interface.ts
libs/frontend/abstract/core/src/domain/element/element.model.interface.ts
libs/frontend/domain/builder/src/store/builder.service.ts
libs/frontend/domain/component/src/store/component.model.ts
libs/frontend/domain/component/src/store/component.service.ts
libs/frontend/domain/element/src/store/element.model.ts
libs/frontend/domain/element/src/use-cases/element/create-element/CreateElementModal.tsx
libs/frontend/domain/renderer/src/renderer.model.ts
libs/frontend/domain/renderer/src/test/setup/setup-test.ts

- fixed cyclic traversal issue due to [bug on the logic of setting the element parent](https://github.com/codelab-app/platform/pull/2425/files#diff-1df306a8c4d34d1d731fcf135c78d3b94949bcc3ac5ce3975ad940a3ccbda0e4L141)
- re-renamed the `element.component` to `element.parentComponent` to make it the same with the BE response which also fixes the reference issue on the component builder
- 
Fixes #

fix: cyclic error when there is a component element

---

apps/builder-e2e/src/e2e/providers-page.cy.ts
apps/builder/pages/apps/index.tsx
libs/frontend/domain/component/src/use-cases/update-component/update-component.schema.ts
libs/frontend/domain/element/src/use-cases/element/create-element/create-element.schema.ts
libs/frontend/domain/page/src/use-cases/update-page-tab/update-page-tab.schema.ts
libs/frontend/view/components/form/schema/app.schema.ts
libs/frontend/view/components/form/schema/owner.schema.ts

- Fixed double field labels for form fields:
Before|After
- Fix apps not loaded when /apps page is loaded. It happened because useMountEffect is executed before the `user` is resolved - and request for apps never happens:
Before
https://user-images.githubusercontent.com/74900868/229300415-0d0a2c4b-44ed-48a1-b145-ad8c7b851e4e.mov
After
https://user-images.githubusercontent.com/74900868/229300451-95ea0581-c179-441d-be0d-2984903bb748.mov
Fixes #

fix: apps loading issue, multiple field labels

---

libs/frontend/domain/element/src/store/element.model.ts

The parent component was being set to null when the element is updated resulting to traversal error on getting the component node upon re-rendering
https://user-images.githubusercontent.com/27695022/229455524-ce112b10-42b4-4ce8-9a53-3c89364d6340.mp4
Fixes #2432

fix: keep parent component when element is updated

---

libs/backend/application/type/src/use-case/export-admin-types.ts
libs/backend/infra/adapter/neo4j/src/schema/type/type.schema.ts
libs/backend/infra/adapter/neo4j/src/selectionSet/typeSelectionSet.ts
libs/shared/abstract/codegen/src/ogm-types.gen.ts
libs/shared/abstract/codegen/src/types.api.graphql.gen.ts
schema.graphql

This PR implements a simple way to export array types as well as their item type (if it was of interface type).
Fixes #2288

feat: export array types

---

libs/backend/infra/adapter/neo4j/src/schema/model/component.schema.ts
libs/frontend/domain/type/src/graphql/interface-form.endpoints.graphql
libs/frontend/domain/type/src/graphql/interface-form.endpoints.graphql.gen.ts
libs/frontend/domain/type/src/interface-form/fields/select-component/SelectComponent.tsx
libs/shared/abstract/codegen/src/ogm-types.gen.ts
libs/shared/abstract/codegen/src/types.api.graphql.gen.ts
schema.graphql

SelectComponent dropdown is used in many places on forms and it sends the request for components each time it is mounted. The only reason for this request is to filter components that include other components as children. No need to do this request at all, since all the data is available at the client and this can be computed with the same algorithm complexity but with no request.
Before
https://user-images.githubusercontent.com/74900868/229877512-51aa7bac-4fad-4534-b9ce-d91f157c6e2c.mov
After
https://user-images.githubusercontent.com/74900868/229877968-5cc8ab67-8aba-4352-b72e-654e65d4d58d.mov
This is one of the fixes under #2215

refactor: remove request for components in Select

---

apps/cli/src/commands/tasks/tasks.command.ts
libs/backend/shared/util/src/file/save-formatted-file.ts
libs/frontend/domain/type/src/store/type.service.ts

- Do not request types over and over again if they were already loaded
- Fix linting errors on exported files with data (no new line in the end)
- Reduce the amount of parallel unit tests runs in CI. This is an experimental fix, since unit tests currently fail on CI almost in 100% cases with strange errors like `A jest worker process (pid=11453) was terminated by another process: signal=SIGKILL, exitCode=null.` This may be because of memory issues.
Before
https://user-images.githubusercontent.com/74900868/230017315-71274696-b682-4bd2-9f81-8bffa25f73e1.mov
After
https://user-images.githubusercontent.com/74900868/230017349-758461a8-af7a-4cc8-8b4c-6fa6f5c2c48c.mov
One of the fixes under #2215

fix: use interface from store if exists

---

libs/frontend/abstract/core/src/domain/element/element.fragment.graphql
libs/frontend/abstract/core/src/domain/element/element.fragment.graphql.gen.ts
libs/frontend/abstract/core/src/domain/page/page.fragment.graphql
libs/frontend/abstract/core/src/domain/page/page.fragment.graphql.gen.ts
libs/frontend/domain/app/src/store/app.service.ts
libs/shared/abstract/codegen/src/types.api.graphql.gen.ts

Query to get app and all related resources (pages, elements, components, stores, etc) cause the image that has only 1GB RAM to crash with an Out Of Memory error.
Reduce the complexity of the query by replacing full components information loading with only ID.
Not the query successes on 1GB ram image
Before
https://user-images.githubusercontent.com/74900868/231205525-69cfdbd9-a1c8-4a89-8d5c-ad5ca0825612.mov
Fixes #2441

refactor: simplify app query to use less resources

---

data/export/admin/atoms/AntDesignAvatar.json
libs/backend/application/admin/src/use-case/export-admin-data.service.ts
libs/backend/application/type/src/use-case/export-admin-types.ts
libs/backend/domain/type/src/repository/union-type.repo.ts
libs/backend/infra/adapter/neo4j/src/selectionSet/typeSelectionSet.ts

- includes union types fields when exporting the atoms
- fixed selection set for union types so that `typesOfUnionType` is included which is needed for importing the union type fields
- fixed connecting of nodes for the `typesOfUnionType` ids when importing
- fixed src field of AntDesignAvatar so that it is a union type of String and ReactNode
Fixes #2466

feat: support import and export of union types

---

libs/frontend/abstract/types/src/form/form.tsx
libs/frontend/domain/element/src/use-cases/element/update-element-props/UpdateElementPropsForm.tsx
libs/frontend/domain/type/src/interface-form/fields/select-default-value/SelectDefaultValue.tsx
libs/frontend/domain/type/src/interface-form/fields/select-union-type-value/SelectUnionTypeValue.tsx
libs/frontend/domain/type/src/interface-form/type-schema.factory.ts
libs/frontend/domain/type/src/use-cases/fields/create-field/CreateFieldModal.tsx
libs/frontend/domain/type/src/use-cases/fields/create-field/field-utils.ts
libs/frontend/domain/type/src/use-cases/fields/update-field/UpdateFieldModal.tsx
libs/frontend/view/components/form/components/Form.tsx
libs/frontend/view/components/form/modal/ModalForm.Form.tsx

- fixed `defaultValues` for UnionType so it will initially set the first of its types as the default
- hide the `nullable` option and the `defaultValues` field if field type is ReactNodeType or InterfaceType since we cannot set a default value for it
https://user-images.githubusercontent.com/27695022/231506074-a9350b79-f8b5-4056-b566-1462a69c1e14.mp4
Fixes #2459

fix: union type and react node field on create/update field modal

---

apps/platform/pages/apps/[appId]/pages/[pageId]/builder.tsx
libs/frontend/abstract/core/src/domain/app/app.dto.interface.ts
libs/frontend/abstract/core/src/domain/app/app.service.interface.ts
libs/frontend/domain/app/src/store/app.service.ts
libs/frontend/domain/builder/src/sections/content/BuilderTabs.tsx
libs/frontend/domain/page/src/view/PageDetailHeader.tsx
libs/frontend/presenter/container/src/pageHooks/index.ts
libs/frontend/presenter/container/src/pageHooks/useRemainingPages.ts

Suppose we have an app with 5 pages:
- Main
- Secondary
- _app
- 404
- 500
When builder is opened (`apps/{appId}/pages/${pageId}/builder`) two requests are performed:
- request to load the current page and system pages (Main, _app, 404, 500) and all related data: components, interfaces, and other types. The response is cached to the store. No problem with this request.
- request to load all the pages for the current app (Main, Secondary, _app, 404, 500), even though Main, _app, 404, 500 are already loaded by the first request. This request is sent from the `PageDetailHeader` component to display all pages and allow users to switch between them. There are 2 problems with this request: it loads duplicated data; and it DOES NOT CACHE response. So when the user switches to another page from …

refactor: remove duplicated data load in builder

---

libs/frontend/view/components/codeMirror/completionOptions.ts

It seems its because when the react node prop is transformed to an actual ReactNode then we try to build the autocomplete options thats used for fields like **"Render If"**, it was trying to get all the properties of the transformed ReactNode.
We need another condition on the generating of auto complete options to stop when it is a ReactNode. This PR uses the same logic from the [mapDeep](https://github.com/codelab-app/platform/blob/3244eb84af4b70be0dbb890c32dab749c633b6d5/libs/shared/utils/src/mapDeep/mapDeep.ts)
https://user-images.githubusercontent.com/27695022/231777585-8d7d2f85-1e63-4f56-a844-422c9d35c997.mp4
Fixes #2469

fix: crash when element has react node prop

---

libs/frontend/abstract/core/src/domain/app/app.service.interface.ts
libs/frontend/domain/app/src/store/app.service.ts
libs/frontend/presenter/container/src/pageHooks/useRemainingPages.ts

Replace `lazyGetRemainingPages` with a more general function `getAppPages` to load pages by any condition

refactor: make page load function more reusable

---

libs/frontend/abstract/core/src/domain/element/element.service.interface.ts
libs/frontend/domain/builder/src/hooks/useElementTreeDrop/useElementTreeDrop.ts
libs/frontend/domain/element/src/store/element.service.ts

The issue stems from pushing partial updates to the backend. more specifically, we used to detach the elements from their current tree, push updates, then attach to the new tree. and it seems like mobx tried to recalculate the value of `closestContainerNode` while we're pushing the updates, which causes the crash.
Instead we can perform all the actions on the local cache: detaching from current tree and attaching to the new tree, then push the changes to the backend.
On a separate note, the logic of `moveElementToAnotherTree` seemed quite complicated because it tries to perform one of two things: either move an element to another tree, or create a new element in the other tree as an instance of the component. hence, I renamed it to `moveNodeToAnotherTree` and made it call another method …

fix: move element to another tree crashes the builder

---

libs/backend/domain/type/src/model/field.model.ts
libs/backend/domain/type/src/repository/field.repo.ts
libs/backend/domain/type/src/repository/interface-type.repo.ts
libs/backend/infra/adapter/neo4j/src/schema/type/field.schema.ts
libs/backend/infra/adapter/neo4j/src/selectionSet/fieldSelectionSet.ts
libs/frontend/abstract/core/src/domain/type/field.dto.interface.ts
libs/frontend/abstract/core/src/domain/type/field/field.interface.ts
libs/frontend/abstract/core/src/domain/type/field/field.record.interface.ts
libs/frontend/abstract/core/src/domain/type/field/field.service.interface.ts
libs/frontend/abstract/core/src/domain/type/fragments/field.fragment.graphql
libs/frontend/abstract/core/src/domain/type/fragments/field.fragment.graphql.gen.ts
libs/frontend/domain/type/src/services/field.repo.ts
libs/frontend/domain/type/src/store/field.service.ts
libs/frontend/domain/type/src/store/models/field.model.ts
libs/frontend/domain/type/src/use-cases/types/get-types/tables/FieldsTable.tsx
libs/shared/abstract/codegen/src/ogm-types.gen.ts
libs/shared/abstract/codegen/src/types.api.graphql.gen.ts
package.json
schema.graphql
yarn.lock

add prevSibling and NextSibling to fields and  drag Icon to enable order for fields table
https://user-images.githubusercontent.com/47860740/232375616-aeaa69e2-ad82-4de4-aa3a-84c3cbd628bb.mp4
#2447 enable order for api fields
Fixes #

2447 enable order for api fields

---

libs/frontend/abstract/core/src/domain/element/element.dto.interface.ts
libs/frontend/domain/element/src/css-editor/ElementCssEditor.tsx
libs/frontend/domain/element/src/store/element.model.ts
libs/frontend/domain/element/src/use-cases/element/update-element-prop-transformation/UpdateElementPropTransformationForm.tsx
libs/frontend/domain/element/src/use-cases/element/update-element/UpdateElementForm.tsx
libs/frontend/domain/element/src/use-cases/element/update-element/update-element.schema.ts
libs/frontend/domain/element/src/utils/getElementModel.ts

Allow to nullify `renderType` in `element.writeCache` function. As a side effect updated all places that use `elementService.update` function to include all the props from `IUpdateElementData` instead of partially including them. Otherwise, it is impossible to distinguish when the property just was not passed and does not need to be updated from the case when it needs to be nullified.
https://user-images.githubusercontent.com/74900868/232804612-fe625410-de23-4b55-93a7-a2b0571440bd.mov
Fixes #2484

fix: allow to nullify renderType for elements

---

apps/platform-e2e/src/support/antd/form/form.commands.ts
apps/platform-e2e/src/support/builder/builder.command.ts
libs/frontend/abstract/core/src/domain/atom/atom.repo.interface.ts
libs/frontend/abstract/core/src/domain/atom/atom.service.interface.ts
libs/frontend/abstract/core/src/domain/type/type.repo.interface.ts
libs/frontend/abstract/core/src/domain/type/type.service.interface.ts
libs/frontend/domain/atom/src/graphql/atom.endpoints.graphql
libs/frontend/domain/atom/src/graphql/atom.endpoints.graphql.gen.ts
libs/frontend/domain/atom/src/store/atom.repo.ts
libs/frontend/domain/atom/src/store/atom.service.ts
libs/frontend/domain/type/src/graphql/get-type.endpoints.graphql
libs/frontend/domain/type/src/graphql/get-type.endpoints.graphql.gen.ts
libs/frontend/domain/type/src/interface-form/fields/select-atom/SelectAtom.tsx
libs/frontend/domain/type/src/services/type.repo.ts
libs/frontend/domain/type/src/shared/TypeSelect.tsx
libs/frontend/domain/type/src/store/type.service.ts
libs/shared/abstract/codegen/src/types.api.graphql.gen.ts

- created new queries for [atoms](https://github.com/codelab-app/platform/pull/2479/files#diff-36c113451e50e0945bc589072123548132618c3473c3b2dde8574d552162b0bfR29) and [types](https://github.com/codelab-app/platform/pull/2479/files#diff-b876f80c92ce861ebb6a7992b0928b077561c15751f7669eaa2e84710c73742aR157) to be specifically used for fetching all the atoms and types for the dropdown
- new queries are a lot smaller compared to the older query being used where lots of extra unused fields are being fetched
- created new methods for the atoms and types service (`getOptions`) that will use the new queries and will not do extra stuffs like storing to cache or loading underlying types that potentially freezes the app
- since this reduces the size of the responses and the extra processes like …

refactor: atoms and types dropdown

---

libs/frontend/domain/builder/src/sections/explorer-pane/ElementContextMenu.tsx

When an element that is selected in the builder is deleted - the context menu for it is still rendered before the element is fully detached and `closestContainerNode` computed property throws an error. Move this computed property execution to where it is used instead of being on the root level of the context menu component.
Fixes #2500

fix: context menu error on deleted element

---

apps/platform-e2e/src/e2e/builder.cy.ts
apps/platform-e2e/src/e2e/component.cy.ts
apps/platform-e2e/src/e2e/pages.cy.ts
apps/platform-e2e/src/e2e/providers-page.cy.ts
apps/platform-e2e/src/e2e/tag.cy.ts
apps/platform-e2e/src/support/entities/tag/tag.command.ts

- remove redundant calls to user endpoint (/me)
- stabilize tag.cy spec by using more specific RegExp. Tag table has a different order of tags and the test sometimes was selecting `Delete-tag-0-1` instead of `Delete-tag-0`, because they have the common part in the name (`Delete-tag-0`), and depending on the table order, the spec was sometimes deleting the wrong tag.
Fixes #2499

wip: fix: stabilize e2e specs

---

apps/platform/pages/apps/[appId]/pages/[pageId]/builder.tsx
libs/frontend/domain/builder/src/sections/content/Builder-Component.tsx
libs/frontend/domain/builder/src/sections/content/Builder.tsx
libs/frontend/domain/builder/src/sections/content/BuilderTabs.tsx
libs/frontend/domain/renderer/src/Renderer.tsx

The remaining issues with e2e were caused by re-rendering on the builder page. The test was trying to type/click on a node that no longer exists in the DOM because of re-rendering. This PR reduces amount of re-renders and increases stability of e2e tests
Fixes #2499

fix: e2e by reducing re-renders

---

libs/frontend/domain/element/src/store/element.service.ts

If the element that is about to be deleted is linked as a children container in a component - replace this link to the component root
https://user-images.githubusercontent.com/74900868/233367358-5fc3869e-e467-48cd-97c1-d43436f5e021.mov
Fixes #2503

fix: reset component children container on delete

---

libs/frontend/domain/renderer/src/element/wrapper.utils.ts

If an atom is assigned to the component root element - it was replaced with `span` during rendering in order to group all component children under a single DOM node. The logic is updated to do so only if no atom is assigned (e.g. render span instead of Fragment)
Before
https://user-images.githubusercontent.com/74900868/233795508-9b1213b5-41e9-4d0a-b78a-8a508e462f52.mov
After
https://user-images.githubusercontent.com/74900868/233795417-3553cf1f-212a-4cfc-a47c-c5102b4e7dab.mov
Fixes #2501

fix: do not replace component root atom with span

---

apps/landing/pages/_app.tsx
apps/platform-e2e/src/e2e/component.cy.ts
apps/platform/pages/_app.tsx
apps/websites/pages/_app.tsx

Apply `antd/dist/reset.css` to fix common CSS problems.
Also stabilize e2e test that failed on this PR.
This fixes the scrolling problem described in the current issue:
https://user-images.githubusercontent.com/74900868/233830592-35c64a8f-b1df-4b1e-8e46-3dc70b7e57c3.mov
And also some other issues with sizing, padding, margins:
Before             |  After
Before             |  After
Before             |  After
Fixes #2523

fix: apply global css fix

---

libs/frontend/domain/component/src/use-cases/create-component/CreateComponentModal.tsx
libs/frontend/domain/component/src/use-cases/create-component/create-component.schema.ts
libs/frontend/domain/component/src/use-cases/update-component/update-component.schema.ts

Element uses Title Case validation pattern for name. When creating a component its root element name is not validated, which causes the form submission to fail in case of invalid Element names.  
This PR adds Title Case validation for the component name as well. 
Fixes #2527

fix: use title case validation for component name

---

libs/frontend/domain/type/src/shared/index.ts
libs/frontend/domain/type/src/shared/sortFields.ts
libs/frontend/domain/type/src/store/models/interface-type.model.ts
libs/frontend/domain/type/src/use-cases/types/create-type/CreateTypeModal.tsx
libs/frontend/domain/type/src/use-cases/types/get-types/tables/FieldsTable.tsx

make props field follow the fields order 
https://user-images.githubusercontent.com/47860740/233812381-eee3672e-eed8-4615-9c90-93fafd3e42ed.mp4
r Image
#2495 Make sure props form uses field order
Fixes #
#2495  Make sure props form uses field order

fix: make props form use field order

---

libs/frontend/view/templates/SidebarNavigation/SidebarNavigation.tsx

Solarized dark             |  Solarized Ocean
One part of the #2521

fix: sidebar styling issues

---

libs/frontend/domain/renderer/src/abstract/ITypedValueTransformer.ts
libs/frontend/domain/renderer/src/element/ElementWrapper.ts
libs/frontend/domain/renderer/src/renderer.model.ts
libs/frontend/domain/renderer/src/typedValueTransformers/ReactNodeTypedValueTransformer.ts

The issue was that when transforming the `ReactNodeType` in `ReactNodeTypedValueTransformer` we aren't passing the render props as part of the context, hence the created component has no access to that data.
https://user-images.githubusercontent.com/51242349/234057965-5b3ce540-85ca-42a3-8cc3-4185d31aac5f.mp4
Fixes #2285

fix: state expression not working in ReactNodeType

---

.github/PULL_REQUEST_TEMPLATE.md
libs/frontend/domain/type/src/interface-form/type-schema.factory.ts
libs/frontend/domain/type/src/interface-form/types.ts

Once an element is created - no props are passed to it and it renders using default values only. But when the first property is specified on the Element Props Form - the form schema is validated and default values are applied. Previously the form schema was set up to set all boolean values to "false" values, which is not what we want.
Before:
https://user-images.githubusercontent.com/74900868/234360828-c2026965-1b92-4f27-b80e-4c76173124ed.mov
After:
https://user-images.githubusercontent.com/74900868/234360160-3cf532e0-5331-4802-b57b-4020dd0b3e2b.mov
Fixes
- #2508

fix: don't apply "false" by default for bool props

---

apps/platform/pages/_app.tsx

Before             |  After
Before             |  After
Part of
- #2521

fix: layout header color

---

libs/backend/infra/adapter/neo4j/src/cypher/type/getBaseTypes.cypher
libs/backend/infra/adapter/neo4j/src/resolver/pure-resolver/type/query/base-types.ts
libs/frontend/domain/element/src/use-cases/element/update-element-prop-transformation/UpdateElementPropTransformationForm.tsx
libs/frontend/domain/type/src/graphql/get-type.endpoints.graphql
libs/frontend/domain/type/src/graphql/get-type.endpoints.graphql.gen.ts

- refactor the getBaseTypes cypher query so that if the `$limit` and `$skip` is null, it will still work and will execute the query without the LIMIT and SKIP
- the implementation uses the [apoc.cypher.run](https://neo4j.com/labs/apoc/4.1/overview/apoc.cypher/apoc.cypher.run/) to be able to conditionally add the LIMIT and SKIP clause into the whole query
- removed the hard coded limit of 99999 to query "all" the base types
Testing base types query to see its still working
https://user-images.githubusercontent.com/27695022/234055640-605587c0-102e-4808-ac67-b8d99e0cb812.mp4
Fixes #2514

refactor: get base types cypher query optional pagination

---

libs/frontend/abstract/core/src/domain/element/element.model.interface.ts
libs/frontend/domain/element/src/css-editor/ElementCssEditor.tsx

Reduce the number of hooks used in `ElementCssEditor` from 18 to just 5.
A bit different approach was used: all the changes were immediately applied from the editor to the `element` model, instead of saving it to the component state. And then either by debouncer or on component unmount these changes are saved to DB (depending on what happens earlier)
Fixes #2530

refactor: reduce hooks usage

---

apps/platform-e2e/src/e2e/css.cy.ts
libs/frontend/domain/element/src/css-editor/ElementCssEditor.tsx

While refactoring `ElementCssEditor` I made a mistake and used an inverted condition which caused invalid logic (css to be applied on the client but not to be saved to DB).
This is fixed not as well as automated
Fixes #2558

fix: mistake in condition statement

---

libs/frontend/presentation/view/components/form/fields/WrappedListField.tsx

This PR fixes the labels not showing on the interface types when they are inside an array type prop
| Before | After |
|-----------|---------|
| ![image](https://user-images.githubusercontent.com/27695022/235437780-431e0bed-f85f-4a5f-b75b-f5b41f6cc136.png) |  ![image](https://user-images.githubusercontent.com/27695022/235437953-83b954b0-1995-4dad-b517-86d94ae312ea.png) |
| ![image](https://user-images.githubusercontent.com/27695022/235438023-162077d5-3c34-46b0-a8ae-0717d257280c.png) | ![image](https://user-images.githubusercontent.com/27695022/235438047-87aaaaf2-565c-45c8-9ef1-384b641317ba.png) |
Fixes #2540

fix: missing labels on array types of interface types

---

libs/frontend/domain/app/src/use-cases/create-app/CreateAppModal.tsx
libs/frontend/domain/resource/src/use-cases/create-resource/CreateResourceModal.tsx
libs/frontend/domain/resource/src/use-cases/delete-resource/DeleteResourceModal.tsx
libs/frontend/domain/resource/src/use-cases/update-resource/UpdateResourceModal.tsx
libs/frontend/domain/tag/src/use-cases/create-tag/CreateTagModal.tsx
libs/frontend/domain/tag/src/use-cases/delete-tags/DeleteTagsModal.tsx
libs/frontend/domain/tag/src/use-cases/update-tag/UpdateTagModal.tsx
libs/frontend/domain/type/src/use-cases/fields/create-field/CreateFieldModal.tsx
libs/frontend/domain/type/src/use-cases/fields/update-field/UpdateFieldModal.tsx

change modal behavior to close without await for modal that I expect that wouldn't be replaced by inline form 
https://user-images.githubusercontent.com/47860740/236696920-f8fbb4d3-33e0-42b9-9bf9-0c707e3612fe.mp4
https://user-images.githubusercontent.com/47860740/236696946-e4ff57cf-f95f-40dd-992b-cef09861fe6e.mp4
https://user-images.githubusercontent.com/47860740/236696964-db1eb00a-96f2-4284-9b3d-2a9e254cd1cf.mp4
https://user-images.githubusercontent.com/47860740/236696979-62121f8b-ed13-446d-81c6-564c43f6b364.mp4
https://user-images.githubusercontent.com/47860740/236696997-45c8c598-04eb-49c1-8460-db2bb2b27b37.mp4
https://user-images.githubusercontent.com/47860740/236697014-0efad7f0-8b84-477a-9aa7-d039665930be.mp4
- #2434 
Fixes #
- #2434

fix: change modal behavior to close without await

---

apps/platform/pages/apps/[appId]/pages/[pageId]/builder.tsx
apps/platform/pages/apps/[appId]/pages/index.tsx
apps/platform/pages/tags/index.tsx
libs/frontend/abstract/core/src/domain/app/app.fragment.graphql
libs/frontend/abstract/core/src/domain/app/app.fragment.graphql.gen.ts
libs/frontend/abstract/types/src/ExplorerPaneType.ts
libs/frontend/abstract/types/src/index.ts
libs/frontend/domain/app/src/store/app.service.ts
libs/frontend/domain/app/src/use-cases/get-apps/GetAppsItem.tsx
libs/frontend/domain/builder/src/sections/content/Builder.tsx
libs/frontend/domain/page/src/use-cases/get-pages/GetPagesItem.tsx
libs/frontend/domain/page/src/use-cases/get-pages/PageList.tsx
libs/frontend/domain/page/src/view/ExplorerPanePage.tsx
libs/frontend/domain/page/src/view/PageDetailHeader.tsx
libs/frontend/presentation/view/sections/Menu/commonMenuItems.tsx
libs/frontend/presentation/view/templates/Dashboard/DashboardTemplate.tsx
libs/frontend/presentation/view/templates/Dashboard/Sidebar/SidebarNavigation.tsx
libs/frontend/presentation/view/templates/Dashboard/types.tsx
libs/frontend/presentation/view/templates/SidebarNavigation/SidebarNavigation.tsx

This PR changes the behaviour of the ExplorerPane and make it accept a list of options to be viewed in it.
This is the new interface:
```
interface PaneItem {
key: React.Key
render: JSXElementConstructor<unknown>
}
interface ExplorerPane {
default?: React.Key
items: Array<PaneItem>
}
```
Fixes #2585

feat: Pages left panel

---

data/export/admin/atoms/AntDesignIcon.json
libs/frontend/application/atoms/src/ant-design/icon/AntdIcon.ts

AntDesignIcon atom was missing the `name` property, making it impossible to use. I tried to add the `name` property as an `Enum` type, but there were ~1000 options, and currently our db can't handle that many entities and it crashed during import with an errror:
`Error: There is not enough memory to perform the current task. Please try increasing 'server.memory.heap.max_size' in the neo4j configuration (normally in 'conf/neo4j.conf' or, if you are using Neo4j Desktop, found through the user interface) or if you are running an embedded installation increase the heap by using '-Xmx' command line flag, and then restart the database.
at Model.create (/Users/vladyslav/Desktop/builder/node_modules/@neo4j/graphql-ogm/dist/classes/Model.js:124:19)
at process.processTicksAndRejections …

fix: allow to use antd icon atom

---

libs/frontend/domain/element/src/use-cases/element/delete-element/DeleteElementModal.tsx

Fixed `Rendered fewer hooks than expected.` script error because an early return statement existed before other hooks.
Another part of the issue was when the `parent` property was used to set the parent of the delete element as the currently selected builder node, but `parent` exists only for the first child. `closestParent` is used instead, which first will traverse to the first child and then get `parent`.
https://github.com/codelab-app/platform/assets/74900868/cd6ec5e9-2e97-4c46-b60d-bbc452d3829b
Fixes #2602

fix: script error on second child element deleting

---

apps/platform-e2e/src/e2e/component.cy.ts
libs/frontend/domain/page/src/view/PageDetailHeader.tsx

- Fix providersPage spec by updating the builder header. Before headers refactoring the root node of it was `header`, but after refactoring it became `div`, and the selector in e2e spec started to fail. Since semantically it is more valid to use `header` in this case - instead of updating e2e I decided to update platform code.
- Fix components spec selector to rely on data-id attribute instead of id, because tab ids are sensetive to the initialization order (if the tabs component is initialized first on the component tree - antd includes `0` in the id, for the second tab - `1` and so forth). So previously the selector was `#rc-tabs-2-tab-custom-components` but after refactoring in past PRs the id changed to `#rc-tabs-6-tab-custom-components`. I think new selector is less sensetive and …

fix: failing e2e specs

---

.eslintignore
.eslintrc.json

use overrides to ignore pages from name conventions 
Fixes #2660

fix: use overrides to ignore pages from name conventions

---

libs/shared/config/src/env/env-platform.ts
terraform/modules/vercel-platform/project.tf
terraform/modules/vercel-websites/project.tf

The problem is that when PR gets merged and a new production build is triggered after the merge - the production build uses a cache from the preview build (preview of the PR that is merged) and produces invalid artifacts. The login issue (but this is not the only problem because of the same root cause) occurs because the production build used the values for system environment variables from preview deployment of merged PR, like NEXT_PUBLIC_VERCEL_ENV, VERCEL_URL. For example, NEXT_PUBLIC_VERCEL_ENV was `preview` instead of `production`, and VERCEL_URL pointed to the previous deployment (to deployment of the source branch).
Also when opening production - because of invalid Environment variable values, client makes request to a preview back-end:
The login issue occurs because the invalid …

fix: skip Vercel build cache for production deployments

---

libs/frontend/domain/element/src/use-cases/element/update-element-props/UpdateElementPropsForm.tsx
libs/frontend/presentation/container/src/pageHooks/useRenderedPage.hook.ts

After types loading refactoring - types were not loaded anymore for components tabs. This caused a script error in an attempt to render the Props form for the element in the component builder because the field type was missing.
Reuse types loading logic that is used for rendering pages to load only required types when the form is loaded.
Fixes #2671

fix: script error because of missing types

---

libs/frontend/abstract/core/src/domain/action/base-action.interface.ts
libs/frontend/abstract/core/src/domain/render/action.runner.model.interface.ts
libs/frontend/abstract/core/src/domain/render/index.ts
libs/frontend/abstract/core/src/domain/render/renderer.model.interface.ts
libs/frontend/domain/builder/src/sections/explorer-pane/BuilderPrimarySidebar.tsx
libs/frontend/domain/builder/src/sections/explorer-pane/ComponentsExplorerPane.tsx
libs/frontend/domain/builder/src/sections/explorer-pane/StorePane.tsx
libs/frontend/domain/renderer/src/action-runner.model.ts
libs/frontend/domain/renderer/src/element-runtime-props.model.ts
libs/frontend/domain/renderer/src/index.ts
libs/frontend/domain/renderer/src/renderer.model.ts
libs/frontend/domain/renderer/src/test/conditional-render-pipe.spec.ts
libs/frontend/domain/renderer/src/test/setup/setup-test.ts
libs/frontend/domain/renderer/src/test/typed-prop-tranformers.spec.ts
libs/frontend/domain/renderer/src/typedPropTransformers/action-type-transformer.ts
libs/frontend/domain/renderer/src/utils/should-render-element.ts
libs/frontend/domain/store/src/store/action.service.ts
libs/frontend/domain/store/src/store/models/api-action.model.ts
libs/frontend/domain/store/src/store/models/base-action.model.ts
libs/frontend/domain/store/src/store/models/code-action.model.ts
libs/frontend/domain/store/src/store/models/store.model.ts
libs/frontend/domain/type/src/interface-form/type-schema.factory.ts
libs/frontend/presentation/container/src/routerHooks/useCurrentApp.hook.ts
libs/frontend/shared/utils/src/state-expressions.ts

- In expressions and in actions component props are accessible via `props.[propName]`
- add action runner to enable us inject props into actions during render
- in typed props `type` property wasn't submitted by form until I added `required`.
- Action Modals wasn't working as expected therefor they were moved to the correct place. (maybe will change with the upcoming UI)
- Action model is now a pure data model
Fixes #
- #2696
- #2733

feat: allow actions access props

---

apps/platform/pages/apps/index.tsx
libs/backend/application/admin/src/use-case/import-admin-data/import-admin-data.service.ts
libs/frontend/domain/element/src/store/element.model.ts
libs/frontend/presentation/codelab-ui/src/views/CuiHeaderToolbar/CuiHeaderToolbarItem.tsx

The request for components is not a part of the request for page elements, as a result, page data is loaded first and only then request for components is made. And the UI crashed because of `.current` throw an error (the component did not exist in the store yet). Replace `.current` with `.maybeCurrent` to avoid errors while components being loaded
Fixes #2718

fix: script error on a page with component instance

---

libs/frontend/presentation/container/src/routerHooks/useCurrentApp.hook.ts
libs/frontend/presentation/container/src/routerHooks/useCurrentPage.hook.ts
package.json
yarn.lock

`App` app name has slug `app`. And during to previous logic the name out of the `app` slug was reversed to `_app`, which is not correct, this is applicable only for pages where we have provider page "_app" which does not follow common convention for pages naming.
Fixes #2724

fix: can't open app with name "App"

---

libs/frontend/domain/type/src/interface-form/fields/select-union-type-value/SelectUnionTypeValue.tsx

Fixes the following issues.
- Nested props are not saved
- UnionType can be saved without a value
Fixes #2726

fix: nested props are not saved

---

data/export/admin/atoms/HtmlScript.json
scripts/vercel/landing/build.sh
scripts/vercel/platform-api-next/build.sh
scripts/vercel/platform/build.sh
scripts/vercel/websites/build.sh

Allow users to specify `onload` and `onerror` callbacks for scripts.
Use case example: now I can load supabase script, and initialize supabaseClient once it is loaded and set the instance to the store. After this I am able to fetch data from supabase using this instance
Fixes #2737

refactor: allow to set callback on script load/error

---

apps/platform-e2e/src/e2e/builder.cy.ts
apps/platform-e2e/src/e2e/component.cy.ts
apps/platform-e2e/src/e2e/css.cy.ts
libs/backend/domain/type/src/model/interface-type.model.ts
libs/backend/infra/adapter/neo4j/src/resolver/pure-resolver/app/field/app-slug.ts
libs/backend/infra/adapter/neo4j/src/resolver/pure-resolver/page/field/page-slug.ts
libs/frontend/domain/app/src/store/app.model.ts
libs/frontend/domain/page/src/store/page.model.ts
libs/frontend/domain/page/src/store/page.service.ts
libs/frontend/presentation/container/src/routerHooks/useCurrentApp.hook.ts
libs/frontend/presentation/container/src/routerHooks/useCurrentPage.hook.ts
libs/shared/utils/src/transform/strings.ts

Added custom implementation of `slugify` method because we can't rely on voca.slugify.
There are collisions, for example for strings like `My1 App`, `My1app`, `My 1 App` the same slug is generated `my-1-app` and we can't reverse it back to the original string.
The new implementation will generate `my1-app`, `my1app`, `my-1-app`
https://github.com/codelab-app/platform/assets/74900868/0c84a69b-8f10-4582-8c7b-98ba17c0e8cb
Fixes #2745

fix: can't open apps with digits in name

---

.circleci/config/jobs/e2e.yml
apps/landing/project.json
apps/platform-api-next/project.json
apps/platform-e2e/project.json
apps/platform-e2e/src/e2e/builder.cy.ts
apps/platform-e2e/src/e2e/css.cy.ts
apps/platform/project.json
apps/websites/project.json
libs/backend/domain/user/src/model/user.model.ts
libs/frontend/abstract/core/src/domain/type/json-schema/typed-prop.interface.ts
libs/frontend/domain/renderer/src/base-runtime-props.model.ts
libs/frontend/domain/renderer/src/test/setup/setup-test.ts
libs/frontend/domain/renderer/src/test/typed-prop-tranformers.spec.ts
libs/frontend/domain/type/src/interface-form/type-schema.factory.ts
libs/frontend/domain/type/src/store/tests/schema.data.ts
libs/frontend/presentation/container/src/pageHooks/useRenderedPage.hook.ts
scripts/nx/reset-cache.sh

- The problem in `loadAllTypesForElements` was that `getComponentIdsFromProp` always returned ids of other entities like actions where it should return only component ids which made the loop to never end.  
Fixes #2735

fix: infinite loop on load all types for elements

---

libs/frontend/domain/type/src/interface-form/fields/select-default-value/SelectDefaultValue.tsx

Fixes the following problems with default values for types.
1. Default values form not shows up when adding a new field to the api
2.  ~~Default values not pre-populated when there's no value set for a field~~ (seems to be fixed in recent prs)
3. Default values are not added to the props as the value of the field. So field value (default value) is effectively useless unless updated.
Fixes #2755

default value issues

---

libs/backend/infra/adapter/neo4j/src/resolver/pure-resolver/action/action.resolver.ts
libs/backend/infra/adapter/neo4j/src/resolver/pure-resolver/action/index.ts
libs/backend/infra/adapter/neo4j/src/resolver/pure-resolver/pure-resolvers.ts
libs/backend/infra/adapter/neo4j/src/schema/model/element.schema.ts
libs/backend/infra/adapter/neo4j/src/selectionSet/element-selection-set.ts
libs/frontend/abstract/core/src/domain/element/element.fragment.graphql
libs/frontend/abstract/core/src/domain/element/element.fragment.graphql.gen.ts
libs/frontend/abstract/core/src/domain/element/element.model.interface.ts
libs/frontend/domain/element/src/store/element.model.ts
libs/frontend/domain/element/src/use-cases/element/create-element/CreateElementForm.tsx
libs/frontend/domain/element/src/use-cases/element/create-element/create-element.schema.ts
libs/frontend/domain/element/src/use-cases/element/update-element/UpdateElementForm.tsx
libs/frontend/domain/element/src/utils/get-element-model.ts
libs/frontend/domain/renderer/src/element/element-wrapper.ts
libs/frontend/domain/renderer/src/renderer.model.ts
libs/frontend/domain/type/src/interface-form/fields/select-action/SelectAction.tsx
libs/frontend/domain/type/src/interface-form/fields/select-action/SelectActionField.tsx
libs/frontend/domain/type/src/interface-form/fields/select-action/index.ts
libs/frontend/domain/type/src/interface-form/ui-properties/action-type-ui-properties.ts
libs/shared/abstract/codegen/src/types.api.graphql.gen.ts

Implemented preRenderAction (executed in `renderElement` before element is starting to render) and postRenderAction (executed in `useEffect` with `[]`).
https://github.com/codelab-app/platform/assets/74900868/2ce554d8-4992-4ad3-ac26-90624dd2621c
Fixes #2738

feat: implement preRenderAction and postRenderAction

---

libs/frontend/domain/store/src/store/action.service.ts
libs/frontend/presentation/codelab-ui/src/views/CuiCollapse/CuiCollapse.tsx
libs/frontend/presentation/codelab-ui/src/views/CuiCollapse/CuiCollapsePanelContent.tsx
libs/frontend/presentation/codelab-ui/src/views/CuiSidebarToolbar/CuiSidebarToolbarItem.tsx
libs/frontend/presentation/codelab-ui/src/views/CuiTree/CuiTreeItemToolbar/CuiTreeItemToolbarItem.tsx

- When new action was created - it was not attached to corresponding store and as a result it did not show up in sidebar "Actions" panel
- Also fixed a couple of script errors related to missing "key" attribute
https://github.com/codelab-app/platform/assets/74900868/5cce008c-a34a-42c2-938f-f292ad04263b
Fixes #2765

fix: attach new actions to corresponding stores

---

libs/frontend/domain/app/src/services/app.repo.ts
libs/frontend/domain/atom/src/store/atom.repo.ts
libs/frontend/domain/resource/src/store/resource.repo.ts
libs/frontend/shared/utils/src/client-cache.ts

Fix caching decorators to match the newer TS version, as a result, they became more compact and a bit simpler.
Also removed the `modelFlow` decorator from API methods, since they do not alter store.
Fixes #2638

fix: caching decorators after TS version change

---

libs/frontend/domain/app/src/store/app.service.ts

The issue was that `loadAppsWithNestedPreviews` did not load descendant elements to the store and when the app was deleted - an error was thrown on an attempt to iterate over all page descendant elements because it could not resolve refs.
As a solution - `loadAppsWithNestedPreviews` is updated to load all elements to store, to keep the state valid and avoid script errors about unresolved refs
Stable steps to reproduce issue
https://github.com/codelab-app/platform/assets/74900868/6873fc5a-d7ff-49ad-9b53-1a1534e8367e
After the fix
https://github.com/codelab-app/platform/assets/74900868/3cde88d2-8cb9-4f92-82bc-040c56dc4e5a
Fixes #2782

fix: load descendant page elements on app load

---

libs/frontend/domain/type/src/interface-form/type-schema.factory.ts

It was not possible to add boolean field before, because default value for it was "undefined" but it was required by ajv schema. As a result the form was not submited and validation error was shown (see video in the github issue). As a solution - for boolean props used default "false" value instead of "undefined"
https://github.com/codelab-app/platform/assets/74900868/3aeabf4f-2f93-47d9-9595-a5449e3424ad
Fixes #2764

fix: use "false" instead of undefined as default value for boolean prop 

---

apps/platform/pages/api/import/app.ts
libs/backend/domain/action/src/repository/action.repo.ts
libs/backend/domain/app/src/repository/app.repo.ts
libs/frontend/domain/app/src/use-cases/import-app/ImportAppDialog.tsx
libs/frontend/domain/app/src/use-cases/import-app/import-app.api.ts

- Fixes #2808 , store actions were not imported since we migrated store to be per page instead of single store for application
- Fixes #2809 , the error was thrown since not all imported app was loaded to store (pages were not loaded and attempt to access a page threw the error).
- Also implemented loading indicator while app import or refreshing app list after import is in progress
https://github.com/codelab-app/platform/assets/74900868/14a8b988-0e19-4aa0-b045-523f888b5bb4
Fixes #2808 
Fixes #2809

fix: actions import and script error

---

libs/frontend/domain/prop/src/store/prop.model.ts
libs/frontend/domain/renderer/src/action-runner.model.ts
libs/frontend/domain/renderer/src/element-runtime-props.model.ts
libs/frontend/domain/renderer/src/renderer.model.ts
libs/frontend/shared/utils/src/try-parse.ts

This is for being able to render the component from the child mapper with filtering logic. The filtering logic could be from via action code or a REST endpoint with query for filtering
Fixed:
- cached prop data issue for the component instances that got rendered after filtering
- evaluating the rest api config with the state expressions
Demo: All products are fetched via pre-render action and only called once. The filtering is done via code actions so theres no extra calls
https://github.com/codelab-app/platform/assets/27695022/c5aab808-3955-4386-bb97-e33a7aa14b4c
<br />
Demo: Products are filtered via passing a query param `name` to the API endpoint.
https://github.com/codelab-app/platform/assets/27695022/52b4e410-de82-4703-953d-901d1a6088d3
Fixes #2784

fix: child mapper rendering with filtered data

---

libs/backend/abstract/codegen/src/ogm-types.gen.ts
libs/backend/domain/element/src/model/element.model.ts
libs/backend/infra/adapter/neo4j/src/schema/model/element.schema.ts
libs/backend/infra/adapter/neo4j/src/selectionSet/element-selection-set.ts
libs/frontend/abstract/core/src/domain/element/element.dto.interface.ts
libs/frontend/abstract/core/src/domain/element/element.fragment.graphql
libs/frontend/abstract/core/src/domain/element/element.fragment.graphql.gen.ts
libs/frontend/abstract/core/src/domain/element/element.model.interface.ts
libs/frontend/domain/builder/src/sections/explorer-pane/builder-tree/ElementTreeView.tsx
libs/frontend/domain/element/src/components/ChildMapperCompositeField.tsx
libs/frontend/domain/element/src/components/SelectLinkElement.tsx
libs/frontend/domain/element/src/store/element.model.ts
libs/frontend/domain/element/src/store/element.service.ts
libs/frontend/domain/element/src/use-cases/element/update-element/UpdateElementForm.tsx
libs/frontend/domain/element/src/use-cases/element/update-element/update-element.schema.ts
libs/frontend/domain/element/src/utils/get-element-model.ts
libs/frontend/domain/renderer/src/renderer.model.ts
libs/frontend/presentation/codelab-ui/src/views/CuiTree/CuiTree.tsx
libs/shared/abstract/codegen/src/types.api.graphql.gen.ts
libs/shared/abstract/core/src/element.dto.interface.ts
schema.graphql

- added a new field `childMapperPreviousSibling` to select where to render the instances of the child mapper
- only the children of the element can be selected
- disable drag and drop of the child mapper instance nodes in the tree view
https://github.com/codelab-app/platform/assets/27695022/63b92e4a-3861-40fd-b89e-11d17dd340bb
Fixes #2783

feat: move child mapper instances around

---

apps/platform/pages/api/export/component.ts
libs/backend/application/admin/src/use-case/export-admin-data.service.ts
libs/frontend/domain/component/src/use-cases/get-components/columns/ActionColumn.tsx

The current implementation of component export saves the exported component to the codebase. This pr changes the implementation to download the file instead. 
Fixes #2796

fix: download components when exported from ui

---

apps/platform-e2e/src/e2e/builder.cy.ts

Tests for the child mapper logic
Fixes #2801

chore: e2e test for child mapper logic

---

libs/frontend/domain/element/src/components/SelectLinkElement.tsx

It seems this was caused due to some changes for the SelectLinkElement component that is used for the child mapper logic.
Somehow if the `onChange` passed to the uniform-antd's SelectField is `undefined`, it still tries to run the [props.onChange](https://github.com/vazco/uniforms/blob/master/packages/uniforms-antd/src/SelectField.tsx#L76). Its probably some bug in uniform-antd. But this can be fixed on our end by not setting the `onChange` prop if it is undefined
https://github.com/codelab-app/platform/assets/27695022/b656b4e2-d0d3-46cf-9904-eae14b3a244a
Fixes #2822

fix: select link element

---

libs/frontend/domain/renderer/src/element/get-styled-components.ts

Turned out that the issue is caused by `styled` from `styled-component` that we wrap the elements before rendering. When an element is rendered conditionally, a `Framgent` component is rendered, which is not wrapped with `styled` anymore. `styled` uses hooks internally so this causes a mismatch in the number of hooks rendered in each render. 
https://github.com/codelab-app/platform/assets/48331678/aa6c7aae-49f2-44af-b33f-db4ebfdd58ac
Fixes #2807

fix: elements not rendered conditionally

---

libs/frontend/presentation/container/src/routerHooks/useCurrentApp.hook.ts

`useCurrentApp` hook used inside `useMemo` with missing dependency.
The first time `useCurrentApp` was executed - app was not loaded yet and it memoized `app` as `undefined`. But after app finished loading - the memo was not trigered to update and still returned `undefind`.
Because of this app.id was not populated on form and domain was impossible to create
https://github.com/codelab-app/platform/assets/74900868/a4b1d119-9b4f-4f8f-a502-71f15962e1d2
Fixes #2829

fix: useMemo missing dependencies

---

.docker/docker-compose.yaml
scripts/docker/build.sh
scripts/docker/push.sh
scripts/docker/up.sh

Remove `name` which is not supported by most `docker-composer` versions.
Fixes #2820

fix: docker up command

---

apps/platform-e2e/src/e2e/builder.cy.ts
libs/frontend/abstract/core/src/domain/component/component.ref.ts
libs/frontend/abstract/core/src/domain/element/element.model.interface.ts
libs/frontend/abstract/core/src/domain/render/action.runner.model.interface.ts
libs/frontend/domain/builder/src/sections/explorer-pane/BuilderPrimarySidebar.tsx
libs/frontend/domain/element/src/store/element.model.ts
libs/frontend/domain/element/src/use-cases/element/update-element/UpdateElementForm.tsx
libs/frontend/domain/renderer/src/action-runner.model.ts
libs/frontend/domain/renderer/src/element-runtime-props.model.ts
libs/frontend/domain/renderer/src/element/element-wrapper.ts
libs/frontend/domain/renderer/src/renderer.model.ts
libs/frontend/domain/renderer/src/typedPropTransformers/action-type-transformer.ts
libs/frontend/domain/renderer/src/utils/should-render-element.ts
libs/frontend/domain/type/src/interface-form/fields/select-action/SelectAction.tsx
libs/frontend/shared/utils/src/state-expressions.ts
libs/shared/data/test/src/page.data.ts

State from the provider page can be accessed via `rootState.[propName]`. The state from the provider page will be included on evaluating the runtime props of an element.
The actions from the provider page are also included in the options to choose from in the SelectActions fields in a regular page.
Also updated the inspector tab in the explorer to show the state values from the local store, component store, and provider store so users can see all the state values it can use
Added e2e tests for testing that the state created from the provider page is accessible in a regular page.
Using the `products` state from the provider as the child mapper prop in a regular page.
https://github.com/codelab-app/platform/assets/27695022/5332e43f-bbc1-4073-ade2-b1ba14125764
<br />
Updated inspector to …

feat: state sharing between pages

---

apps/platform/pages/api/export/app.ts
libs/backend/application/type/src/use-case/export/export-user-types.ts
libs/backend/application/type/src/use-case/import/import-user-types.ts
libs/backend/application/type/src/use-case/import/index.ts
libs/backend/application/type/src/use-case/index.ts
libs/backend/application/user/src/use-case/export-user-data.ts
libs/backend/application/user/src/use-case/import-user-data.ts
libs/backend/infra/adapter/neo4j/src/cypher/type/getTypeDescendantsOGM.cypher

- Fixed cypher query to get type descendants (`labelFilter` is case sensetive)
- Fixed export of user types and added condition to export only types owned by user
- Implemented import of user types
See video in the issue to see how it worked before.
Now all types exported successfully:
https://github.com/codelab-app/platform/assets/74900868/6d61c1dd-bd7b-4834-87ab-43a5c32504b7
Fixes #2817

fix: user types export on app export

---

libs/frontend/domain/element/src/use-cases/element/update-element/UpdateElementForm.tsx

fix autocomplete of to use state or props instead of this 
https://github.com/codelab-app/platform/assets/47860740/84b0c1df-da6e-428d-a316-1da328597825
Fixes #2832

fix: update autocompletion

---

libs/frontend/domain/renderer/src/element/element-wrapper.ts
libs/frontend/domain/renderer/src/element/get-styled-components.ts
libs/frontend/domain/renderer/src/renderer.model.ts

The entire user component tree was producing new nodes on each re-render. This happened because we dynamically wrapped all elements with `styled()`. This is not how the styled-components were intended to use, because `styled()` produces each time new component (impossible to use `useMemo` for it because then error is thrown about changed rendered hooks count). This was the reason why it was impossible to use controlled components (the input loses focus on each new key pressed because new input is created on each state update). Now the styled component is created only once, and using `as` property we pass to it which component we want to render and by `css` prop we control set of css rules to be applied.
Also, to avoid script errors and allow React to effectively patch user elements - …

fix: controlled components

---

libs/frontend/domain/builder/src/sections/content/Builder.tsx
libs/frontend/domain/builder/src/sections/overlay-toolbar/BuilderClickOverlay.tsx
libs/frontend/domain/builder/src/sections/overlay-toolbar/BuilderHoverOverlay.tsx
libs/frontend/presentation/view/components/hoverOverlay/ClickOverlay.tsx
libs/frontend/presentation/view/components/hoverOverlay/HoverOverlay.tsx
libs/frontend/presentation/view/components/hoverOverlay/OverlayToolbar.tsx
libs/frontend/presentation/view/components/hoverOverlay/index.ts
libs/frontend/presentation/view/components/hoverOverlay/overlay.interface.ts

Rerender overlay when:
- element is resized
- the page is resized
- the content is scrolled
Also commented out unused components.
Before: 
https://github.com/codelab-app/platform/assets/74900868/5b8aa52f-1ed3-410b-9971-f0d619f127ba
After:
https://github.com/codelab-app/platform/assets/74900868/2e435cf5-cc4d-4e08-9a61-d2a0cf3dac5e
Fixes #2844 
Fixes #2855

fix: re-render overlay on resize and scroll

---

.yarnrc.yml
dist/libs/tools/workspace/package.json
libs/frontend/abstract/core/src/domain/atom/atom.repo.interface.ts
libs/frontend/abstract/core/src/domain/atom/atom.service.interface.ts
libs/frontend/domain/atom/src/graphql/atom.endpoints.graphql
libs/frontend/domain/atom/src/graphql/atom.endpoints.graphql.gen.ts
libs/frontend/domain/atom/src/store/atom.repo.ts
libs/frontend/domain/element/src/use-cases/element/move-element/MoveElementForm.tsx
libs/frontend/domain/type/src/interface-form/fields/select-atom/SelectAtom.tsx
libs/shared/abstract/codegen/src/types.api.graphql.gen.ts
libs/tools/workspace/package.json
package.json
scripts/yarn/after-install.sh
yarn.lock

Some atoms can only under certain atoms. For example, Form.Item goes under Form. We are using the `requiredParents` field to validate if a child atom can go under a parent atom. Below are four cases that we're handling:
1. Only display the atoms if their required parents include the parent 
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/c13139bd66a64fa1b143a77b6f5d2ed2-00001.gif)](https://www.loom.com/share/c13139bd66a64fa1b143a77b6f5d2ed2)
2. Only display the atoms if the required parents of the parent doesn't include the atom 
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/c7e5c8e42dcf4a69984ab2ce1f17a09f-00001.gif)](https://www.loom.com/share/c7e5c8e42dcf4a69984ab2ce1f17a09f)
3. Only display the atoms without required parents 
[![LOOM …

feat: add atom parent and child validation

---

libs/frontend/abstract/core/src/domain/type/json-schema/typed-prop.interface.ts
libs/frontend/domain/renderer/src/typedPropTransformers/action-type-transformer.ts
libs/frontend/domain/renderer/src/typedPropTransformers/react-node-type-transformer.ts
libs/frontend/domain/renderer/src/typedPropTransformers/render-prop-type-transformer.ts
libs/frontend/domain/type/src/interface-form/fields/select-union-type-value/SelectUnionTypeValue.tsx
libs/frontend/presentation/container/src/pageHooks/useRenderedPage.hook.ts

Fixes the following issues with `UnionType` in forms.
Fixes #2847

fix: UnionType issues

---

libs/frontend/domain/renderer/src/element/element-wrapper.ts

- Allow refs to be attached to render element instead of being blocked by `ElementWrapper`.
Fixes #2905

fix: form submit

---

libs/frontend/presentation/view/templates/Dashboard/DashboardTemplate.tsx

It appears to be a known issue - https://github.com/ant-design/ant-design/issues/8937. After it was fixed - AntDesign documentation recommends to use this approach when `Layout` is used on page with SSR:
Behaviour before:
https://github.com/codelab-app/platform/assets/74900868/5399a681-ecac-4831-90fc-d4cc0b0947d8
After fix:
https://github.com/codelab-app/platform/assets/74900868/cc4ed12c-1f55-4f5e-9c83-8566456a79df
Fixes #2899

fix: set hasSider flag to avoid flickering

---

libs/frontend/domain/element/src/store/element.service.ts
libs/frontend/domain/element/src/use-cases/element/update-element-props/UpdateElementPropsForm.tsx
libs/frontend/presentation/container/src/pageHooks/useRenderedComponent.hook.ts
libs/frontend/presentation/container/src/pageHooks/useRenderedPage.hook.ts

Fixed 2 issues in this PR:
1. The problem that the interface and corresponding fields were not loaded for Body at all (for renderType)
2. The problem when renderType interface and fields were not loaded on element *update*: when the user changes renderType to an atom that was not used on the current page before, this results in the same script error because could not resolve interface type for that atom
https://github.com/codelab-app/platform/assets/74900868/c40fa740-4a39-4bd9-8e12-747a25a5eb08
Fixes #2893

fix: script error on adding renderType to Body

---

libs/frontend/presentation/view/components/form/components/Form.tsx

Show inline errors to indicate what was the reason for the field to become invalid
https://github.com/codelab-app/platform/assets/74900868/3b75d174-37a9-4a4c-a477-64fd8c333e29
Fixes #2913

fix: show errors for inline forms

---

libs/frontend/domain/renderer/src/action-runner.model.ts
libs/frontend/domain/renderer/src/element/element-wrapper.ts
libs/frontend/domain/renderer/src/renderer.model.ts

Need to lookup for preRender/postRender actions in rootStore if the action was not found in regular page store.
https://github.com/codelab-app/platform/assets/74900868/d07b7ecf-abab-4d59-9afc-de68f182a7d5
Fixes #2918

fix: allow to execute pre-/post- actions from _app

---

apps/platform-e2e/src/e2e/component/component.cy.ts
apps/platform-e2e/src/e2e/component/convert-element-to-component.cy.ts
libs/frontend/domain/element/src/store/element.service.ts

This fixes converting an element to a component.
As mentioned in the issue, we were detaching an element to its parent then calling the mutation, which causes this [error](https://github.com/codelab-app/platform/blob/3397cb3cf545a6a89456a9ac8ee51789d2f161a4/libs/frontend/domain/element/src/store/element.model.ts#L210) to throw. This is fixed by calling the mutation later, once the element's parent/sibling connection is updated.
The mutation midway causes the tree to be re-rendered while the operation is being processed inside the mobx-keystone transaction, so we should do the mutation only once the element data locally is fully updated.
https://github.com/codelab-app/platform/assets/27695022/fd04c7c2-9cc9-4b81-a486-27c1fbbe84eb
Fixes #2474

fix: converting element to a component

---

libs/frontend/abstract/core/src/domain/action/action.service.interface.ts
libs/frontend/abstract/core/src/domain/type/field/field.service.interface.ts
libs/frontend/domain/element/src/store/element.service.ts
libs/frontend/domain/store/src/store/action.factory.ts
libs/frontend/domain/store/src/store/action.service.ts
libs/frontend/domain/type/src/store/field.service.ts

When converting an element to a component:
To achieve this clones of all actions and state fields are created and added to the newly created component store.
Fixes #2896

wip: clone actions when converting to component

---

libs/frontend/domain/builder/src/sections/explorer-pane/ElementContextMenu.tsx
libs/frontend/domain/builder/src/sections/explorer-pane/builder-tree/ElementTreeItemElementTitle.tsx
libs/frontend/domain/builder/src/sections/explorer-pane/builder-tree/ElementTreeItemTitle.tsx
libs/frontend/domain/element/src/store/element.model.ts

Currently, the element tree view doesn't display any assigned ReactNode props, making it challenging for users to determine which component is in use. To improve clarity, the ReactNodes should be made visible within the element tree, enabling users to easily identify the specific  components being used.
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/798a64a189764836b3f5f7a04a9ceab4-00001.gif)](https://www.loom.com/share/798a64a189764836b3f5f7a04a9ceab4)
Fixes [#2933](https://github.com/codelab-app/platform/issues/2933)

feat: show assigned ReactNode props in the element tree view

---

apps/platform-e2e/src/e2e/builder/form.cy.ts
apps/platform-e2e/src/support/builder/builder.command.ts
libs/backend/abstract/codegen/src/ogm-types.gen.ts
libs/backend/domain/element/src/model/element.model.ts
libs/backend/infra/adapter/neo4j/src/resolver/pure-resolver/element/element.resolver.ts
libs/backend/infra/adapter/neo4j/src/resolver/pure-resolver/element/field/ref-key.ts
libs/backend/infra/adapter/neo4j/src/schema/model/element.schema.ts
libs/backend/infra/adapter/neo4j/src/selectionSet/element-selection-set.ts
libs/frontend/abstract/core/src/domain/element/element.dto.interface.ts
libs/frontend/abstract/core/src/domain/element/element.fragment.graphql
libs/frontend/abstract/core/src/domain/element/element.fragment.graphql.gen.ts
libs/frontend/abstract/core/src/domain/element/element.model.interface.ts
libs/frontend/domain/element/src/store/element.model.ts
libs/frontend/domain/element/src/use-cases/element/create-element/create-element.schema.ts
libs/frontend/domain/element/src/use-cases/element/update-element/UpdateElementForm.tsx
libs/frontend/domain/element/src/use-cases/element/update-element/update-element.schema.ts
libs/frontend/domain/element/src/utils/get-element-model.ts
libs/frontend/domain/renderer/src/element-runtime-props.model.ts
libs/frontend/domain/renderer/src/test/renderer.spec.ts
libs/frontend/domain/store/src/store/models/store.model.ts
libs/frontend/domain/type/src/interface-form/ui-properties/primative-ui-properties.ts
libs/frontend/shared/utils/src/dynamic-loader.ts
libs/shared/abstract/codegen/src/types.api.graphql.gen.ts
libs/shared/abstract/core/src/element.dto.interface.ts
schema.graphql

- Remove `element.refKey` and use `element.slug` instead
Fixes #2968

refactor: use element slug for refs

---

.nxignore

Looks like ignoring the `tools-workspaces` in dist fixes the issue since nx will not see the `tools-workspaces` having a duplicate project name.
Just tried the [.nxignore](https://nx.dev/reference/nxignore) and it works.
There will be expected failing e2e tests, but we can merge this now and properly fix the e2e tests on another PRs. This should now somehow prevent more failing e2e tests to get to master
Fixes #2983

fix: CI issue about tools-workspace in dist

---

libs/frontend/domain/store/src/store/models/store.model.ts

State should be cached (should not be reset during page navigations, etc.) only for preview and production, while in page/component builder - state should be reset each time it is altered (new prop added/removed, etc), to make sure no outdated information is shown
https://github.com/codelab-app/platform/assets/74900868/0344eb27-4c47-4646-87ce-19c9b1df270c
Fixes #2979

fix: allow state caching for preview and production only

---

libs/frontend/domain/renderer/src/element/get-styled-components.ts
libs/shared/utils/src/transform/strings.ts

We had to convert camelCase in `css` string to kebab-case to be correctly applied. This conversion was done for both keys and values, which caused some of the styles i.e. font-family to not work if the name is two words. 
So now we only convert the keys to kebab-case. 
Fixes #2991

fix: css string values converted to kebab-case

---

libs/frontend/domain/store/src/use-cases/actions/update-action/UpdateActionForm.tsx
libs/frontend/domain/store/src/use-cases/actions/update-action/UpdateActionModal.tsx
libs/frontend/domain/type/src/interface-form/fields/select-action/SelectAction.tsx

- Prevent creating action loop in api actions by allowing only actions that are not already parents for the updated action
- Code actions are not considered because they could involve in loops but still finite using stopping conditions.
Fixes #2953

fix: exclude parent actions from select box

---

libs/frontend/domain/element/src/store/element.service.ts

element parent (page/parentComponent props) is a required property, since unique `_compoundName` is not computed based on it. So we can't omit it anymore and need to specify it during creation.
https://github.com/codelab-app/platform/assets/74900868/fb933f3f-5c09-4b56-ab65-8e0340529737
Fixes #2995

fix: specify element parent on duplicate

---

libs/frontend/presentation/codelab-ui/src/layout/CuiSidebarPopover/store/cui-popover.store.ts
libs/frontend/presentation/codelab-ui/src/views/CuiPopoverToolbar/CuiPopoverToolbarItem.tsx
libs/frontend/shared/utils/src/inline-form.service.ts
libs/frontend/shared/utils/src/modal.service.ts

When the user opens an inline form/popover and navigates to another page - the popover and form remain opened and show invalid data.
As a fix, implemented a mechanism to close any forms and popovers when navigation to different pages occurs.
https://github.com/codelab-app/platform/assets/74900868/4b12b0e6-a5ed-4526-8795-c27b34eb1bbf
Fixes #2976

fix: hide forms and popovers on navigation

---

libs/frontend/domain/domain/src/static-regeneration.ts
libs/frontend/domain/page/src/use-cases/get-pages/PageTreeItem.tsx

After `app` requests were optimized some time ago - app domains are not always loaded (loaded only on `/apps` page), so need to request domains in case they are not loaded yet before trying to build page for production
https://github.com/codelab-app/platform/assets/74900868/cf6bdd6b-4776-4814-a41a-6286bb4ca6ff
Fixes #2944

fix: build app for production does not work

---

libs/frontend/domain/renderer/src/element/text-editor/TextRenderer.tsx
libs/frontend/domain/renderer/src/element/wrapper.utils.ts
libs/frontend/domain/renderer/src/renderer.model.ts
libs/frontend/domain/shared/src/inline-form.service.ts
package.json
yarn.lock

In builder we use `@editorjs/editorjs` package, it is a powerful editor, but it performs poorly in production.
It does not handle content updates from outside (like when the state changes and we need to replace it inside the editor).
So use a lightweight viewer without editing capabilities that handles updates better.
https://github.com/codelab-app/platform/assets/74900868/029ea1dc-6462-48fc-b9d0-2c52d86e9cab
Fixes #3001

fix: use lightweight text viewer for preview and production

---

libs/frontend/domain/builder/src/sections/overlay-toolbar/BuilderClickOverlay.tsx
libs/frontend/presentation/view/components/hoverOverlay/ClickOverlay.tsx

Whenever selected element is moved on the page, or whenever breakpoint changes - update the selected element overlay
https://github.com/codelab-app/platform/assets/74900868/de970b2b-bb46-43af-bca9-471704ffece6
Fixes #3016

fix: update overlay on position/breakpoint change

---

libs/backend/application/atom/src/use-case/import-atom.command.service.ts
libs/backend/application/type/src/use-case/import/import-api.command.service.ts
libs/frontend/abstract/core/src/domain/tag/tag.fragment.graphql
libs/frontend/abstract/core/src/domain/tag/tag.fragment.graphql.gen.ts
libs/frontend/domain/app/src/use-cases/app-development/app-development.service.ts
libs/frontend/domain/atom/src/use-cases/get-select-atom-options/get-select-atom-options.endpoints.graphql.gen.ts
libs/frontend/domain/tag/src/store/tag.service.ts
libs/shared/abstract/codegen/src/types.api.graphql.gen.ts

This PR fixes issues with error during importing types and atoms to the DB, and errors with opening Apps
- during atoms and types import, use `name` instead of id to upsert. ReactFragment already exists in the database by the moment the import command is run, and the ReactFragment is seeded with a random id, and error was thrown when it was seeded with a different ID during import.
- comment out tag.isRoot for now
- after codegen command was run - it appeared that one file was not committed, so it was added in this PR
- add a missing reference to the page for elements. Without it, an error is thrown on an attempt to render a page
Fixes #

fix: import fails and apps does not open

---

libs/backend/domain/prop/src/model/prop.model.ts
libs/frontend/domain/app/src/use-cases/create-app/CreateAppModal.tsx
libs/frontend/domain/atom/src/store/atom.model.ts
libs/frontend/domain/builder/src/sections/content/Builder.tsx
libs/frontend/domain/builder/src/sections/overlay-toolbar/BuilderClickOverlay.tsx
libs/frontend/domain/builder/src/sections/overlay-toolbar/BuilderHoverOverlay.tsx
libs/frontend/domain/builder/src/sections/overlay-toolbar/index.ts
libs/frontend/domain/builder/src/store/builder.service.ts
libs/frontend/domain/renderer/src/element/wrapper.utils.ts
libs/frontend/domain/renderer/src/utils/useDragDropHandlers.hook.ts
libs/frontend/domain/renderer/src/utils/useSelectionHandlers.hook.ts
libs/frontend/presentation/view/components/overlay/ClickOverlay.tsx
libs/frontend/presentation/view/components/overlay/index.ts
libs/frontend/presentation/view/components/overlay/overlay.interface.ts
libs/frontend/presentation/view/components/overlay/spacingOverlay/Margins.tsx
libs/frontend/presentation/view/components/overlay/spacingOverlay/Paddings.tsx
libs/frontend/presentation/view/components/overlay/spacingOverlay/index.tsx
libs/frontend/presentation/view/components/overlay/spacingOverlay/shared.ts
libs/shared/data/test/src/app.data.ts

In this PR, we visually represent paddings and margins using differently colored squares. This enables users to easily identify the spacing associated with each element, along with their respective values.
Fixes #2955

2955 display margins and paddings

---

libs/frontend/abstract/domain/src/domain/render/render.interface.ts
libs/frontend/abstract/domain/src/domain/render/renderer.model.interface.ts
libs/frontend/application/renderer/src/element/element-wrapper.ts
libs/frontend/application/renderer/src/renderPipes/pre-render-pipe.ts
libs/frontend/application/renderer/src/renderPipes/render-pipe.base.ts
libs/frontend/application/renderer/src/renderPipes/render-pipe.factory.ts
libs/frontend/application/renderer/src/renderer.model.ts
libs/frontend/application/renderer/src/test/conditional-render-pipe.spec.ts
libs/frontend/application/renderer/src/utils/render-output.ts

This PR apllies the changes proposed in #3005. in addition to that, 
1. The element Wrapper implementatin is simplified:
- ~removed element prop~ reverted this back for now
- added errorBoundary and onRendered props to move some unnecessary logic to outside the element wrapper
2. added methods to run pre/post render methods to renderModel so that the logic is located in close proximity.
Before
https://github.com/codelab-app/platform/assets/51242349/8975d757-7135-44c3-a49a-3fcb084e1f4d
After
https://github.com/codelab-app/platform/assets/51242349/dc622b6a-7113-42ae-a286-32cd35688af6
Fixes #3005

refactor: add pre-render pipe and simplify element wrapper

---

apps/platform/pages/_app.tsx

This PR is to fix the error when selecting or hovering Tailwind classes.
**Before:**
https://github.com/codelab-app/platform/assets/48331678/3b223bdd-bfcb-435f-817b-913dd33a151b
**After:**
https://github.com/codelab-app/platform/assets/32300655/6806df99-4154-4387-a8cf-5a8923eb3901
Fixes #3068

fix: error when selecting tailwind class

---

libs/frontend/application/app/src/use-cases/app-development/useAppDevlopment.hook.ts

When attempting to open an app, if there are multiple apps available, the elements from the first app always load regardless of which app is selected. This issue arises because we are getting the page based on its name alone, rather than using both the name and the app id.
https://github.com/codelab-app/platform/assets/32300655/48b6a9bc-5350-4398-8c3a-6f9e43da7e51
Fixes #

fix: loading incorrect page when opening an app

---

libs/frontend/application/renderer/src/render.service.ts
libs/frontend/application/renderer/src/renderer.model.ts
libs/frontend/domain/element/src/store/element.model.ts

Issue used to happen because
1. Component props are not attached to the builder unless it is in a `component-builder` mode
2. no element inside the component other than the root had access to the component props no matter what.
1. first component testing component props usage in the root element
2. second component testing component props usage in another element
https://github.com/codelab-app/platform/assets/51242349/5db576be-1b2f-4c3e-8cae-2f39f099d9e7
Fixes #3070

fix: component props undefined in props evaluation context

---

libs/frontend/domain/element/src/store/element.model.ts

This pr fixes 2 issue
1. Setting the render type to a component is not persisted.
2. Changing render type would not cause the removal of the previous render type. Render types are just added to the element instead.
https://github.com/codelab-app/platform/assets/51242349/689feacc-858f-47e1-9799-4d7f6148b912
Fixes #3079

fix: persist element render type in the db

---

libs/frontend/application/atom/src/use-cases/select-atom/SelectAtom.tsx

https://github.com/codelab-app/platform/assets/74900868/f3a926fc-e1da-43b0-aeff-ed8e8dbb0418
Fixes #3086

fix: use existing atoms as fallback in dropdown

---

apps/platform-api/pages/api/data/[[...index]].ts
apps/platform-api/pages/api/graphql.ts
apps/platform/pages/api/[[...index]].ts
apps/platform/pages/api/auth/[...auth0].ts
libs/backend/application/admin/src/use-case/import/import-admin-data.command.service.ts
libs/backend/application/admin/src/use-case/seed-data/seeder.application.service.ts
libs/backend/application/atom/src/use-case/import-atom.command.service.ts
libs/backend/domain/tag/src/repository/tag.repo.service.ts
terraform/modules/vercel-platform-api/project.tf

- fix environment variables for vercel production deployments
- increase `maxDuration` for serverless function on Vercel from 15s to 60s, since requests often rejected by timeout
- fix atoms import: import all atoms without `suggestedChildren` first, and then selectively update atoms that have `suggestedChildren`
- after user logs in - skip `importSystemTypes` and only seed user from request. This speeds up login as well as does not require us to deploy `data/export-v3` folder
- remove redundant request inside of `update` method in tag.repository, since it is not used anymore (previously it was used to get current value of tag `parent` property)
Fixes #

fix: production deployment and import fixes

---

libs/backend/application/atom/src/services/atom.application.service.ts
libs/backend/domain/atom/src/repository/atom.repo.service.ts
libs/backend/infra/core/src/abstract.repository.ts

- an error was thrown during atoms export (too many opened DB connections) because all atoms were imported in parallel. Instead import 10 at a time
- allow to specify `selectionSet` in backend repo classes for more effective queries. In future can benefit from this also by updating `exists` method on all repos to fetch only record `id` instead of getting entire record with all relationships
Fixes #

fix: error during export

---

libs/frontend/application/component/src/services/component.application.service.ts

The [closestContainerNode](https://github.com/codelab-app/platform/blob/da360f07606f0ebef0f758fcf7f0e5253301bb66/libs/frontend/domain/element/src/store/element.model.ts#L231) in [toCreateInput](https://github.com/codelab-app/platform/blob/da360f07606f0ebef0f758fcf7f0e5253301bb66/libs/frontend/domain/element/src/store/element.model.ts#L623) is needed but the current code causes the ref issue for the parent component because it has not been hydrated yet in the cache.
This PR updates the logic so that we only do the mutations after the hydrations in the cache so that the refs are resolved successfully.
~Also includes the fix for the missing `tagDomainServiceContext`  error~ Looks like this has been fixed already by some other PR that just got merged. …

fix: cant create component due to ref issue

---

libs/frontend/domain/type/src/type.domain.service.ts

The interface type in the cache for the atom used for the element was being re-created with a new instance of InterfaceType that causes the current rendered fields in the props config pane to disappear.
https://github.com/codelab-app/platform/assets/27695022/9a7557a5-924d-484a-981f-e659c77e006b
Fixes #3165

fix: element atom props disappearing

---

libs/backend/domain/element/src/repository/element.repo.service.ts
libs/backend/infra/adapter/neo4j/src/resolver/index.ts
libs/backend/infra/adapter/neo4j/src/resolver/ogm-resolver/component/component.resolver.provider.ts
libs/backend/infra/adapter/neo4j/src/resolver/ogm-resolver/element/element.resolver.provider.ts
libs/backend/infra/adapter/neo4j/src/resolver/ogm-resolver/page/page.resolver.provider.ts
libs/backend/infra/adapter/neo4j/src/resolver/tests/component.resolver.i.spec.ts
libs/backend/infra/adapter/neo4j/src/resolver/tests/page.resolver.i.spec.ts
libs/backend/infra/adapter/neo4j/src/resolver/utils/get-descendant-elements.ts
libs/frontend/abstract/domain/src/component/component-development.fragment.graphql
libs/frontend/abstract/domain/src/component/component-development.fragment.graphql.gen.ts
libs/frontend/abstract/domain/src/page/page.fragment.graphql
libs/frontend/abstract/domain/src/page/page.fragment.graphql.gen.ts
libs/frontend/application/app/src/use-cases/app-development/app-development.endpoints.graphql.gen.ts
libs/frontend/application/app/src/use-cases/app-production/app-production.endpoints.graphql.gen.ts
libs/frontend/presentation/container/src/pageHooks/useRenderedComponent.hook.ts
libs/frontend/presentation/container/src/pageHooks/utils.ts
libs/shared/abstract/codegen/src/types.api.graphql.gen.ts
scripts/jest/setupFiles.js

- removes the `descendantElements` resolver since it is not needed anymore after introducing a new field resolver `elements` for the Page and Component type.
- reduce response size by only needing id on `rootElement` on Page and Component when loading the builder
- fix env file used when running jest locally
- the current issue is when using neo4j service, it is using the database used when running the platform locally
Fixes #3161

chore: clean up unused descendantElements

---

libs/backend/application/app/src/app.application.controller.ts
libs/backend/application/atom/src/atom.application.controller.ts
libs/backend/application/tag/src/tag.application.controller.ts
libs/backend/application/type/src/type.application.controller.ts
libs/backend/application/user/src/user.application.controller.ts

Recently the `platform-api` was migrated to digital ocean, and the NestJs wrapper around it was removed.
When NestJs wrapper was used - it had two separate endpoint URLs: /data and /graphql, and for /data endpoint global prefix was defined. But now global prefix is not an option since all the controllers are a part of a global root module. So specify prefix individually.
This /data requests are used in cypress tests to seed the database
Part of #3171

fix: nestjs endpoint prefix after migration

---

apps/platform-e2e/src/e2e/builder/child-mapper.cy.ts
apps/platform-e2e/src/e2e/builder/in-app-routing.cy.ts
apps/platform-e2e/src/e2e/builder/state-sharing.cy.ts
apps/platform-e2e/src/e2e/component/component.cy.ts
apps/platform-e2e/src/e2e/store/actions-inside-code-actions.cy.ts
apps/platform-e2e/src/e2e/store/child-mapper-api-actions-with-props.cy.ts
apps/platform-e2e/src/e2e/store/nested-api-actions.cy.ts
apps/platform-e2e/src/e2e/store/pre-render-api-action-and-set-state.cy.ts
apps/platform-e2e/src/support/commands/builder/builder.command.ts

Do not set "Atom" render type explicitly in e2e tests. The form filed is already pre-populated with this value by default.
Part of #3171

refactor: do not explicitly set "Atom" renderType in e2e

---

apps/platform-e2e/src/e2e/builder/form.cy.ts
apps/platform-e2e/src/e2e/component/convert-element-to-component.cy.ts
apps/platform-e2e/src/e2e/store/child-mapper-api-actions-with-props.cy.ts

- fix invalid import path
- fix error in e2e test when renderType was set to Atom but no atom was selected. Atom can't be skipped anymore, so use ReactFragment
Part of #3171

fix: atom is required as render type

---

libs/frontend/application/renderer/src/renderer.application.service.ts

During renderer hydration - `renderType` property value is not updated. As a result, when switching from builder mode to preview mode - expressions are not evaluated (the render type remains 'builder').
Before:
https://github.com/codelab-app/platform/assets/74900868/7a45905a-807a-4ed2-b52d-a1a5cbd011d9
After:
https://github.com/codelab-app/platform/assets/74900868/6b10b35d-9dfa-4c04-8192-64d0653dea1a
Part of #3171

fix: expressions are not evaluated in preview mode

---

apps/platform-e2e/src/e2e/builder/form.cy.ts
apps/platform-e2e/src/e2e/store/actions-inside-code-actions.cy.ts
apps/platform-e2e/src/e2e/store/nested-api-actions.cy.ts
apps/platform-e2e/src/support/commands/builder/builder.command.ts
libs/frontend/application/builder/src/sections/explorer-pane/tab-contents/ComponentList.tsx
libs/frontend/application/renderer/src/element/ElementWrapper.tsx
libs/frontend/application/renderer/src/text-editor/TextEditor.tsx
libs/frontend/test/cypress/antd/src/form/form.commands.ts
libs/frontend/test/cypress/utils/src/api/api.command.ts
libs/frontend/test/cypress/utils/src/text-editor/text-editor.command.ts

- in e2e tests do not interact with created elements in builder, go to preview mode and test elements there. This will test expression evaluation, click and other event handlers, and exclude functionality like DnD of elements
- update cypress commands `openPreview` and `openBuilder` to wait until page is loaded
- fix script error when component list was rendered without assigning `key` property
- disable DnD for preview mode
- increase timeout for seed requests. Currently, almost all e2e tests fail in the beginning because 15s was not enough to seed all required data
- fix cy command to interact with inner text editor. After refactoring, text editor activates after double click only.
- update TextEditor component to allow accept plain text as value (in addition to JSON object with …

fix: script error and some e2e tests

---

apps/platform-e2e/src/e2e/store/nested-api-actions.cy.ts
apps/platform-e2e/src/e2e/store/pre-render-api-action-and-set-state.cy.ts
libs/frontend/abstract/application/src/renderer/runtime-action/runtime-action.model.interface.ts
libs/frontend/application/renderer/src/runtime-action.model.ts
libs/frontend/application/renderer/src/runtime-element-prop.model.ts
libs/frontend/application/renderer/src/runtime-element.model.ts
libs/frontend/application/renderer/src/typedPropTransformers/action-type-transformer.ts
libs/frontend/domain/action/src/store/action.factory.ts

Api and code actions that are used as event handlers or pre/post render hooks do not have proper context, and as a result did not have access to read/write state, or use other actions inside.
As a fix, always bind evaluation context to actions.
Fixes #3171

fix: actions running and related e2e specs

---

libs/frontend/abstract/application/src/shared/router.service.interface.ts
libs/frontend/application/shared/store/src/router/router.service.ts
libs/frontend/domain/element/src/services/element.validate.ts
libs/frontend/presentation/view/templates/Dashboard/NavigationBar/default-navigation-bar-items.ts

1. Fix issue when sidebar buttons were not disabled when necessary (when on `/app` page, buttons for `components`, `pageList` and `builder` should be disabled). This happened because `routerServer` assigned values like this: 
```
this.setPath({
appSlug: `${appSlug}`,
componentSlug: `${componentSlug}`,
pageSlug: `${pageSlug}`,
userSlug: `${userSlug}`,
})
```
and in case if slug was undefined - value "undefined" as string was saved.
Before             |  After
2. Fix the issue when apps fail to open when a component with 2 children exists. This happened because of this validation:
```
assertContainsAtMostOne([nextSibling, parentElement])
```
But this is not valid, since the first child will have both references to parentElement, and to …

fix: routing issue and multiple children in component issue

---

libs/frontend/domain/type/src/models/interface-type.model.ts

There was a small truthy/falsy bug that caused variables with a value of 0 not to be included in the state.
Fixes #3213

fix: state expressions not evaluated

---

libs/frontend/abstract/application/src/element/element.service.interface.ts
libs/frontend/abstract/domain/src/element/element-style.model.interface.ts
libs/frontend/application/builder/src/sections/overlay-toolbar/BuilderClickOverlay.tsx
libs/frontend/application/element/src/css-editor/StylesEditor.tsx
libs/frontend/application/element/src/css-editor/style.hook.ts
libs/frontend/application/element/src/services/element.service.ts
libs/frontend/application/renderer/src/text-editor/TextRenderer.tsx
libs/frontend/domain/element/src/store/element-style.model.ts

Allows setting CSS styles for different states (hover, focus...) of elements.
https://github.com/codelab-app/platform/assets/48331678/52fd2f94-2bbd-4f67-bdea-ec773a6e4d0b
Fixes #3221

wip: styles for different states

---

apps/platform/pages/apps/[userSlug]/[appSlug]/pages/[pageSlug]/index.tsx
libs/frontend/abstract/application/src/page/page.application.service.interface.ts
libs/frontend/abstract/application/src/renderer/runtime-element/runtime-element.model.interface.ts
libs/frontend/abstract/application/src/renderer/runtime-prop/runtime-prop.model.interface.ts
libs/frontend/abstract/domain/src/shared/test/root.domain.store.interface.ts
libs/frontend/application/builder/src/index.ts
libs/frontend/application/page/src/services/page.application.service.ts
libs/frontend/application/renderer/src/renderer.application.service.ts
libs/frontend/application/renderer/src/runtime-action.model.ts
libs/frontend/application/renderer/src/runtime-component-prop.model.ts
libs/frontend/application/renderer/src/runtime-element-prop.model.ts
libs/frontend/application/renderer/src/runtime-element.model.ts
libs/frontend/application/renderer/src/runtime-store.model.ts
libs/frontend/application/renderer/src/test/runtime-element-props.spec.ts
libs/frontend/domain/app/src/test/root.test.store.ts
libs/frontend/domain/shared/src/test/root.domain.store.ts
libs/frontend/domain/type/src/models/interface-type.model.ts
libs/frontend/presentation/view/components/codeMirror/completion-options.ts

This PR just revives the old functionality around in-app routing that was done in https://github.com/codelab-app/platform/pull/2843, and will only work when in preview. Also updated the logic around executing pre/post render actions so that they are executed again when navigating
This also includes some fixes around cached state for a page not changing when navigating with a different url props e.g. _going to product-1 then going back to product list then going to product-2_
This also includes fixes on the unit tests for `frontend-application-renderer` and `frontend-domain-app`
https://github.com/codelab-app/platform/assets/27695022/81bb8151-8724-4cbf-b6d9-a2ddea8c3747
Fixes #3227

feat: in-app routing

---

terraform/environments/ci/symlink.sh
terraform/environments/ci/vars-auth0-audience.symlink.tf
terraform/environments/prod/module-do-codelab.tf
terraform/environments/shared/module-auth0.tf
terraform/environments/shared/vars-auth0-audience.tf
terraform/environments/shared/vars-auth0.tf
terraform/modules/auth0-vars/vars-audience.tf
terraform/modules/auth0/action_upsert_user.tf
terraform/modules/auth0/client_machine.tf
terraform/modules/auth0/client_web.tf
terraform/modules/auth0/vars.tf
terraform/modules/circleci/vars-audience.symlink.tf
terraform/modules/digitalocean-codelab/platform-web.tf
terraform/modules/digitalocean-codelab/vars.tf
terraform/modules/symlink.sh

- After migration to DigitalOcean there is no need to have *vercel urls in Auth0 settings
- Remove not used uuid dependency
- Include AUTH0_AUDIENCE env variable to production

refactor: add audience env

---

libs/frontend/abstract/application/src/atom/atom.service.interface.ts
libs/frontend/application/atom/src/services/atom.service.ts
libs/frontend/application/atom/src/use-cases/get-select-atom-options/get-select-atom-options.endpoints.graphql
libs/frontend/application/atom/src/use-cases/get-select-atom-options/get-select-atom-options.endpoints.graphql.gen.ts
libs/frontend/application/element/src/services/element.service.ts
libs/frontend/domain/atom/src/store/atom.filter.ts
libs/shared/abstract/codegen/src/types.api.graphql.gen.ts

Removed the unnecessary fields from `GetSelectAtomOptions` query. For example, loading the API is pointless since we need to load the full API (types for fields and sub-types) when creating element. 
So now we fetch the minimal data to just show options in the `SelectAtomField` and load the necessary API and types once the element is created or the `renderType` is changed.
Fixes #3224

3224 atom and types issues

---

apps/platform-e2e/src/e2e/builder/in-app-routing.cy.ts
apps/platform-e2e/src/e2e/builder/in-app-routing.data.ts
libs/frontend/abstract/application/src/renderer/render.interface.ts
libs/frontend/application/renderer/src/element/ElementWrapper.tsx
libs/frontend/application/renderer/src/element/wrapper.utils.ts
libs/shared/abstract/core/src/element/element.data.interface.ts

This is for improving the in-app routing specs
- when in preview mode, should be able to navigate to static and dynamic page
- when in builder mode, navigation is prevented in the app
- refactored spec to seed setup data via api
Also implemented an override props for props like `href` so it is changed to `#` when in builder mode so it doesn't navigate when clicked.
Fixes #3011

chore: in-app routing specs

---

apps/platform-e2e/src/e2e/component/convert-element-to-component.cy.ts
apps/platform-e2e/src/e2e/component/convert-element-to-component.data.ts
libs/frontend/application/renderer/src/runtime-element.model.ts

This PR fixes the spec `convert-element-to-component.cy` and convert the seeding logic to use the APIs
Relates #3249

fix: convert element to component spec

---

data/export-v3/admin/atoms/AntDesignInputTextArea.json
examples/ai-app/export.json
libs/backend/abstract/codegen/src/ogm-types.gen.ts
libs/backend/data/seed/src/tag/antd/antd-tag-tree.data.ts
libs/frontend/application/element/src/css-editor/tailwind-class-editor/tailwind-classes.ts
libs/frontend/application/renderer/src/atoms/antd/antd-atoms.ts
libs/frontend/application/renderer/src/runtime-component-prop.model.ts
libs/frontend/application/renderer/src/runtime-element.model.ts
libs/shared/abstract/codegen/src/types.api.graphql.gen.ts
libs/shared/abstract/core/src/atom/atom-type.enum.ts
libs/shared/abstract/core/src/component/component.aggregate.interface.ts
libs/shared/data/seed/src/atoms/antd-atom.data.ts
libs/shared/utils/src/expression/constants.ts
libs/shared/utils/src/expression/expression.ts
schema.graphql

This PR contains some additional data and fixes needed while I am creating a chatbot component
- antd textarea component
- some tailwind classes i need to add styling for the chatbox UI
- maybe theres a better way to make the tailwind css strings more dynamic?
- fixed child mapper prev sibling as there was no way to render the instances at the start if there are other children
- fixed regex for expression as it was not able to match when expression have new lines
The chatbot component can be imported by importing the ai app since the import/export for component only is not working. This is the workaround for now.
The chatbot component has a prop called `model` which is `gpt-3.5-turbo` by default. You can try other models or your own fine-tuned model. Also just replace the …

chore: trying openai api in a chatbot custom component

---

apps/platform/pages/components/[componentSlug]/builder.tsx
apps/platform/pages/components/[componentSlug]/index.tsx
apps/platform/pages/components/index.tsx
libs/frontend/application/builder/src/sections/config-pane/ConfigPane-InspectorTabContainer/ConfigPaneInspectorTabContainer.tsx
libs/frontend/application/builder/src/sections/config-pane/ConfigPane-InspectorTabContainer/data.ts
libs/frontend/application/builder/src/sections/explorer-pane/builder-tree/ElementTreeItemElementTitle.tsx
libs/frontend/application/builder/src/sections/explorer-pane/builder-tree/ElementTreeItemTitle.tsx
libs/frontend/application/element/src/use-cases/element/update-element/UpdateElementForm.tsx
libs/frontend/application/renderer/src/model/runtime-component.model.ts
libs/frontend/application/renderer/src/model/runtime-element.model.ts
libs/frontend/presentation/container/src/pageHooks/useRenderedComponent.hook.ts
libs/frontend/presentation/container/src/pageHooks/utils.ts

A couple of problem is fixed in this PR:
1. #3308 issue is that in component builder it was impossible to open components props form after any elmenet in builder tree was selected. The issue is resolved by adding new `Components` tabs (similar to `Page` tab for page builder).
https://github.com/codelab-app/platform/assets/74900868/79972a21-f7d5-4a56-b05a-b7a9c9dc36a0
2. Builder tree issues. The child mapper components, regular components was displaying incorrectly.
https://github.com/codelab-app/platform/assets/74900868/c806e94f-673a-4521-b271-2596f7271c99
Fixes #3308
Fixes #2972

fix: components and explorer tree issues

---

libs/frontend/application/builder/src/hooks/useElementTreeDrop/useElementTreeDrop.hook.ts
libs/frontend/application/renderer/src/renderer.model.ts

- `key` stores runtime-element.model keys. it used to store element.model id for in the past
Fixes #3323

fix: drag drop runtime keys

---

libs/frontend/application/builder/src/sections/content/Builder.tsx
libs/frontend/presentation/codelab-ui/src/layout/CuiResizablePanel/CuiResizablePanel.tsx
libs/frontend/presentation/codelab-ui/src/layout/CuiResizablePanel/components/CollapseControl.tsx
libs/frontend/presentation/codelab-ui/src/layout/CuiResizablePanel/components/CuiResizeHandler.tsx
libs/frontend/presentation/codelab-ui/src/layout/CuiResizablePanel/components/index.ts
libs/frontend/presentation/codelab-ui/src/layout/CuiResizablePanel/hooks/UseResizablePanel.tsx
libs/frontend/presentation/codelab-ui/src/layout/CuiResizablePanel/hooks/index.ts
libs/frontend/presentation/codelab-ui/src/layout/CuiResizablePanel/index.ts
libs/frontend/presentation/codelab-ui/src/layout/index.ts
libs/frontend/presentation/view/src/templates/Dashboard/DashboardTemplate.tsx

Abstracted the resizable panels into a single Cui component that allows for collapsing the panel and adds a button to expand it. 
https://github.com/codelab-app/platform/assets/51242349/151771e2-2a78-4ef0-b3af-eaa7e0fa85bc
Fixes #3382

feat: make resizable panels collapsible

---

libs/frontend/presentation/components/codemirror/src/CodeMirrorInput.tsx

fix: syntax highlight for code mirror editor
